In [8]:
import pandas as pd
pd.options.display.float_format = '{:.8e}'.format
from population import generate_init
from character import CharacterType
#from src.stats import random_stats

N = 100
K = 50
maxStatsValue = 150
type = CharacterType.ARCHER

#equipment_data = random_stats(N, maxStatsValue)
poblacion_inicial = generate_init(N,maxStatsValue,type)

poblacion_inicial

,strength,agility,expertise,resistance,life,height,type,performance
93,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03
30,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
6,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
46,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02
28,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02
...,...,...,...,...,...,...,...,...
86,5,103,1,28,13,1.60000000e+00,CharacterType.ARCHER,2.23907125e+01
78,6,53,1,32,58,1.70000000e+00,CharacterType.ARCHER,1.94388480e+01
22,1,81,23,6,39,1.60000000e+00,CharacterType.ARCHER,1.67527764e+01
96,3,70,3,26,48,1.50000000e+00,CharacterType.ARCHER,1.46286460e+01
75,2,55,9,60,24,1.40000000e+00,CharacterType.ARCHER,1.37995489e+01

In [9]:
#AÃ±ado las columnas de desempeÃ±o relativo y acumulado
from selection import add_relative_accumulate
poblacion_rel_acu = add_relative_accumulate(poblacion_inicial)
poblacion_rel_acu

sum: 26915.117243191766

,strength,agility,expertise,resistance,life,height,type,performance,performance_relative,performance_accumulated
93,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03,4.10168220e-02,4.10168220e-02
30,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02,3.54785984e-02,7.64954204e-02
6,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02,3.43867469e-02,1.10882167e-01
46,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02,3.38358381e-02,1.44718005e-01
28,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02,3.14286095e-02,1.76146615e-01
...,...,...,...,...,...,...,...,...,...,...
86,5,103,1,28,13,1.60000000e+00,CharacterType.ARCHER,2.23907125e+01,8.31900985e-04,9.97599125e-01
78,6,53,1,32,58,1.70000000e+00,CharacterType.ARCHER,1.94388480e+01,7.22227879e-04,9.98321353e-01
22,1,81,23,6,39,1.60000000e+00,CharacterType.ARCHER,1.67527764e+01,6.22429999e-04,9.98943783e-01
96,3,70,3,26,48,1.50000000e+00,CharacterType.ARCHER,1.46286460e+01,5.43510394e-04,9.99487294e-01
75,2,55,9,60,24,1.40000000e+00,CharacterType.ARCHER,1.37995489e+01,5.12706254e-04,1.00000000e+00

#### Seleccion de k indiduos
A*(mÃ©todo1) + (1-A)*(mÃ©todo2)

In [10]:
import numpy as np
#Dado un K
#Si quiero un m1_perc de la selecciÃ³n con metodo1
#K = 120
m1_perc = 0.3
N1 = int(np.round(K * m1_perc))
N2 = K - N1
#N1

In [11]:
from selection import elitist_selection
nueva_poblacion_e = elitist_selection(poblacion_rel_acu,N1)
#nueva_poblacion_e

In [12]:
from selection import roulette_wheel_selection
nueva_poblacion_rul = roulette_wheel_selection(poblacion_rel_acu, N2)
#nueva_poblacion_rul

In [13]:
from selection import universal_selection
    
nueva_poblacion_uni = universal_selection(poblacion_rel_acu, N2)
#nueva_poblacion_uni

In [14]:
from selection import rank_based_selection

nueva_poblacion_rank = rank_based_selection(poblacion_inicial, N2)
#nueva_poblacion_rank

sum: 20.800984073664875
    strength  agility  expertise  resistance  life         height  \
75         2       55          9          60    24 1.40000000e+00
96         3       70          3          26    48 1.50000000e+00
22         1       81         23           6    39 1.60000000e+00
78         6       53          1          32    58 1.70000000e+00
86         5      103          1          28    13 1.60000000e+00
..       ...      ...        ...         ...   ...            ...
28        50        1         63          13    23 2.00000000e+00
46        63       30         49           2     6 2.00000000e+00
6         74        7         48          11    10 1.40000000e+00
30        58        4         62          11    15 1.80000000e+00
93        72        7         60           8     3 1.80000000e+00

                    type    performance  performance_relative  \
75  CharacterType.ARCHER 9.54548457e-03        4.58895816e-04
96  CharacterType.ARCHER 1.00000000e-02        4.80746486e-04
22  CharacterType.ARCHER 1.04761575e-02        5.03637592e-04
78  CharacterType.ARCHER 1.09749877e-02        5.27618675e-04
86  CharacterType.ARCHER 1.14975700e-02        5.52741635e-04
..                   ...            ...                   ...
28  CharacterType.ARCHER 7.92482898e-01        3.80983369e-02
46  CharacterType.ARCHER 8.30217568e-01        3.99124179e-02
6   CharacterType.ARCHER 8.69749003e-01        4.18128777e-02
30  CharacterType.ARCHER 9.11162756e-01        4.38038293e-02
93  CharacterType.ARCHER 9.54548457e-01        4.58895816e-02

    performance_accumulated
75           4.58895816e-04
96           9.39642302e-04
22           1.44327989e-03
78           1.97089857e-03
86           2.52364020e-03
..                      ...
28           8.28581294e-01
46           8.68493711e-01
6            9.10306589e-01
30           9.54110418e-01
93           1.00000000e+00

[100 rows x 10 columns]

In [15]:
import pandas as pd
selection_total = pd.concat([nueva_poblacion_e,nueva_poblacion_rul])
selection_total

,strength,agility,expertise,resistance,life,height,type,performance,performance_relative,performance_accumulated
0,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03,4.10168220e-02,4.10168220e-02
1,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02,3.54785984e-02,7.64954204e-02
2,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02,3.43867469e-02,1.10882167e-01
3,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02,3.38358381e-02,1.44718005e-01
4,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02,3.14286095e-02,1.76146615e-01
5,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02,2.43563271e-02,2.00502942e-01
6,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02,2.37499540e-02,2.24252896e-01
7,30,2,81,28,9,1.60000000e+00,CharacterType.ARCHER,6.22507325e+02,2.31285385e-02,2.47381435e-01
8,100,11,23,5,11,1.80000000e+00,CharacterType.ARCHER,6.07740348e+02,2.25798886e-02,2.69961323e-01
9,57,6,36,31,20,2.00000000e+00,CharacterType.ARCHER,5.97784812e+02,2.22100022e-02,2.92171325e-01
10,41,5,50,6,48,1.60000000e+00,CharacterType.ARCHER,5.90859720e+02,2.19527084e-02,3.14124034e-01
11,32,35,55,13,15,1.50000000e+00,CharacterType.ARCHER,5.57283743e+02,2.07052319e-02,3.34829266e-01
12,52,30,29,18,21,1.90000000e+00,CharacterType.ARCHER,5.31970240e+02,1.97647380e-02,3.54594004e-01
13,50,5,36,45,14,1.70000000e+00,CharacterType.ARCHER,5.20935341e+02,1.93547491e-02,3.73948753e-01
14,58,40,28,4,20,1.30000000e+00,CharacterType.ARCHER,5.17367206e+02,1.92221792e-02,3.93170932e-01
0,19,11,49,70,1,1.60000000e+00,CharacterType.ARCHER,2.80052130e+02,1.04050125e-02,6.70200779e-01
1,25,19,4,48,54,1.90000000e+00,CharacterType.ARCHER,6.11456580e+01,2.27179608e-03,9.84752088e-01
2,30,14,52,40,14,1.70000000e+00,CharacterType.ARCHER,4.66867790e+02,1.73459319e-02,4.64066059e-01
3,64,42,6,20,18,1.50000000e+00,CharacterType.ARCHER,2.29416805e+02,8.52371562e-03,7.55634288e-01
4,35,11,46,48,10,1.80000000e+00,CharacterType.ARCHER,4.94345101e+02,1.83668195e-02,4.11537751e-01
5,22,30,30,43,25,1.30000000e+00,CharacterType.ARCHER,2.22875683e+02,8.28068778e-03,7.80711166e-01
6,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03,4.10168220e-02,4.10168220e-02
7,20,34,8,33,55,2.00000000e+00,CharacterType.ARCHER,8.99458827e+01,3.34183507e-03,9.48710916e-01
8,11,49,77,10,3,2.00000000e+00,CharacterType.ARCHER,2.57706361e+02,9.57478130e-03,7.20275590e-01
9,31,31,16,51,21,1.80000000e+00,CharacterType.ARCHER,2.07179098e+02,7.69749937e-03,7.96110979e-01
10,41,5,50,6,48,1.60000000e+00,CharacterType.ARCHER,5.90859720e+02,2.19527084e-02,3.14124034e-01
11,41,5,50,6,48,1.60000000e+00,CharacterType.ARCHER,5.90859720e+02,2.19527084e-02,3.14124034e-01
12,57,6,36,31,20,2.00000000e+00,CharacterType.ARCHER,5.97784812e+02,2.22100022e-02,2.92171325e-01
13,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02,3.38358381e-02,1.44718005e-01
14,30,2,81,28,9,1.60000000e+00,CharacterType.ARCHER,6.22507325e+02,2.31285385e-02,2.47381435e-01
15,49,26,27,42,6,1.90000000e+00,CharacterType.ARCHER,4.66291816e+02,1.73245322e-02,4.81390592e-01
16,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02,2.43563271e-02,2.00502942e-01
17,20,34,8,33,55,2.00000000e+00,CharacterType.ARCHER,8.99458827e+01,3.34183507e-03,9.48710916e-01
18,21,10,68,39,12,1.60000000e+00,CharacterType.ARCHER,4.02250578e+02,1.49451542e-02,5.43925793e-01
19,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02,3.38358381e-02,1.44718005e-01
20,39,12,19,45,35,1.50000000e+00,CharacterType.ARCHER,2.52778181e+02,9.39168048e-03,7.29667270e-01
21,49,26,27,42,6,1.90000000e+00,CharacterType.ARCHER,4.66291816e+02,1.73245322e-02,4.81390592e-01
22,32,23,13,27,55,1.90000000e+00,CharacterType.ARCHER,1.77151314e+02,6.58185185e-03,8.59949696e-01
23,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02,2.37499540e-02,2.24252896e-01
24,11,49,77,10,3,2.00000000e+00,CharacterType.ARCHER,2.57706361e+02,9.57478130e-03,7.20275590e-01
25,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02,3.54785984e-02,7.64954204e-02
26,30,14,52,40,14,1.70000000e+00,CharacterType.ARCHER,4.66867790e+02,1.73459319e-02,4.64066059e-01
27,33,9,38,61,9,1.30000000e+00,CharacterType.ARCHER,3.54430159e+02,1.31684420e-02,6.13666659e-01
28,39,12,19,45,35,1.50000000e+00,CharacterType.ARCHER,2.52778181e+02,9.39168048e-03,7.29667270e-01
29,30,2,81,28,9,1.60000000e+00,CharacterType.ARCHER,6.22507325e+02,2.31285385e-02,2.47381435e-01
30,39,12,19,45,35,1.50000000e+00,CharacterType.ARCHER,2.52778181e+02,9.39168048e-03,7.29667270e-01
31,1,81,23,6,39,1.60000000e+00,CharacterType.ARCHER,1.67527764e+01,6.22429999e-04,9.98943783e-01
32,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03,4.10168220e-02,4.10168220e-02
33,41,5,50,6,48,1.60000000e+00,CharacterType.ARCHER,5.90859720e+02,2.19527084e-02,3.14124034e-01
34,10,65,16,17,42,1.40000000e+00,CharacterType.ARCHER,8.58041462e+01,3.18795365e-03,9.58513563e-01

In [16]:
from genes import  encode_genes

cromosomas = encode_genes(selection_total)
#cromosomas

In [10]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas)
#cromosomas_decoded2

In [17]:
from crossover import normalize_chromosome

cromosomas_norm = normalize_chromosome(cromosomas)
cromosomas_norm

    strength   agility expertise resistance      life height
1   01001000  00000111  00111100   00001000  00000011    101
2   00111010  00000100  00111110   00001011  00001111    101
3   01001010  00000111  00110000   00001011  00001010    001
4   00111111  00011110  00110001   00000010  00000110    111
5   00110010  00000001  00111111   00001101  00010111    111
6   00110001  00111010  00100110   00000011  00000010    010
7   00110011  00010100  00101000   00000111  00100000    101
8   00011110  00000010  01010001   00011100  00001001    011
9   01100100  00001011  00010111   00000101  00001011    101
10  00111001  00000110  00100100   00011111  00010100    111
11  00101001  00000101  00110010   00000110  00110000    011
12  00100000  00100011  00110111   00001101  00001111    010
13  00110100  00011110  00011101   00010010  00010101    110
14  00110010  00000101  00100100   00101101  00001110    100
15  00111010  00101000  00011100   00000100  00010100    000
16  00010011  00001011  00110001   01000110  00000001    011
17  00011001  00010011  00000100   00110000  00110110    110
18  00011110  00001110  00110100   00101000  00001110    100
19  01000000  00101010  00000110   00010100  00010010    010
20  00100011  00001011  00101110   00110000  00001010    101
21  00010110  00011110  00011110   00101011  00011001    000
22  01001000  00000111  00111100   00001000  00000011    101
23  00010100  00100010  00001000   00100001  00110111    111
24  00001011  00110001  01001101   00001010  00000011    111
25  00011111  00011111  00010000   00110011  00010101    101
26  00101001  00000101  00110010   00000110  00110000    011
27  00101001  00000101  00110010   00000110  00110000    011
28  00111001  00000110  00100100   00011111  00010100    111
29  00111111  00011110  00110001   00000010  00000110    111
30  00011110  00000010  01010001   00011100  00001001    011
31  00110001  00011010  00011011   00101010  00000110    110
32  00110001  00111010  00100110   00000011  00000010    010
33  00010100  00100010  00001000   00100001  00110111    111
34  00010101  00001010  01000100   00100111  00001100    011
35  00111111  00011110  00110001   00000010  00000110    111
36  00100111  00001100  00010011   00101101  00100011    010
37  00110001  00011010  00011011   00101010  00000110    110
38  00100000  00010111  00001101   00011011  00110111    110
39  00110011  00010100  00101000   00000111  00100000    101
40  00001011  00110001  01001101   00001010  00000011    111
41  00111010  00000100  00111110   00001011  00001111    101
42  00011110  00001110  00110100   00101000  00001110    100
43  00100001  00001001  00100110   00111101  00001001    000
44  00100111  00001100  00010011   00101101  00100011    010
45  00011110  00000010  01010001   00011100  00001001    011
46  00100111  00001100  00010011   00101101  00100011    010
47  00000001  01010001  00010111   00000110  00100111    011
48  01001000  00000111  00111100   00001000  00000011    101
49  00101001  00000101  00110010   00000110  00110000    011
50  00001010  01000001  00010000   00010001  00101010    001

In [18]:
from crossover import single_point_crossover, normalize_chromosome

new_individuals = single_point_crossover(cromosomas)
cromosomas_ok1 = normalize_chromosome(new_individuals)

cromosomas_ok1

    strength   agility expertise resistance      life height
1   01000101  00000101  00111010   00001010  00000110    101
2   00111100  00000101  01000000   00001000  00001011    101
3   01000001  00011000  00101000   00001000  00001011    001
4   01001001  00001000  00111101   00000011  00000010    111
5   00110011  00011011  00111000   00001101  00000010    110
6   00110000  00011111  00101101   00000010  00010110    011
7   01010100  00000010  00101101   00000101  00001100    111
8   00001111  00001111  01000101   00011000  00011001    001
9   01011011  00001001  00010010   00011100  00000011    101
10  00111110  00000111  00101011   00000101  00011110    111
11  00011111  00000100  00110110   00001100  00101110    010
12  00101001  00100011  00110010   00000110  00010000    011
13  00111011  00100010  00000100   00011001  00011010    100
14  00101100  00000101  00110100   00100100  00001011    110
15  00010101  00110000  00110110   00000110  00010011    011
16  00110100  00000111  00011001   00111101  00000011    000
17  00010011  00001101  00100111   00100100  00101000    100
18  00101010  00010110  00000101   00111010  00010100    110
19  00111001  00100101  00000101   00101001  00001000    001
20  00100110  00001011  00110110   00010111  00010101    110
21  00001000  00100010  00011111   00101100  00011110    001
22  01001101  00000101  00111000   00001001  00000000    100
23  00011010  00111101  00010000   00101010  00000011    111
24  00001000  00011100  00111100   00000111  00101101    111
25  00110100  00001010  00100001   00001100  00101001    111
26  00011110  00010100  00100000   00100001  00100000    001
27  00110001  00000111  00111100   00001000  00011000    111
28  00110000  00000100  00011110   00011001  00101000    011
29  01001011  00000010  00111011   00000010  00001010    011
30  00011010  00011001  01000101   00010111  00000101    111
31  00100111  00101110  00011000   00100010  00000100    110
32  01000000  00100010  00101110   00000010  00000010    010
33  00010101  00100010  00001000   00101000  00101101    111
34  00010011  00001001  01000010   00100000  00010110    011
35  00110001  00001111  01000000   00010000  00000011    110
36  00110011  00011000  00001110   00011100  00011111    011
37  00110100  00011101  00001110   00101110  00000111    110
38  00011110  00010100  00011001   00011000  00110010    110
39  00101001  00100111  00100001   00001000  00011010    101
40  00001110  00011001  01100010   00001001  00000010    111
41  00100011  00010000  01001000   00001001  00010000    100
42  00110010  00000011  00101101   00100101  00001101    101
43  00101011  00001101  00010101   01000100  00000011    010
44  00011101  00001000  00100010   00101000  00100101    000
45  00000111  00001100  01010010   00101101  00000011    010
46  00111101  00000001  00010010   00011011  00101000    011
47  00110000  00110110  00101000   00000101  00000010    101
48  00000001  00001101  00101101   00001011  01001100    011
49  00100010  00111000  00001101   00000000  00101011    001
50  00001100  00000101  00111010   00011001  00101110    011

In [13]:
#from genes import decode_genes
#cromosomas_decoded = decode_genes(new_individuals)
#cromosomas_decoded

In [19]:
from crossover import two_point_crossover, normalize_chromosome

new_individuals2 = two_point_crossover(cromosomas)
cromosomas_ok2 = normalize_chromosome(new_individuals2)

cromosomas_ok2

    strength   agility expertise resistance      life height
1   01001011  00000110  00110011   00000110  00001001    101
2   00110010  00000100  01001001   00001101  00001000    101
3   00101100  00100000  00110010   00001011  00001010    001
4   01011010  00000101  00101110   00000001  00000101    111
5   00111001  00000001  01001000   00001010  00001000    011
6   00101011  00110011  00100001   00000110  00001111    110
7   00101001  00001110  00111000   00010000  00010110    011
8   00100110  00000011  01000111   00010100  00001111    101
9   01010100  00001001  00100010   00000100  00010000    101
10  01000110  00000110  00010111   00100011  00001101    111
11  00011100  00011100  00101010   00001010  00101000    011
12  00110000  00001000  01000010   00001000  00010010    010
13  00101110  00000011  00101000   00101001  00010010    100
14  00111000  00100011  00010110   00010011  00001111    110
15  00101011  00100010  00110011   00000011  00010001    010
16  00100000  00001101  00010100   01010011  00000001    001
17  00011011  00010000  00000100   00101011  00111010    100
18  00011011  00010000  00110000   00101100  00001100    110
19  01000010  00101010  00001110   00010000  00001010    010
20  00100000  00001010  00100101   00110011  00010001    101
21  00010010  00010010  00100100   00110111  00010101    100
22  01000001  00010010  00110010   00000110  00001000    001
23  00010110  00011111  00000111   00100101  00110010    111
24  00000111  00110101  01010011   00000010  00000011    111
25  00110100  00010000  00010001   00000011  00111011    111
26  00010110  00010010  00101101   00110000  00001110    001
27  01000100  00001000  00101001   00000111  00011000    011
28  00100010  00000011  00101100   00011010  00101000    111
29  00110001  00101111  00011011   00000011  00010110    111
30  00101101  00000001  01010010   00010100  00000000    011
31  00101111  00111000  00100101   00000001  00000101    110
32  00110010  00011010  00011010   00101100  00000010    010
33  00010110  00001011  00001000   00100100  01000110    111
34  00010010  00011110  00111101   00100011  00000011    011
35  00110011  00100001  00111000   00000010  00000110    011
36  00110010  00001010  00001111   00101001  00100000    110
37  00100111  00010100  00011001   00010100  00101011    110
38  00101010  00011110  00001011   00111000  00001001    110
39  00110001  00110010  00100110   00001010  00000000    111
40  00001011  00010001  01001111   00000110  00100011    101
41  00100001  00000101  01001110   00001101  00010011    101
42  00110011  00001011  00101010   00100000  00001011    100
43  00110100  00001100  00001000   00111111  00001100    000
44  00011011  00001001  00100111   00101111  00011011    010
45  00100101  00010001  00100000   00101111  00001111    011
46  00100001  00000010  00111001   00011111  00011000    010
47  00000011  00000011  01100101   00010011  00010110    011
48  00101010  00110011  00011110   00000100  00010100    101
49  00100011  00111011  00001111   00000101  00100010    001
50  00001011  00000001  00111001   00010100  00111011    011

In [20]:
from crossover import uniform_crossover
# Ejemplo de uso

individuals_df = pd.DataFrame(cromosomas)
offspring_df = uniform_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   00111010  00000111  00111100   00001000  00000011    101
1   01001010  00011110  00110001   00001011  00000110    001
2   00110010  00111010  00100110   00001101  00000010    111
3   00011110  00000010  00101000   00000111  00001001    101
4   00111001  00001011  00010111   00000101  00001011    101
5   00101001  00000101  00110111   00001101  00110000    011
6   00110010  00000101  00100100   00010010  00010101    110
7   00010011  00101000  00110001   00000100  00000001    011
8   00011001  00010011  00110100   00101000  00001110    110
9   01000000  00101010  00000110   00010100  00010010    101
10  00010110  00011110  00111100   00001000  00000011    101
11  00010100  00100010  00001000   00001010  00110111    111
12  00101001  00011111  00010000   00000110  00110000    101
13  00111001  00000101  00100100   00000110  00010100    111
14  00011110  00000010  01010001   00000010  00000110    111
15  00110001  00111010  00100110   00000011  00000010    110
16  00010101  00100010  01000100   00100111  00110111    111
17  00100111  00011110  00010011   00101101  00000110    010
18  00100000  00011010  00011011   00101010  00000110    110
19  00110011  00010100  01001101   00001010  00100000    111
20  00011110  00000100  00111110   00101000  00001110    100
21  00100111  00001001  00100110   00111101  00001001    000
22  00011110  00000010  00010011   00011100  00100011    011
23  01001000  01010001  00010111   00000110  00000011    101
24  00101001  00000101  00010000   00010001  00110000    001

In [21]:
from crossover import annular_crossover
individuals_df = pd.DataFrame(cromosomas)
offspring_df = annular_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   01001000  00000100  00111110   00001000  00000011    101
1   00111010  00000111  00111100   00001011  00001111    101
2   01001010  00011110  00110000   00001011  00001010    001
3   00111111  00000111  00110001   00000010  00000110    111
4   00110010  00000001  00100110   00000011  00000010    111
5   00110001  00111010  00111111   00001101  00010111    010
6   00110011  00000010  01010001   00000111  00100000    101
7   00011110  00010100  00101000   00011100  00001001    011
8   01100100  00001011  00010111   00000101  00001011    101
9   00111001  00000110  00100100   00011111  00010100    111
10  00101001  00000101  00110111   00001101  00110000    011
11  00100000  00100011  00110010   00000110  00001111    010
12  00110010  00011110  00011101   00010010  00010101    110
13  00110100  00000101  00100100   00101101  00001110    100
14  00111010  00001011  00011100   00000100  00010100    000
15  00010011  00101000  00110001   01000110  00000001    011
16  00011001  00010011  00110100   00101000  00110110    110
17  00011110  00001110  00000100   00110000  00001110    100
18  01000000  00101010  00101110   00110000  00001010    010
19  00100011  00001011  00000110   00010100  00010010    101
20  01001000  00011110  00011110   00101011  00011001    000
21  00010110  00000111  00111100   00001000  00000011    101
22  00010100  00100010  00001000   00100001  00110111    111
23  00001011  00110001  01001101   00001010  00000011    111
24  00011111  00011111  00110010   00000110  00010101    101
25  00101001  00000101  00010000   00110011  00110000    011
26  00101001  00000101  00100100   00011111  00110000    011
27  00111001  00000110  00110010   00000110  00010100    111
28  00111111  00000010  01010001   00000010  00000110    111
29  00011110  00011110  00110001   00011100  00001001    011
30  00110001  00111010  00100110   00101010  00000110    110
31  00110001  00011010  00011011   00000011  00000010    010
32  00010100  00100010  00001000   00100001  00110111    111
33  00010101  00001010  01000100   00100111  00001100    011
34  00111111  00011110  00110001   00000010  00000110    111
35  00100111  00001100  00010011   00101101  00100011    010
36  00110001  00011010  00001101   00011011  00000110    110
37  00100000  00010111  00011011   00101010  00110111    110
38  00110011  00110001  00101000   00000111  00100000    101
39  00001011  00010100  01001101   00001010  00000011    111
40  00111010  00000100  00111110   00001011  00001111    101
41  00011110  00001110  00110100   00101000  00001110    100
42  00100001  00001100  00010011   00111101  00001001    000
43  00100111  00001001  00100110   00101101  00100011    010
44  00011110  00001100  00010011   00011100  00001001    011
45  00100111  00000010  01010001   00101101  00100011    010
46  00000001  00000111  00111100   00000110  00100111    011
47  01001000  01010001  00010111   00001000  00000011    101
48  00101001  00000101  00010000   00010001  00110000    011
49  00001010  01000001  00110010   00000110  00101010    001

In [23]:
from genes import decode_genes
cromosomas_decoded2 = decode_genes(cromosomas_ok1)
cromosomas_decoded2

,strength,agility,expertise,resistance,life,height
1,6.90000000e+01,5.00000000e+00,5.80000000e+01,1.00000000e+01,6.00000000e+00,1.80000000e+00
2,6.00000000e+01,5.00000000e+00,6.40000000e+01,8.00000000e+00,1.10000000e+01,1.80000000e+00
3,6.50000000e+01,2.40000000e+01,4.00000000e+01,8.00000000e+00,1.10000000e+01,1.40000000e+00
4,7.30000000e+01,8.00000000e+00,6.10000000e+01,3.00000000e+00,2.00000000e+00,2.00000000e+00
5,5.10000000e+01,2.70000000e+01,5.60000000e+01,1.30000000e+01,2.00000000e+00,1.90000000e+00
6,4.80000000e+01,3.10000000e+01,4.50000000e+01,2.00000000e+00,2.20000000e+01,1.60000000e+00
7,8.40000000e+01,2.00000000e+00,4.50000000e+01,5.00000000e+00,1.20000000e+01,2.00000000e+00
8,1.50000000e+01,1.50000000e+01,6.90000000e+01,2.40000000e+01,2.50000000e+01,1.40000000e+00
9,9.10000000e+01,9.00000000e+00,1.80000000e+01,2.80000000e+01,3.00000000e+00,1.80000000e+00
10,6.20000000e+01,7.00000000e+00,4.30000000e+01,5.00000000e+00,3.00000000e+01,2.00000000e+00
11,3.10000000e+01,4.00000000e+00,5.40000000e+01,1.20000000e+01,4.60000000e+01,1.50000000e+00
12,4.10000000e+01,3.50000000e+01,5.00000000e+01,6.00000000e+00,1.60000000e+01,1.60000000e+00
13,5.90000000e+01,3.40000000e+01,4.00000000e+00,2.50000000e+01,2.60000000e+01,1.70000000e+00
14,4.40000000e+01,5.00000000e+00,5.20000000e+01,3.60000000e+01,1.10000000e+01,1.90000000e+00
15,2.10000000e+01,4.80000000e+01,5.40000000e+01,6.00000000e+00,1.90000000e+01,1.60000000e+00
16,5.20000000e+01,7.00000000e+00,2.50000000e+01,6.10000000e+01,3.00000000e+00,1.30000000e+00
17,1.90000000e+01,1.30000000e+01,3.90000000e+01,3.60000000e+01,4.00000000e+01,1.70000000e+00
18,4.20000000e+01,2.20000000e+01,5.00000000e+00,5.80000000e+01,2.00000000e+01,1.90000000e+00
19,5.70000000e+01,3.70000000e+01,5.00000000e+00,4.10000000e+01,8.00000000e+00,1.40000000e+00
20,3.80000000e+01,1.10000000e+01,5.40000000e+01,2.30000000e+01,2.10000000e+01,1.90000000e+00
21,8.00000000e+00,3.40000000e+01,3.10000000e+01,4.40000000e+01,3.00000000e+01,1.40000000e+00
22,7.70000000e+01,5.00000000e+00,5.60000000e+01,9.00000000e+00,0.00000000e+00,1.70000000e+00
23,2.60000000e+01,6.10000000e+01,1.60000000e+01,4.20000000e+01,3.00000000e+00,2.00000000e+00
24,8.00000000e+00,2.80000000e+01,6.00000000e+01,7.00000000e+00,4.50000000e+01,2.00000000e+00
25,5.20000000e+01,1.00000000e+01,3.30000000e+01,1.20000000e+01,4.10000000e+01,2.00000000e+00
26,3.00000000e+01,2.00000000e+01,3.20000000e+01,3.30000000e+01,3.20000000e+01,1.40000000e+00
27,4.90000000e+01,7.00000000e+00,6.00000000e+01,8.00000000e+00,2.40000000e+01,2.00000000e+00
28,4.80000000e+01,4.00000000e+00,3.00000000e+01,2.50000000e+01,4.00000000e+01,1.60000000e+00
29,7.50000000e+01,2.00000000e+00,5.90000000e+01,2.00000000e+00,1.00000000e+01,1.60000000e+00
30,2.60000000e+01,2.50000000e+01,6.90000000e+01,2.30000000e+01,5.00000000e+00,2.00000000e+00
31,3.90000000e+01,4.60000000e+01,2.40000000e+01,3.40000000e+01,4.00000000e+00,1.90000000e+00
32,6.40000000e+01,3.40000000e+01,4.60000000e+01,2.00000000e+00,2.00000000e+00,1.50000000e+00
33,2.10000000e+01,3.40000000e+01,8.00000000e+00,4.00000000e+01,4.50000000e+01,2.00000000e+00
34,1.90000000e+01,9.00000000e+00,6.60000000e+01,3.20000000e+01,2.20000000e+01,1.60000000e+00
35,4.90000000e+01,1.50000000e+01,6.40000000e+01,1.60000000e+01,3.00000000e+00,1.90000000e+00
36,5.10000000e+01,2.40000000e+01,1.40000000e+01,2.80000000e+01,3.10000000e+01,1.60000000e+00
37,5.20000000e+01,2.90000000e+01,1.40000000e+01,4.60000000e+01,7.00000000e+00,1.90000000e+00
38,3.00000000e+01,2.00000000e+01,2.50000000e+01,2.40000000e+01,5.00000000e+01,1.90000000e+00
39,4.10000000e+01,3.90000000e+01,3.30000000e+01,8.00000000e+00,2.60000000e+01,1.80000000e+00
40,1.40000000e+01,2.50000000e+01,9.80000000e+01,9.00000000e+00,2.00000000e+00,2.00000000e+00
41,3.50000000e+01,1.60000000e+01,7.20000000e+01,9.00000000e+00,1.60000000e+01,1.70000000e+00
42,5.00000000e+01,3.00000000e+00,4.50000000e+01,3.70000000e+01,1.30000000e+01,1.80000000e+00
43,4.30000000e+01,1.30000000e+01,2.10000000e+01,6.80000000e+01,3.00000000e+00,1.50000000e+00
44,2.90000000e+01,8.00000000e+00,3.40000000e+01,4.00000000e+01,3.70000000e+01,1.30000000e+00
45,7.00000000e+00,1.20000000e+01,8.20000000e+01,4.50000000e+01,3.00000000e+00,1.50000000e+00
46,6.10000000e+01,1.00000000e+00,1.80000000e+01,2.70000000e+01,4.00000000e+01,1.60000000e+00
47,4.80000000e+01,5.40000000e+01,4.00000000e+01,5.00000000e+00,2.00000000e+00,1.80000000e+00
48,1.00000000e+00,1.30000000e+01,4.50000000e+01,1.10000000e+01,7.60000000e+01,1.60000000e+00
49,3.40000000e+01,5.60000000e+01,1.30000000e+01,0.00000000e+00,4.30000000e+01,1.40000000e+00
50,1.20000000e+01,5.00000000e+00,5.80000000e+01,2.50000000e+01,4.60000000e+01,1.60000000e+00

In [36]:
#columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
#cromosomas_decoded2['sum'] = cromosomas_decoded2[columnas_a_sumar].sum(axis=1) 
#cromosomas_decoded2

In [18]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas_ok)
#cromosomas_decoded2

In [25]:
from mutation import one_gene_mutation
from crossover import normalize_chromosome

mutation_rate = 0.1
  
result = one_gene_mutation(cromosomas_ok2, mutation_rate)
cromosomas_okm = normalize_chromosome(result)

cromosomas_okm

    strength   agility expertise resistance      life height
1   01001100  00000110  00110100   00000110  00001001    101
2   00110010  00000100  01001001   00001101  00001000    101
3   00101011  00100011  00110001   00001010  00001001    001
4   01011100  00000100  00101111   00000001  00000101    111
5   00111001  00000001  01001000   00001010  00001000    011
6   01001011  00100100  00010111   00000100  00001010    110
7   00101001  00001110  00111000   00010000  00010110    011
8   00100110  00000011  01001000   00010100  00001111    101
9   01010101  00001001  00100010   00000100  00010000    101
10  00100000  00000010  00001010   00010000  01011000    111
11  00011100  00011100  00101010   00001010  00101000    011
12  00110000  00001000  01000010   00001000  00010010    010
13  00101110  00000011  00101000   00101001  00010010    100
14  00111000  00100011  00010111   00010011  00001111    110
15  00010111  01010111  00011011   00000001  00001001    010
16  00101100  00001011  00010010   01001011  00000000    001
17  00011011  00010000  00000100   00101011  00111010    100
18  00010110  00001101  00101000   00100100  00100100    110
19  01000010  00101010  00001110   00010000  00001010    010
20  00100000  00001010  00100101   00110100  00010001    100
21  00010010  00010010  00100100   00110111  00010101    110
22  01000010  00010010  00110011   00000110  00001000    001
23  00010110  00011111  00000111   00100101  00110011    101
24  00010101  00110000  01001011   00000001  00000010    111
25  00110101  00010000  00010001   00000011  00111100    101
26  00010110  00010010  00101101   00110000  00001110    001
27  01000100  00001000  00101001   00000111  00011000    011
28  00100100  00000011  00101111   00010011  00101011    111
29  00110001  00101111  00011011   00000011  00010110    111
30  00101101  00000001  01010011   00010100  00000000    011
31  00110000  00111001  00100110   00000001  00000101    110
32  00100111  00010100  00010100   00100011  00100001    010
33  00010110  00001011  00001000   00100100  01000111    111
34  01001111  00010000  00100001   00010011  00000001    011
35  00110011  00100001  00111000   00000010  00000110    011
36  00110010  00001010  00001111   00101001  00100000    110
37  00110011  00011010  00100001   00011010  00001011    110
38  00101010  00011110  00001011   00111000  00001001    110
39  00110010  00110011  00100110   00001010  00000000    110
40  00001011  00010001  01010000   00000110  00100011    101
41  00100001  00000101  01001111   00001101  00010011    101
42  00101110  00001010  00100110   00101100  00001010    100
43  00110101  00001100  00001000   01000000  00001100    000
44  00011000  00001000  00110010   00101010  00011000    010
45  00100101  00010001  00100000   00101111  00001111    011
46  00100001  00000010  00111010   00011111  00011000    010
47  00000010  00110010  01000101   00001101  00001111    011
48  00101010  00110100  00011110   00000100  00010100    101
49  00100011  00111011  00001111   00000101  00100010    001
50  00001001  00011011  00101111   00010000  00110001    011

In [37]:
from genes import decode_genes
cromosomas_decoded2m = decode_genes(cromosomas_okm)
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height
1,7.60000000e+01,6.00000000e+00,5.20000000e+01,6.00000000e+00,9.00000000e+00,1.80000000e+00
2,5.00000000e+01,4.00000000e+00,7.30000000e+01,1.30000000e+01,8.00000000e+00,1.80000000e+00
3,4.30000000e+01,3.50000000e+01,4.90000000e+01,1.00000000e+01,9.00000000e+00,1.40000000e+00
4,9.20000000e+01,4.00000000e+00,4.70000000e+01,1.00000000e+00,5.00000000e+00,2.00000000e+00
5,5.70000000e+01,1.00000000e+00,7.20000000e+01,1.00000000e+01,8.00000000e+00,1.60000000e+00
6,7.50000000e+01,3.60000000e+01,2.30000000e+01,4.00000000e+00,1.00000000e+01,1.90000000e+00
7,4.10000000e+01,1.40000000e+01,5.60000000e+01,1.60000000e+01,2.20000000e+01,1.60000000e+00
8,3.80000000e+01,3.00000000e+00,7.20000000e+01,2.00000000e+01,1.50000000e+01,1.80000000e+00
9,8.50000000e+01,9.00000000e+00,3.40000000e+01,4.00000000e+00,1.60000000e+01,1.80000000e+00
10,3.20000000e+01,2.00000000e+00,1.00000000e+01,1.60000000e+01,8.80000000e+01,2.00000000e+00
11,2.80000000e+01,2.80000000e+01,4.20000000e+01,1.00000000e+01,4.00000000e+01,1.60000000e+00
12,4.80000000e+01,8.00000000e+00,6.60000000e+01,8.00000000e+00,1.80000000e+01,1.50000000e+00
13,4.60000000e+01,3.00000000e+00,4.00000000e+01,4.10000000e+01,1.80000000e+01,1.70000000e+00
14,5.60000000e+01,3.50000000e+01,2.30000000e+01,1.90000000e+01,1.50000000e+01,1.90000000e+00
15,2.30000000e+01,8.70000000e+01,2.70000000e+01,1.00000000e+00,9.00000000e+00,1.50000000e+00
16,4.40000000e+01,1.10000000e+01,1.80000000e+01,7.50000000e+01,0.00000000e+00,1.40000000e+00
17,2.70000000e+01,1.60000000e+01,4.00000000e+00,4.30000000e+01,5.80000000e+01,1.70000000e+00
18,2.20000000e+01,1.30000000e+01,4.00000000e+01,3.60000000e+01,3.60000000e+01,1.90000000e+00
19,6.60000000e+01,4.20000000e+01,1.40000000e+01,1.60000000e+01,1.00000000e+01,1.50000000e+00
20,3.20000000e+01,1.00000000e+01,3.70000000e+01,5.20000000e+01,1.70000000e+01,1.70000000e+00
21,1.80000000e+01,1.80000000e+01,3.60000000e+01,5.50000000e+01,2.10000000e+01,1.90000000e+00
22,6.60000000e+01,1.80000000e+01,5.10000000e+01,6.00000000e+00,8.00000000e+00,1.40000000e+00
23,2.20000000e+01,3.10000000e+01,7.00000000e+00,3.70000000e+01,5.10000000e+01,1.80000000e+00
24,2.10000000e+01,4.80000000e+01,7.50000000e+01,1.00000000e+00,2.00000000e+00,2.00000000e+00
25,5.30000000e+01,1.60000000e+01,1.70000000e+01,3.00000000e+00,6.00000000e+01,1.80000000e+00
26,2.20000000e+01,1.80000000e+01,4.50000000e+01,4.80000000e+01,1.40000000e+01,1.40000000e+00
27,6.80000000e+01,8.00000000e+00,4.10000000e+01,7.00000000e+00,2.40000000e+01,1.60000000e+00
28,3.60000000e+01,3.00000000e+00,4.70000000e+01,1.90000000e+01,4.30000000e+01,2.00000000e+00
29,4.90000000e+01,4.70000000e+01,2.70000000e+01,3.00000000e+00,2.20000000e+01,2.00000000e+00
30,4.50000000e+01,1.00000000e+00,8.30000000e+01,2.00000000e+01,0.00000000e+00,1.60000000e+00
31,4.80000000e+01,5.70000000e+01,3.80000000e+01,1.00000000e+00,5.00000000e+00,1.90000000e+00
32,3.90000000e+01,2.00000000e+01,2.00000000e+01,3.50000000e+01,3.30000000e+01,1.50000000e+00
33,2.20000000e+01,1.10000000e+01,8.00000000e+00,3.60000000e+01,7.10000000e+01,2.00000000e+00
34,7.90000000e+01,1.60000000e+01,3.30000000e+01,1.90000000e+01,1.00000000e+00,1.60000000e+00
35,5.10000000e+01,3.30000000e+01,5.60000000e+01,2.00000000e+00,6.00000000e+00,1.60000000e+00
36,5.00000000e+01,1.00000000e+01,1.50000000e+01,4.10000000e+01,3.20000000e+01,1.90000000e+00
37,5.10000000e+01,2.60000000e+01,3.30000000e+01,2.60000000e+01,1.10000000e+01,1.90000000e+00
38,4.20000000e+01,3.00000000e+01,1.10000000e+01,5.60000000e+01,9.00000000e+00,1.90000000e+00
39,5.00000000e+01,5.10000000e+01,3.80000000e+01,1.00000000e+01,0.00000000e+00,1.90000000e+00
40,1.10000000e+01,1.70000000e+01,8.00000000e+01,6.00000000e+00,3.50000000e+01,1.80000000e+00
41,3.30000000e+01,5.00000000e+00,7.90000000e+01,1.30000000e+01,1.90000000e+01,1.80000000e+00
42,4.60000000e+01,1.00000000e+01,3.80000000e+01,4.40000000e+01,1.00000000e+01,1.70000000e+00
43,5.30000000e+01,1.20000000e+01,8.00000000e+00,6.40000000e+01,1.20000000e+01,1.30000000e+00
44,2.40000000e+01,8.00000000e+00,5.00000000e+01,4.20000000e+01,2.40000000e+01,1.50000000e+00
45,3.70000000e+01,1.70000000e+01,3.20000000e+01,4.70000000e+01,1.50000000e+01,1.60000000e+00
46,3.30000000e+01,2.00000000e+00,5.80000000e+01,3.10000000e+01,2.40000000e+01,1.50000000e+00
47,2.00000000e+00,5.00000000e+01,6.90000000e+01,1.30000000e+01,1.50000000e+01,1.60000000e+00
48,4.20000000e+01,5.20000000e+01,3.00000000e+01,4.00000000e+00,2.00000000e+01,1.80000000e+00
49,3.50000000e+01,5.90000000e+01,1.50000000e+01,5.00000000e+00,3.40000000e+01,1.40000000e+00
50,9.00000000e+00,2.70000000e+01,4.70000000e+01,1.60000000e+01,4.90000000e+01,1.60000000e+00

In [38]:
columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
cromosomas_decoded2m['sum'] = cromosomas_decoded2m[columnas_a_sumar].sum(axis=1) 
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height,sum
1,7.60000000e+01,6.00000000e+00,5.20000000e+01,6.00000000e+00,9.00000000e+00,1.80000000e+00,1.49000000e+02
2,5.00000000e+01,4.00000000e+00,7.30000000e+01,1.30000000e+01,8.00000000e+00,1.80000000e+00,1.48000000e+02
3,4.30000000e+01,3.50000000e+01,4.90000000e+01,1.00000000e+01,9.00000000e+00,1.40000000e+00,1.46000000e+02
4,9.20000000e+01,4.00000000e+00,4.70000000e+01,1.00000000e+00,5.00000000e+00,2.00000000e+00,1.49000000e+02
5,5.70000000e+01,1.00000000e+00,7.20000000e+01,1.00000000e+01,8.00000000e+00,1.60000000e+00,1.48000000e+02
6,7.50000000e+01,3.60000000e+01,2.30000000e+01,4.00000000e+00,1.00000000e+01,1.90000000e+00,1.48000000e+02
7,4.10000000e+01,1.40000000e+01,5.60000000e+01,1.60000000e+01,2.20000000e+01,1.60000000e+00,1.49000000e+02
8,3.80000000e+01,3.00000000e+00,7.20000000e+01,2.00000000e+01,1.50000000e+01,1.80000000e+00,1.48000000e+02
9,8.50000000e+01,9.00000000e+00,3.40000000e+01,4.00000000e+00,1.60000000e+01,1.80000000e+00,1.48000000e+02
10,3.20000000e+01,2.00000000e+00,1.00000000e+01,1.60000000e+01,8.80000000e+01,2.00000000e+00,1.48000000e+02
11,2.80000000e+01,2.80000000e+01,4.20000000e+01,1.00000000e+01,4.00000000e+01,1.60000000e+00,1.48000000e+02
12,4.80000000e+01,8.00000000e+00,6.60000000e+01,8.00000000e+00,1.80000000e+01,1.50000000e+00,1.48000000e+02
13,4.60000000e+01,3.00000000e+00,4.00000000e+01,4.10000000e+01,1.80000000e+01,1.70000000e+00,1.48000000e+02
14,5.60000000e+01,3.50000000e+01,2.30000000e+01,1.90000000e+01,1.50000000e+01,1.90000000e+00,1.48000000e+02
15,2.30000000e+01,8.70000000e+01,2.70000000e+01,1.00000000e+00,9.00000000e+00,1.50000000e+00,1.47000000e+02
16,4.40000000e+01,1.10000000e+01,1.80000000e+01,7.50000000e+01,0.00000000e+00,1.40000000e+00,1.48000000e+02
17,2.70000000e+01,1.60000000e+01,4.00000000e+00,4.30000000e+01,5.80000000e+01,1.70000000e+00,1.48000000e+02
18,2.20000000e+01,1.30000000e+01,4.00000000e+01,3.60000000e+01,3.60000000e+01,1.90000000e+00,1.47000000e+02
19,6.60000000e+01,4.20000000e+01,1.40000000e+01,1.60000000e+01,1.00000000e+01,1.50000000e+00,1.48000000e+02
20,3.20000000e+01,1.00000000e+01,3.70000000e+01,5.20000000e+01,1.70000000e+01,1.70000000e+00,1.48000000e+02
21,1.80000000e+01,1.80000000e+01,3.60000000e+01,5.50000000e+01,2.10000000e+01,1.90000000e+00,1.48000000e+02
22,6.60000000e+01,1.80000000e+01,5.10000000e+01,6.00000000e+00,8.00000000e+00,1.40000000e+00,1.49000000e+02
23,2.20000000e+01,3.10000000e+01,7.00000000e+00,3.70000000e+01,5.10000000e+01,1.80000000e+00,1.48000000e+02
24,2.10000000e+01,4.80000000e+01,7.50000000e+01,1.00000000e+00,2.00000000e+00,2.00000000e+00,1.47000000e+02
25,5.30000000e+01,1.60000000e+01,1.70000000e+01,3.00000000e+00,6.00000000e+01,1.80000000e+00,1.49000000e+02
26,2.20000000e+01,1.80000000e+01,4.50000000e+01,4.80000000e+01,1.40000000e+01,1.40000000e+00,1.47000000e+02
27,6.80000000e+01,8.00000000e+00,4.10000000e+01,7.00000000e+00,2.40000000e+01,1.60000000e+00,1.48000000e+02
28,3.60000000e+01,3.00000000e+00,4.70000000e+01,1.90000000e+01,4.30000000e+01,2.00000000e+00,1.48000000e+02
29,4.90000000e+01,4.70000000e+01,2.70000000e+01,3.00000000e+00,2.20000000e+01,2.00000000e+00,1.48000000e+02
30,4.50000000e+01,1.00000000e+00,8.30000000e+01,2.00000000e+01,0.00000000e+00,1.60000000e+00,1.49000000e+02
31,4.80000000e+01,5.70000000e+01,3.80000000e+01,1.00000000e+00,5.00000000e+00,1.90000000e+00,1.49000000e+02
32,3.90000000e+01,2.00000000e+01,2.00000000e+01,3.50000000e+01,3.30000000e+01,1.50000000e+00,1.47000000e+02
33,2.20000000e+01,1.10000000e+01,8.00000000e+00,3.60000000e+01,7.10000000e+01,2.00000000e+00,1.48000000e+02
34,7.90000000e+01,1.60000000e+01,3.30000000e+01,1.90000000e+01,1.00000000e+00,1.60000000e+00,1.48000000e+02
35,5.10000000e+01,3.30000000e+01,5.60000000e+01,2.00000000e+00,6.00000000e+00,1.60000000e+00,1.48000000e+02
36,5.00000000e+01,1.00000000e+01,1.50000000e+01,4.10000000e+01,3.20000000e+01,1.90000000e+00,1.48000000e+02
37,5.10000000e+01,2.60000000e+01,3.30000000e+01,2.60000000e+01,1.10000000e+01,1.90000000e+00,1.47000000e+02
38,4.20000000e+01,3.00000000e+01,1.10000000e+01,5.60000000e+01,9.00000000e+00,1.90000000e+00,1.48000000e+02
39,5.00000000e+01,5.10000000e+01,3.80000000e+01,1.00000000e+01,0.00000000e+00,1.90000000e+00,1.49000000e+02
40,1.10000000e+01,1.70000000e+01,8.00000000e+01,6.00000000e+00,3.50000000e+01,1.80000000e+00,1.49000000e+02
41,3.30000000e+01,5.00000000e+00,7.90000000e+01,1.30000000e+01,1.90000000e+01,1.80000000e+00,1.49000000e+02
42,4.60000000e+01,1.00000000e+01,3.80000000e+01,4.40000000e+01,1.00000000e+01,1.70000000e+00,1.48000000e+02
43,5.30000000e+01,1.20000000e+01,8.00000000e+00,6.40000000e+01,1.20000000e+01,1.30000000e+00,1.49000000e+02
44,2.40000000e+01,8.00000000e+00,5.00000000e+01,4.20000000e+01,2.40000000e+01,1.50000000e+00,1.48000000e+02
45,3.70000000e+01,1.70000000e+01,3.20000000e+01,4.70000000e+01,1.50000000e+01,1.60000000e+00,1.48000000e+02
46,3.30000000e+01,2.00000000e+00,5.80000000e+01,3.10000000e+01,2.40000000e+01,1.50000000e+00,1.48000000e+02
47,2.00000000e+00,5.00000000e+01,6.90000000e+01,1.30000000e+01,1.50000000e+01,1.60000000e+00,1.49000000e+02
48,4.20000000e+01,5.20000000e+01,3.00000000e+01,4.00000000e+00,2.00000000e+01,1.80000000e+00,1.48000000e+02
49,3.50000000e+01,5.90000000e+01,1.50000000e+01,5.00000000e+00,3.40000000e+01,1.40000000e+00,1.48000000e+02
50,9.00000000e+00,2.70000000e+01,4.70000000e+01,1.60000000e+01,4.90000000e+01,1.60000000e+00,1.48000000e+02

In [27]:
from mutation import multi_gene_mutation

# Ejemplo de uso:
mutation_rate = 0.8
resultmp = multi_gene_mutation(cromosomas_ok1, mutation_rate)
resultmp

    strength   agility expertise resistance      life height
0   01000101  00000101  00111010   00001010  00000110    101
1   00111100  00000101  01000000   00001000  00001011    101
2   01000001  00011000  00101000   00001000  00001011    001
3   01001001  00001000  00111101   00000011  00000010    111
4   00110011  00011011  00111000   00001101  00000010    110
5   00110000  00011111  00101101   00000010  00010110    011
6   01010100  00000010  00101101   00000101  00001100    111
7   00001111  00001111  01000101   00011000  00011001    001
8   01011011  00001001  00010010   00011100  00000011    101
9   00111110  00000111  00101011   00000101  00011110    111
10  00011111  00000100  00110110   00001100  00101110    010
11  00101001  00100011  00110010   00000110  00010000    011
12  00111011  00100010  00000100   00011001  00011010    100
13  00101100  00000101  00110100   00100100  00001011    110
14  00010101  00110000  00110110   00000110  00010011    011
15  00110100  00000111  00011001   00111101  00000011    000
16  00010011  00001101  00100111   00100100  00101000    100
17  00101010  00010110  00000101   00111010  00010100    110
18  00111001  00100101  00000101   00101001  00001000    001
19  00100110  00001011  00110110   00010111  00010101    110
20  00001000  00100010  00011111   00101100  00011110    001
21  01001101  00000101  00111000   00001001  00000000    100
22  00011010  00111101  00010000   00101010  00000011    111
23  00001000  00011100  00111100   00000111  00101101    111
24  00110100  00001010  00100001   00001100  00101001    111
25  00011110  00010100  00100000   00100001  00100000    001
26  00110001  00000111  00111100   00001000  00011000    111
27  00110000  00000100  00011110   00011001  00101000    011
28  01001011  00000010  00111011   00000010  00001010    011
29  00011010  00011001  01000101   00010111  00000101    111
30  00100111  00101110  00011000   00100010  00000100    110
31  01000000  00100010  00101110   00000010  00000010    010
32  00010101  00100010  00001000   00101000  00101101    111
33  00010011  00001001  01000010   00100000  00010110    011
34  00110001  00001111  01000000   00010000  00000011    110
35  00110011  00011000  00001110   00011100  00011111    011
36  00110100  00011101  00001110   00101110  00000111    110
37  00011110  00010100  00011001   00011000  00110010    110
38  00101001  00100111  00100001   00001000  00011010    101
39  00001110  00011001  01100010   00001001  00000010    111
40  00100011  00010000  01001000   00001001  00010000    100
41  00110010  00000011  00101101   00100101  00001101    101
42  00101011  00001101  00010101   01000100  00000011    010
43  00011101  00001000  00100010   00101000  00100101    000
44  00000111  00001100  01010010   00101101  00000011    010
45  00111101  00000001  00010010   00011011  00101000    011
46  00110000  00110110  00101000   00000101  00000010    101
47  00000001  00001101  00101101   00001011  01001100    011
48  00100010  00111000  00001101   00000000  00101011    001
49  00001100  00000101  00111010   00011001  00101110    011

    strength   agility expertise resistance      life height
0   11110010  10111010  11000101   10110001  11110100    101
1   10010011  11100010  01000000   10010111  11110000    101
2   01000001  01000111  00101000   00001000  11100101    110
3   10110101  11111111  01100000   11111110  00000010    000
4   00110011  00011011  11000011   11110010  00000010    011
5   01001110  00100100  00101101   11110101  11101001    101
6   11100001  10101101  00101101   11111011  11110011    111
7   01110010  01110001  10111010   10110111  00011001    010
8   01011011  11110010  00010010   00011100  10011110    101
9   00111110  11111000  10010100   00111010  11100000    000
10  10001101  11111001  00110110   11111011  11010100    010
11  00101001  11000110  00110010   00000110  01101111    100
12  11001100  11011110  10111011   11100110  11100101    010
13  11110011  11111010  11101101   11110011  10101100    000
14  11001000  11011100  00110110   11111001  10100100    100
15  00110100  11111110  01110110   11000010  11111101    000
16  10010100  11110000  01011101   11011011  01010111    110
17  00101010  00010110  11101111   01011101  11101011    000
18  11000100  10011010  11111001   11110101  11111111    010
19  10001001  00001011  11111011   10101100  11111010    001
20  01010101  11001100  00011111   01010011  11100100    110
21  10111010  10001110  00000101   00001001  11011111    011
22  11100101  01010010  01011111   10010100  10111000    001
23  11110101  10100011  11000111   01111000  11010011    001
24  01111011  11000101  10011110   10110101  00101001    000
25  11101101  01101011  11011111   01111110  00100000    111
26  11001101  11111000  11000111   11111111  10000111    000
27  10001101  11011011  11100001   00011001  11100111    100
28  00110100  11101101  01010110   10111011  00001010    100
29  10101101  11100010  01000101   10101001  01111010    000
30  11010000  11110001  01101111   01010101  11111011    110
31  01000000  11011101  11010001   11011100  00000010    111
32  10101010  00100010  00001000   00101000  10010010    000
33  00101100  01111110  00110101   11010110  01101001    000
34  11001010  11010000  00111111   11111111  10001010    001
35  11000000  11110100  11110011   10000011  00011111    100
36  01101000  11100011  11110110   11010101  11110000    110
37  01110011  00101011  10100110   11100110  11101101    000
38  00010110  11010001  10011111   10010111  11100100    011
39  11110011  01101110  01100010   01100110  11111101    111
40  01111100  00010000  10100011   11110110  00001101    011
41  11101101  00000011  11010010   11111010  00001101    010
42  11010110  11110000  00010101   10110001  00000011    101
43  11110010  00001000  00111100   11010111  00100101    000
44  11111100  11110001  10101101   11010010  11111100    100
45  11000111  11111011  10101101   10100100  11011110    101
46  11001101  11001101  01010111   11011010  11010101    010
47  11001110  10110000  10100001   11110110  10111011    011
48  11011101  10000101  11010111   11111111  00101011    110
49  11010010  11010010  11100100   01000110  11000001    101

In [28]:
from mutation import multi_gene_mutation_uniform

# Ejemplo de uso:
mutation_rate = 0.7
resultmu = multi_gene_mutation_uniform(cromosomas_ok1, mutation_rate)
resultmu

    strength   agility expertise resistance      life height
0   01000101  00000101  00111010   00001010  00000110    101
1   00111100  00000101  01000000   00001000  00001011    101
2   01000001  00011000  00101000   00001000  00001011    001
3   01001001  00001000  00111101   00000011  00000010    111
4   00110011  00011011  00111000   00001101  00000010    110
5   00110000  00011111  00101101   00000010  00010110    011
6   01010100  00000010  00101101   00000101  00001100    111
7   00001111  00001111  01000101   00011000  00011001    001
8   01011011  00001001  00010010   00011100  00000011    101
9   00111110  00000111  00101011   00000101  00011110    111
10  00011111  00000100  00110110   00001100  00101110    010
11  00101001  00100011  00110010   00000110  00010000    011
12  00111011  00100010  00000100   00011001  00011010    100
13  00101100  00000101  00110100   00100100  00001011    110
14  00010101  00110000  00110110   00000110  00010011    011
15  00110100  00000111  00011001   00111101  00000011    000
16  00010011  00001101  00100111   00100100  00101000    100
17  00101010  00010110  00000101   00111010  00010100    110
18  00111001  00100101  00000101   00101001  00001000    001
19  00100110  00001011  00110110   00010111  00010101    110
20  00001000  00100010  00011111   00101100  00011110    001
21  01001101  00000101  00111000   00001001  00000000    100
22  00011010  00111101  00010000   00101010  00000011    111
23  00001000  00011100  00111100   00000111  00101101    111
24  00110100  00001010  00100001   00001100  00101001    111
25  00011110  00010100  00100000   00100001  00100000    001
26  00110001  00000111  00111100   00001000  00011000    111
27  00110000  00000100  00011110   00011001  00101000    011
28  01001011  00000010  00111011   00000010  00001010    011
29  00011010  00011001  01000101   00010111  00000101    111
30  00100111  00101110  00011000   00100010  00000100    110
31  01000000  00100010  00101110   00000010  00000010    010
32  00010101  00100010  00001000   00101000  00101101    111
33  00010011  00001001  01000010   00100000  00010110    011
34  00110001  00001111  01000000   00010000  00000011    110
35  00110011  00011000  00001110   00011100  00011111    011
36  00110100  00011101  00001110   00101110  00000111    110
37  00011110  00010100  00011001   00011000  00110010    110
38  00101001  00100111  00100001   00001000  00011010    101
39  00001110  00011001  01100010   00001001  00000010    111
40  00100011  00010000  01001000   00001001  00010000    100
41  00110010  00000011  00101101   00100101  00001101    101
42  00101011  00001101  00010101   01000100  00000011    010
43  00011101  00001000  00100010   00101000  00100101    000
44  00000111  00001100  01010010   00101101  00000011    010
45  00111101  00000001  00010010   00011011  00101000    011
46  00110000  00110110  00101000   00000101  00000010    101
47  00000001  00001101  00101101   00001011  01001100    011
48  00100010  00111000  00001101   00000000  00101011    001
49  00001100  00000101  00111010   00011001  00101110    011

    strength   agility expertise resistance      life height
0   10111010  11111010  11000101   11110101  11111001    101
1   11000011  11111010  10111111   11110111  11110100    010
2   01000001  11100111  00101000   11110111  11110100    110
3   10110110  00001000  11000010   11111100  11111101    000
4   00110011  11100100  11000111   11110010  11111101    110
5   11001111  00011111  00101101   11111101  11101001    100
6   01010100  11111101  11010010   00000101  11110011    000
7   11110000  11110000  10111010   11100111  11100110    001
8   10100100  11110110  11101101   11100011  11111100    010
9   00111110  00000111  11010100   00000101  11100001    000
10  11100000  11111011  00110110   00001100  00101110    101
11  00101001  11011100  11001101   11111001  00010000    011
12  00111011  11011101  11111011   11100110  11100101    011
13  00101100  11111010  11001011   11011011  11110100    110
14  11101010  11001111  11001001   00000110  11101100    100
15  11001011  11111000  00011001   00111101  11111100    111
16  11101100  11110010  11011000   00100100  11010111    011
17  00101010  11101001  00000101   11000101  00010100    001
18  11000110  11011010  11111010   11010110  11110111    001
19  11011001  11110100  11001001   11101000  11101010    001
20  11110111  00100010  11100000   11010011  11100001    001
21  01001101  11111010  11000111   11110110  00000000    011
22  11100101  11000010  11101111   11010101  11111100    000
23  11110111  00011100  11000011   00000111  00101101    000
24  11001011  00001010  11011110   11110011  11010110    000
25  11100001  11101011  00100000   00100001  11011111    110
26  00110001  11111000  00111100   00001000  11100111    000
27  11001111  00000100  11100001   11100110  11010111    100
28  01001011  11111101  11000100   11111101  00001010    011
29  11100101  00011001  10111010   11101000  11111010    111
30  00100111  11010001  00011000   00100010  11111011    001
31  01000000  00100010  00101110   11111101  00000010    010
32  11101010  00100010  11110111   11010111  11010010    000
33  11101100  00001001  10111101   11011111  11101001    011
34  00110001  11110000  01000000   11101111  11111100    001
35  11001100  11100111  00001110   00011100  11100000    100
36  11001011  11100010  11110001   11010001  11111000    110
37  11100001  00010100  11100110   11100111  11001101    001
38  00101001  11011000  00100001   00001000  11100101    101
39  11110001  11100110  01100010   00001001  11111101    111
40  11011100  11101111  10110111   11110110  11101111    100
41  00110010  00000011  11010010   00100101  11110010    010
42  11010100  00001101  00010101   10111011  00000011    010
43  11100010  11110111  00100010   11010111  11011010    000
44  11111000  11110011  10101101   00101101  11111100    101
45  11000010  11111110  11101101   11100100  00101000    100
46  00110000  11001001  11010111   11111010  11111101    010
47  11111110  00001101  11010010   11110100  10110011    100
48  11011101  11000111  00001101   11111111  11010100    110
49  00001100  11111010  11000101   00011001  00101110    100

In [29]:
from population import eval_performace

new_generation = eval_performace(cromosomas_decoded2,type)
new_generation

,strength,agility,expertise,resistance,life,height,type,performance
4,9.20000000e+01,4.00000000e+00,4.70000000e+01,1.00000000e+00,5.00000000e+00,2.00000000e+00,CharacterType.ARCHER,1.04759384e+03
1,7.60000000e+01,6.00000000e+00,5.20000000e+01,6.00000000e+00,9.00000000e+00,1.80000000e+00,CharacterType.ARCHER,1.02131540e+03
5,5.70000000e+01,1.00000000e+00,7.20000000e+01,1.00000000e+01,8.00000000e+00,1.60000000e+00,CharacterType.ARCHER,1.00858183e+03
2,5.00000000e+01,4.00000000e+00,7.30000000e+01,1.30000000e+01,8.00000000e+00,1.80000000e+00,CharacterType.ARCHER,9.51254087e+02
22,6.60000000e+01,1.80000000e+01,5.10000000e+01,6.00000000e+00,8.00000000e+00,1.40000000e+00,CharacterType.ARCHER,9.27844973e+02
30,4.50000000e+01,1.00000000e+00,8.30000000e+01,2.00000000e+01,0.00000000e+00,1.60000000e+00,CharacterType.ARCHER,9.07342577e+02
12,4.80000000e+01,8.00000000e+00,6.60000000e+01,8.00000000e+00,1.80000000e+01,1.50000000e+00,CharacterType.ARCHER,8.53257524e+02
35,5.10000000e+01,3.30000000e+01,5.60000000e+01,2.00000000e+00,6.00000000e+00,1.60000000e+00,CharacterType.ARCHER,8.33415753e+02
9,8.50000000e+01,9.00000000e+00,3.40000000e+01,4.00000000e+00,1.60000000e+01,1.80000000e+00,CharacterType.ARCHER,7.74205995e+02
27,6.80000000e+01,8.00000000e+00,4.10000000e+01,7.00000000e+00,2.40000000e+01,1.60000000e+00,CharacterType.ARCHER,7.55844149e+02
8,3.80000000e+01,3.00000000e+00,7.20000000e+01,2.00000000e+01,1.50000000e+01,1.80000000e+00,CharacterType.ARCHER,7.40644050e+02
34,7.90000000e+01,1.60000000e+01,3.30000000e+01,1.90000000e+01,1.00000000e+00,1.60000000e+00,CharacterType.ARCHER,7.16312825e+02
41,3.30000000e+01,5.00000000e+00,7.90000000e+01,1.30000000e+01,1.90000000e+01,1.80000000e+00,CharacterType.ARCHER,6.99416857e+02
39,5.00000000e+01,5.10000000e+01,3.80000000e+01,1.00000000e+01,0.00000000e+00,1.90000000e+00,CharacterType.ARCHER,6.82339184e+02
31,4.80000000e+01,5.70000000e+01,3.80000000e+01,1.00000000e+00,5.00000000e+00,1.90000000e+00,CharacterType.ARCHER,6.71083076e+02
3,4.30000000e+01,3.50000000e+01,4.90000000e+01,1.00000000e+01,9.00000000e+00,1.40000000e+00,CharacterType.ARCHER,6.65058078e+02
7,4.10000000e+01,1.40000000e+01,5.60000000e+01,1.60000000e+01,2.20000000e+01,1.60000000e+00,CharacterType.ARCHER,6.58603182e+02
6,7.50000000e+01,3.60000000e+01,2.30000000e+01,4.00000000e+00,1.00000000e+01,1.90000000e+00,CharacterType.ARCHER,6.04096481e+02
37,5.10000000e+01,2.60000000e+01,3.30000000e+01,2.60000000e+01,1.10000000e+01,1.90000000e+00,CharacterType.ARCHER,5.69725883e+02
46,3.30000000e+01,2.00000000e+00,5.80000000e+01,3.10000000e+01,2.40000000e+01,1.50000000e+00,CharacterType.ARCHER,5.45778028e+02
13,4.60000000e+01,3.00000000e+00,4.00000000e+01,4.10000000e+01,1.80000000e+01,1.70000000e+00,CharacterType.ARCHER,5.29305751e+02
42,4.60000000e+01,1.00000000e+01,3.80000000e+01,4.40000000e+01,1.00000000e+01,1.70000000e+00,CharacterType.ARCHER,5.19171257e+02
28,3.60000000e+01,3.00000000e+00,4.70000000e+01,1.90000000e+01,4.30000000e+01,2.00000000e+00,CharacterType.ARCHER,5.07131529e+02
29,4.90000000e+01,4.70000000e+01,2.70000000e+01,3.00000000e+00,2.20000000e+01,2.00000000e+00,CharacterType.ARCHER,4.98936319e+02
48,4.20000000e+01,5.20000000e+01,3.00000000e+01,4.00000000e+00,2.00000000e+01,1.80000000e+00,CharacterType.ARCHER,4.83177704e+02
14,5.60000000e+01,3.50000000e+01,2.30000000e+01,1.90000000e+01,1.50000000e+01,1.90000000e+00,CharacterType.ARCHER,4.81585869e+02
24,2.10000000e+01,4.80000000e+01,7.50000000e+01,1.00000000e+00,2.00000000e+00,2.00000000e+00,CharacterType.ARCHER,4.76549875e+02
11,2.80000000e+01,2.80000000e+01,4.20000000e+01,1.00000000e+01,4.00000000e+01,1.60000000e+00,CharacterType.ARCHER,3.91603470e+02
19,6.60000000e+01,4.20000000e+01,1.40000000e+01,1.60000000e+01,1.00000000e+01,1.50000000e+00,CharacterType.ARCHER,3.81658197e+02
45,3.70000000e+01,1.70000000e+01,3.20000000e+01,4.70000000e+01,1.50000000e+01,1.60000000e+00,CharacterType.ARCHER,3.80712418e+02
20,3.20000000e+01,1.00000000e+01,3.70000000e+01,5.20000000e+01,1.70000000e+01,1.70000000e+00,CharacterType.ARCHER,3.67958220e+02
44,2.40000000e+01,8.00000000e+00,5.00000000e+01,4.20000000e+01,2.40000000e+01,1.50000000e+00,CharacterType.ARCHER,3.66902265e+02
26,2.20000000e+01,1.80000000e+01,4.50000000e+01,4.80000000e+01,1.40000000e+01,1.40000000e+00,CharacterType.ARCHER,3.17546289e+02
25,5.30000000e+01,1.60000000e+01,1.70000000e+01,3.00000000e+00,6.00000000e+01,1.80000000e+00,CharacterType.ARCHER,3.13535796e+02
18,2.20000000e+01,1.30000000e+01,4.00000000e+01,3.60000000e+01,3.60000000e+01,1.90000000e+00,CharacterType.ARCHER,2.98289729e+02
32,3.90000000e+01,2.00000000e+01,2.00000000e+01,3.50000000e+01,3.30000000e+01,1.50000000e+00,CharacterType.ARCHER,2.79324111e+02
15,2.30000000e+01,8.70000000e+01,2.70000000e+01,1.00000000e+00,9.00000000e+00,1.50000000e+00,CharacterType.ARCHER,2.77282532e+02
40,1.10000000e+01,1.70000000e+01,8.00000000e+01,6.00000000e+00,3.50000000e+01,1.80000000e+00,CharacterType.ARCHER,2.60218550e+02
16,4.40000000e+01,1.10000000e+01,1.80000000e+01,7.50000000e+01,0.00000000e+00,1.40000000e+00,CharacterType.ARCHER,2.60084867e+02
36,5.00000000e+01,1.00000000e+01,1.50000000e+01,4.10000000e+01,3.20000000e+01,1.90000000e+00,CharacterType.ARCHER,2.59220754e+02
49,3.50000000e+01,5.90000000e+01,1.50000000e+01,5.00000000e+00,3.40000000e+01,1.40000000e+00,CharacterType.ARCHER,2.58820290e+02
21,1.80000000e+01,1.80000000e+01,3.60000000e+01,5.50000000e+01,2.10000000e+01,1.90000000e+00,CharacterType.ARCHER,2.27772584e+02
38,4.20000000e+01,3.00000000e+01,1.10000000e+01,5.60000000e+01,9.00000000e+00,1.90000000e+00,CharacterType.ARCHER,2.10950284e+02
50,9.00000000e+00,2.70000000e+01,4.70000000e+01,1.60000000e+01,4.90000000e+01,1.60000000e+00,CharacterType.ARCHER,1.51145485e+02
43,5.30000000e+01,1.20000000e+01,8.00000000e+00,6.40000000e+01,1.20000000e+01,1.30000000e+00,CharacterType.ARCHER,1.43053703e+02
10,3.20000000e+01,2.00000000e+00,1.00000000e+01,1.60000000e+01,8.80000000e+01,2.00000000e+00,CharacterType.ARCHER,1.08634703e+02
23,2.20000000e+01,3.10000000e+01,7.00000000e+00,3.70000000e+01,5.10000000e+01,1.80000000e+00,CharacterType.ARCHER,8.81448620e+01
33,2.20000000e+01,1.10000000e+01,8.00000000e+00,3.60000000e+01,7.10000000e+01,2.00000000e+00,CharacterType.ARCHER,7.38447643e+01
17,2.70000000e+01,1.60000000e+01,4.00000000e+00,4.30000000e+01,5.80000000e+01,1.70000000e+00,CharacterType.ARCHER,5.92523068e+01
47,2.00000000e+00,5.00000000e+01,6.90000000e+01,1.30000000e+01,1.50000000e+01,1.60000000e+00,CharacterType.ARCHER,4.89850031e+01

In [31]:
import numpy as np
from selection import boltzmann_selection

# Example usage:

max_generation = 18
generation = 1
k = K                                  # Number of desired selected individuals.
T_0 = 20                                # Initial temperature.
T_offset = 0.5                          # Offset value for temperature exponential function.
reference_generation = max_generation   # Reference generation where 0 < (T_0 - T_offset) = 0.015 = deltaT is desired.
deltaT = 0.015                          # 0 < (T_0 - T_offset) = deltaT at reference generation.
m = - (np.log(deltaT) - np.log(T_0 - T_offset)) / reference_generation

new_boltzmann_selection = boltzmann_selection(poblacion_inicial,k,generation,T_0,T_offset,m)

new_boltzmann_selection

sum: 0.9999999999999999
    strength  agility  expertise  resistance  life         height  \
93        72        7         60           8     3 1.80000000e+00
30        58        4         62          11    15 1.80000000e+00
6         74        7         48          11    10 1.40000000e+00
46        63       30         49           2     6 2.00000000e+00
28        50        1         63          13    23 2.00000000e+00
..       ...      ...        ...         ...   ...            ...
86         5      103          1          28    13 1.60000000e+00
78         6       53          1          32    58 1.70000000e+00
22         1       81         23           6    39 1.60000000e+00
96         3       70          3          26    48 1.50000000e+00
75         2       55          9          60    24 1.40000000e+00

                    type    performance  performance_relative  \
93  CharacterType.ARCHER 9.99980061e-01        9.99980061e-01
30  CharacterType.ARCHER 1.72769885e-05        1.72769885e-05
6   CharacterType.ARCHER 1.98858686e-06        1.98858686e-06
46  CharacterType.ARCHER 6.68032742e-07        6.68032742e-07
28  CharacterType.ARCHER 5.68503109e-09        5.68503109e-09
..                   ...            ...                   ...
86  CharacterType.ARCHER 2.77646070e-35        2.77646070e-35
78  CharacterType.ARCHER 2.23449595e-35        2.23449595e-35
22  CharacterType.ARCHER 1.83383258e-35        1.83383258e-35
96  CharacterType.ARCHER 1.56853349e-35        1.56853349e-35
75  CharacterType.ARCHER 1.47572072e-35        1.47572072e-35

    performance_accumulated
93           9.99980061e-01
30           9.99997338e-01
6            9.99999326e-01
46           9.99999994e-01
28           1.00000000e+00
..                      ...
86           1.00000000e+00
78           1.00000000e+00
22           1.00000000e+00
96           1.00000000e+00
75           1.00000000e+00

[100 rows x 10 columns]

,strength,agility,expertise,resistance,life,height,type,performance,performance_relative,performance_accumulated
0,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
1,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
2,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
3,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
4,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
5,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
6,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
7,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
8,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
9,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
10,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
11,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
12,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
13,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
14,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
15,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
16,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
17,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
18,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
19,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
20,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
21,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
22,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
23,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
24,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
25,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
26,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
27,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
28,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
29,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
30,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
31,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
32,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
33,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
34,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
35,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
36,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
37,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
38,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
39,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
40,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
41,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
42,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
43,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
44,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
45,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
46,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
47,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
48,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01
49,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,9.99980061e-01,9.99980061e-01,9.99980061e-01

In [35]:
from selection import deterministic_tournament_selection 

individualsT = deterministic_tournament_selection(poblacion_inicial, 10, k)
individualsT

c:\Users\dpenaloza\Downloads\SIA\sia-tp2\src\selection.py:195: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  individuals = pd.concat([individuals, winner])

,strength,agility,expertise,resistance,life,height,type,performance
0,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02
1,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
2,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
3,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02
4,35,11,46,48,10,1.80000000e+00,CharacterType.ARCHER,4.94345101e+02
5,18,23,103,5,1,1.80000000e+00,CharacterType.ARCHER,4.71404818e+02
6,30,2,81,28,9,1.60000000e+00,CharacterType.ARCHER,6.22507325e+02
7,36,6,40,30,38,1.50000000e+00,CharacterType.ARCHER,4.41506879e+02
8,49,26,27,42,6,1.90000000e+00,CharacterType.ARCHER,4.66291816e+02
9,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02
10,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
11,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
12,30,14,52,40,14,1.70000000e+00,CharacterType.ARCHER,4.66867790e+02
13,57,6,36,31,20,2.00000000e+00,CharacterType.ARCHER,5.97784812e+02
14,52,30,29,18,21,1.90000000e+00,CharacterType.ARCHER,5.31970240e+02
15,49,26,27,42,6,1.90000000e+00,CharacterType.ARCHER,4.66291816e+02
16,50,5,36,45,14,1.70000000e+00,CharacterType.ARCHER,5.20935341e+02
17,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02
18,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
19,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
20,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03
21,36,6,40,30,38,1.50000000e+00,CharacterType.ARCHER,4.41506879e+02
22,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02
23,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02
24,58,40,28,4,20,1.30000000e+00,CharacterType.ARCHER,5.17367206e+02
25,25,3,50,29,43,1.50000000e+00,CharacterType.ARCHER,3.79967906e+02
26,22,5,32,19,72,1.50000000e+00,CharacterType.ARCHER,2.34046287e+02
27,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02
28,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02
29,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
30,58,4,62,11,15,1.80000000e+00,CharacterType.ARCHER,9.54910635e+02
31,24,38,48,37,3,1.90000000e+00,CharacterType.ARCHER,4.00219353e+02
32,22,38,68,12,10,1.90000000e+00,CharacterType.ARCHER,4.75532961e+02
33,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02
34,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02
35,50,5,36,45,14,1.70000000e+00,CharacterType.ARCHER,5.20935341e+02
36,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
37,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02
38,100,11,23,5,11,1.80000000e+00,CharacterType.ARCHER,6.07740348e+02
39,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02
40,49,58,38,3,2,1.50000000e+00,CharacterType.ARCHER,6.55553400e+02
41,18,12,68,8,44,1.40000000e+00,CharacterType.ARCHER,3.64744058e+02
42,74,7,48,11,10,1.40000000e+00,CharacterType.ARCHER,9.25523325e+02
43,30,2,81,28,9,1.60000000e+00,CharacterType.ARCHER,6.22507325e+02
44,18,12,68,8,44,1.40000000e+00,CharacterType.ARCHER,3.64744058e+02
45,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02
46,100,11,23,5,11,1.80000000e+00,CharacterType.ARCHER,6.07740348e+02
47,17,17,48,44,24,1.60000000e+00,CharacterType.ARCHER,2.60246922e+02
48,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02
49,72,7,60,8,3,1.80000000e+00,CharacterType.ARCHER,1.10397257e+03
50,51,20,40,7,32,1.80000000e+00,CharacterType.ARCHER,6.39232797e+02
51,57,6,36,31,20,2.00000000e+00,CharacterType.ARCHER,5.97784812e+02

In [34]:
from selection import stochastic_tournament_selection
#ejemplo
individualsTd = stochastic_tournament_selection(poblacion_inicial, k)
individualsTd

,strength,agility,expertise,resistance,life,height,type,performance
32,21,10,68,39,12,1.60000000e+00,CharacterType.ARCHER,4.02250578e+02
8,20,34,8,33,55,2.00000000e+00,CharacterType.ARCHER,8.99458827e+01
46,63,30,49,2,6,2.00000000e+00,CharacterType.ARCHER,9.10695551e+02
44,21,41,25,9,54,1.30000000e+00,CharacterType.ARCHER,1.99075563e+02
21,35,48,5,52,10,1.30000000e+00,CharacterType.ARCHER,1.23104341e+02
67,33,14,6,71,26,2.00000000e+00,CharacterType.ARCHER,8.82376029e+01
29,19,11,49,70,1,1.60000000e+00,CharacterType.ARCHER,2.80052130e+02
70,23,13,12,4,98,1.80000000e+00,CharacterType.ARCHER,1.09332001e+02
78,6,53,1,32,58,1.70000000e+00,CharacterType.ARCHER,1.94388480e+01
32,21,10,68,39,12,1.60000000e+00,CharacterType.ARCHER,4.02250578e+02
13,85,2,7,33,23,1.90000000e+00,CharacterType.ARCHER,1.70737942e+02
59,22,33,6,86,3,1.80000000e+00,CharacterType.ARCHER,8.00423555e+01
11,31,86,17,6,10,1.90000000e+00,CharacterType.ARCHER,2.86940505e+02
2,3,70,63,10,4,2.00000000e+00,CharacterType.ARCHER,6.53926876e+01
57,16,19,38,46,31,1.60000000e+00,CharacterType.ARCHER,2.06164698e+02
56,9,31,10,22,78,1.90000000e+00,CharacterType.ARCHER,4.92514595e+01
24,64,42,6,20,18,1.50000000e+00,CharacterType.ARCHER,2.29416805e+02
11,31,86,17,6,10,1.90000000e+00,CharacterType.ARCHER,2.86940505e+02
43,31,31,16,51,21,1.80000000e+00,CharacterType.ARCHER,2.07179098e+02
7,31,52,8,20,39,1.80000000e+00,CharacterType.ARCHER,1.58522909e+02
8,20,34,8,33,55,2.00000000e+00,CharacterType.ARCHER,8.99458827e+01
69,63,12,22,32,21,1.80000000e+00,CharacterType.ARCHER,4.33138778e+02
56,9,31,10,22,78,1.90000000e+00,CharacterType.ARCHER,4.92514595e+01
62,35,38,8,54,15,1.40000000e+00,CharacterType.ARCHER,1.52660563e+02
39,12,46,29,27,36,1.40000000e+00,CharacterType.ARCHER,1.42542782e+02
71,49,5,6,10,80,1.60000000e+00,CharacterType.ARCHER,1.01284414e+02
28,50,1,63,13,23,2.00000000e+00,CharacterType.ARCHER,8.45904711e+02
70,23,13,12,4,98,1.80000000e+00,CharacterType.ARCHER,1.09332001e+02
63,36,6,40,30,38,1.50000000e+00,CharacterType.ARCHER,4.41506879e+02
58,39,12,19,45,35,1.50000000e+00,CharacterType.ARCHER,2.52778181e+02
84,24,38,48,37,3,1.90000000e+00,CharacterType.ARCHER,4.00219353e+02
22,1,81,23,6,39,1.60000000e+00,CharacterType.ARCHER,1.67527764e+01
62,35,38,8,54,15,1.40000000e+00,CharacterType.ARCHER,1.52660563e+02
78,6,53,1,32,58,1.70000000e+00,CharacterType.ARCHER,1.94388480e+01
90,25,19,4,48,54,1.90000000e+00,CharacterType.ARCHER,6.11456580e+01
5,11,49,77,10,3,2.00000000e+00,CharacterType.ARCHER,2.57706361e+02
9,32,23,13,27,55,1.90000000e+00,CharacterType.ARCHER,1.77151314e+02
9,32,23,13,27,55,1.90000000e+00,CharacterType.ARCHER,1.77151314e+02
4,36,18,34,2,60,1.40000000e+00,CharacterType.ARCHER,4.06246032e+02
77,44,51,7,5,43,1.40000000e+00,CharacterType.ARCHER,1.98362662e+02
51,28,20,5,77,20,1.60000000e+00,CharacterType.ARCHER,7.34580775e+01
65,5,14,34,64,33,1.40000000e+00,CharacterType.ARCHER,6.47197799e+01
69,63,12,22,32,21,1.80000000e+00,CharacterType.ARCHER,4.33138778e+02
71,49,5,6,10,80,1.60000000e+00,CharacterType.ARCHER,1.01284414e+02
7,31,52,8,20,39,1.80000000e+00,CharacterType.ARCHER,1.58522909e+02
34,16,16,31,76,11,1.50000000e+00,CharacterType.ARCHER,1.69116847e+02
23,94,1,12,28,15,1.60000000e+00,CharacterType.ARCHER,2.82402276e+02
18,49,26,27,42,6,1.90000000e+00,CharacterType.ARCHER,4.66291816e+02
12,57,6,36,31,20,2.00000000e+00,CharacterType.ARCHER,5.97784812e+02
95,8,8,49,32,53,1.30000000e+00,CharacterType.ARCHER,1.32377675e+02