In [1]:
#from population import generate_init_population

In [2]:
#from stats import random_stats

In [8]:
#from character import Character

In [1]:
import pandas as pd
pd.options.display.float_format = '{:.8e}'.format

from population import generate_init_population
from character import CharacterType
#from src.stats import random_stats

N = 100
K = 50
maxStatsValue = 150
type = CharacterType.ARCHER

#equipment_data = random_stats(N, maxStatsValue)
poblacion_inicial = generate_init_population(N,maxStatsValue,type)

poblacion_inicial

Personaje creado: <character.Character object at 0x00000242FF4E8A40>
Personaje creado: <character.Character object at 0x00000242FE99EAB0>
Personaje creado: <character.Character object at 0x00000242FE8951F0>
Personaje creado: <character.Character object at 0x00000242FF3E8050>
Personaje creado: <character.Character object at 0x00000242F8166480>
Personaje creado: <character.Character object at 0x00000242FE848680>
Personaje creado: <character.Character object at 0x00000242F8165760>
Personaje creado: <character.Character object at 0x00000242FF672000>
Personaje creado: <character.Character object at 0x00000242FF671FA0>
Personaje creado: <character.Character object at 0x00000242FF6720F0>
Personaje creado: <character.Character object at 0x00000242FF672120>
Personaje creado: <character.Character object at 0x00000242FF672150>
Personaje creado: <character.Character object at 0x00000242FF672180>
Personaje creado: <character.Character object at 0x00000242FF6721B0>
Personaje creado: <character.Character object at 0x00000242FF6721E0>
Personaje creado: <character.Character object at 0x00000242FF672210>
Personaje creado: <character.Character object at 0x00000242FF672240>
Personaje creado: <character.Character object at 0x00000242FF672270>
Personaje creado: <character.Character object at 0x00000242FF6722A0>
Personaje creado: <character.Character object at 0x00000242FF6722D0>
Personaje creado: <character.Character object at 0x00000242FF672300>
Personaje creado: <character.Character object at 0x00000242FF672330>
Personaje creado: <character.Character object at 0x00000242FF672360>
Personaje creado: <character.Character object at 0x00000242FF672390>
Personaje creado: <character.Character object at 0x00000242FF6723C0>
Personaje creado: <character.Character object at 0x00000242FF6723F0>
Personaje creado: <character.Character object at 0x00000242FF672420>
Personaje creado: <character.Character object at 0x00000242FF6724B0>
Personaje creado: <character.Character object at 0x00000242FF672510>
Personaje creado: <character.Character object at 0x00000242FF672450>
Personaje creado: <character.Character object at 0x00000242FF672540>
Personaje creado: <character.Character object at 0x00000242FF672570>
Personaje creado: <character.Character object at 0x00000242FF6725A0>
Personaje creado: <character.Character object at 0x00000242FF6725D0>
Personaje creado: <character.Character object at 0x00000242FF672600>
Personaje creado: <character.Character object at 0x00000242FF672630>
Personaje creado: <character.Character object at 0x00000242FF672660>
Personaje creado: <character.Character object at 0x00000242FF672690>
Personaje creado: <character.Character object at 0x00000242FF6726C0>
Personaje creado: <character.Character object at 0x00000242FF6726F0>
Personaje creado: <character.Character object at 0x00000242FF672720>
Personaje creado: <character.Character object at 0x00000242FF672750>
Personaje creado: <character.Character object at 0x00000242FF672780>
Personaje creado: <character.Character object at 0x00000242FF6727B0>
Personaje creado: <character.Character object at 0x00000242FF6727E0>
Personaje creado: <character.Character object at 0x00000242FF672810>
Personaje creado: <character.Character object at 0x00000242FF672840>
Personaje creado: <character.Character object at 0x00000242FF672870>
Personaje creado: <character.Character object at 0x00000242FF6728A0>
Personaje creado: <character.Character object at 0x00000242FF6728D0>
Personaje creado: <character.Character object at 0x00000242FF672900>
Personaje creado: <character.Character object at 0x00000242FF672930>
Personaje creado: <character.Character object at 0x00000242FF672960>
Personaje creado: <character.Character object at 0x00000242FF672990>
Personaje creado: <character.Character object at 0x00000242FF6729C0>
Personaje creado: <character.Character object at 0x00000242FF6729F0>
Personaje creado: <character.Character object at 0x00000242FF672A20>
Personaje creado: <character.Character object at 0x00000242FF672A50>
Personaje creado: <character.Character object at 0x00000242FF672A80>
Personaje creado: <character.Character object at 0x00000242FF672AB0>
Personaje creado: <character.Character object at 0x00000242FF672AE0>
Personaje creado: <character.Character object at 0x00000242FF672B10>
Personaje creado: <character.Character object at 0x00000242FF672B40>
Personaje creado: <character.Character object at 0x00000242FF672B70>
Personaje creado: <character.Character object at 0x00000242FF672BA0>
Personaje creado: <character.Character object at 0x00000242FF672BD0>
Personaje creado: <character.Character object at 0x00000242FF672C00>
Personaje creado: <character.Character object at 0x00000242FF672C30>
Personaje creado: <character.Character object at 0x00000242FF672C60>
Personaje creado: <character.Character object at 0x00000242FF672C90>
Personaje creado: <character.Character object at 0x00000242FF672CC0>
Personaje creado: <character.Character object at 0x00000242FF672CF0>
Personaje creado: <character.Character object at 0x00000242FF672D20>
Personaje creado: <character.Character object at 0x00000242FF672D50>
Personaje creado: <character.Character object at 0x00000242FF672D80>
Personaje creado: <character.Character object at 0x00000242FF672DB0>
Personaje creado: <character.Character object at 0x00000242FF672DE0>
Personaje creado: <character.Character object at 0x00000242FF672E10>
Personaje creado: <character.Character object at 0x00000242FF672E40>
Personaje creado: <character.Character object at 0x00000242FF672E70>
Personaje creado: <character.Character object at 0x00000242FF672EA0>
Personaje creado: <character.Character object at 0x00000242FF672ED0>
Personaje creado: <character.Character object at 0x00000242FF672F00>
Personaje creado: <character.Character object at 0x00000242FF672F30>
Personaje creado: <character.Character object at 0x00000242FF672F60>
Personaje creado: <character.Character object at 0x00000242FF672F90>
Personaje creado: <character.Character object at 0x00000242FF672FC0>
Personaje creado: <character.Character object at 0x00000242FF672FF0>
Personaje creado: <character.Character object at 0x00000242FF673020>
Personaje creado: <character.Character object at 0x00000242FF673050>
Personaje creado: <character.Character object at 0x00000242FF673080>
Personaje creado: <character.Character object at 0x00000242FF6730B0>
Personaje creado: <character.Character object at 0x00000242FF6730E0>
Personaje creado: <character.Character object at 0x00000242FF673110>
Personaje creado: <character.Character object at 0x00000242FF673140>
Personaje creado: <character.Character object at 0x00000242FF673170>
Personaje creado: <character.Character object at 0x00000242FF6731A0>
Personaje creado: <character.Character object at 0x00000242FF6731D0>
Personaje creado: <character.Character object at 0x00000242FF673200>
Personaje creado: <character.Character object at 0x00000242FF673230>
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero
Tipo de personaje: CharacterType.ARCHER
arquero

,strength,agility,expertise,resistance,life,height,characterType,performance
6,52,6,80,5,7,2.00000000e+00,CharacterType.ARCHER,1.04603987e+03
3,54,3,72,2,19,1.50000000e+00,CharacterType.ARCHER,9.90437577e+02
71,59,25,50,14,2,1.50000000e+00,CharacterType.ARCHER,8.55097356e+02
32,56,6,39,7,42,1.70000000e+00,CharacterType.ARCHER,6.23384999e+02
91,72,18,29,21,10,1.70000000e+00,CharacterType.ARCHER,6.10857238e+02
...,...,...,...,...,...,...,...,...
18,3,58,6,44,39,1.80000000e+00,CharacterType.ARCHER,1.71424523e+01
35,2,27,11,46,64,1.70000000e+00,CharacterType.ARCHER,1.67165285e+01
54,4,11,6,38,91,1.50000000e+00,CharacterType.ARCHER,1.55563482e+01
62,7,7,4,99,33,1.80000000e+00,CharacterType.ARCHER,1.48239163e+01
28,1,39,5,55,50,1.90000000e+00,CharacterType.ARCHER,6.70353075e+00

In [1]:
from population import generate_init_population
from character import CharacterType

tipo1 = CharacterType.DEFENDER
generation_0 = generate_init_population(3,150,tipo1)
generation_0

,strength,agility,expertise,resistance,life,height,characterType,performance
0,14,6,34,43,53,1.6,CharacterType.DEFENDER,136.714826
2,3,40,21,56,30,1.6,CharacterType.DEFENDER,56.129088
1,20,47,10,70,3,1.8,CharacterType.DEFENDER,15.475458

In [7]:
#Añado las columnas de desempeño relativo y acumulado
from selection import add_relative_accumulate
poblacion_rel_acu = add_relative_accumulate(poblacion_inicial)
poblacion_rel_acu

sum: 26943.79800545565

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
14,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02,3.60449754e-02,3.60449754e-02
29,56,4,59,24,7,1.40000000e+00,CharacterType.ARCHER,8.75402227e+02,3.24899343e-02,6.85349097e-02
72,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02,3.01986702e-02,9.87335799e-02
5,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02,2.59381314e-02,1.24671711e-01
51,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02,2.55052521e-02,1.50176963e-01
...,...,...,...,...,...,...,...,...,...,...
42,4,11,13,65,57,1.40000000e+00,CharacterType.ARCHER,2.63150517e+01,9.76664526e-04,9.98022746e-01
67,3,22,12,87,26,1.30000000e+00,CharacterType.ARCHER,1.93739155e+01,7.19049167e-04,9.98741795e-01
12,1,45,26,40,38,2.00000000e+00,CharacterType.ARCHER,1.74292759e+01,6.46875244e-04,9.99388670e-01
64,1,88,12,25,24,1.60000000e+00,CharacterType.ARCHER,1.01070541e+01,3.75116161e-04,9.99763787e-01
79,1,80,6,53,10,1.50000000e+00,CharacterType.ARCHER,6.36448745e+00,2.36213449e-04,1.00000000e+00

#### Seleccion de k indiduos
A*(método1) + (1-A)*(método2)

In [8]:
import numpy as np
#Dado un K
#Si quiero un m1_perc de la selección con metodo1
#K = 120
m1_perc = 0.3
N1 = int(np.round(K * m1_perc))
N2 = K - N1
#N1

In [9]:
from selection import elitist_selection
nueva_poblacion_e = elitist_selection(poblacion_rel_acu,N1)
#nueva_poblacion_e

In [10]:
from selection import roulette_wheel_selection
nueva_poblacion_rul = roulette_wheel_selection(poblacion_rel_acu, N2)
#nueva_poblacion_rul

In [11]:
from selection import universal_selection
    
nueva_poblacion_uni = universal_selection(poblacion_rel_acu, N2)
#nueva_poblacion_uni

In [12]:
from selection import rank_based_selection

nueva_poblacion_rank = rank_based_selection(poblacion_inicial, N2)
#nueva_poblacion_rank

sum: 49.5

In [13]:
import pandas as pd
selection_total = pd.concat([nueva_poblacion_e,nueva_poblacion_rul])
selection_total

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02,3.60449754e-02,3.60449754e-02
1,56,4,59,24,7,1.40000000e+00,CharacterType.ARCHER,8.75402227e+02,3.24899343e-02,6.85349097e-02
2,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02,3.01986702e-02,9.87335799e-02
3,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02,2.59381314e-02,1.24671711e-01
4,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02,2.55052521e-02,1.50176963e-01
5,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02,2.53274467e-02,1.75504410e-01
6,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02,2.48779977e-02,2.00382408e-01
7,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02,2.46990158e-02,2.25081424e-01
8,29,9,88,16,8,2.00000000e+00,CharacterType.ARCHER,6.62934860e+02,2.46043583e-02,2.49685782e-01
9,34,48,62,3,3,1.40000000e+00,CharacterType.ARCHER,6.57046077e+02,2.43858003e-02,2.74071582e-01
10,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02,2.25761685e-02,2.96647751e-01
11,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02,2.21376735e-02,3.18785424e-01
12,49,39,36,6,20,1.60000000e+00,CharacterType.ARCHER,5.87874034e+02,2.18185288e-02,3.40603953e-01
13,69,2,31,19,29,1.40000000e+00,CharacterType.ARCHER,5.87721976e+02,2.18128853e-02,3.62416838e-01
14,97,6,23,12,12,1.80000000e+00,CharacterType.ARCHER,5.77513099e+02,2.14339901e-02,3.83850828e-01
0,5,18,45,81,1,1.50000000e+00,CharacterType.ARCHER,7.26736078e+01,2.69722954e-03,9.68195902e-01
1,34,48,62,3,3,1.40000000e+00,CharacterType.ARCHER,6.57046077e+02,2.43858003e-02,2.74071582e-01
2,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02,2.46990158e-02,2.25081424e-01
3,9,6,88,23,24,2.00000000e+00,CharacterType.ARCHER,2.18855971e+02,8.12268453e-03,7.93768734e-01
4,71,28,22,20,9,1.40000000e+00,CharacterType.ARCHER,5.13819092e+02,1.90700321e-02,4.22623086e-01
5,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02,2.21376735e-02,3.18785424e-01
6,35,5,25,1,84,1.90000000e+00,CharacterType.ARCHER,2.93314582e+02,1.08861632e-02,7.26198295e-01
7,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02,2.59381314e-02,1.24671711e-01
8,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02,2.21376735e-02,3.18785424e-01
9,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02,2.48779977e-02,2.00382408e-01
10,11,4,102,16,17,2.00000000e+00,CharacterType.ARCHER,2.83689287e+02,1.05289272e-02,7.47358355e-01
11,46,57,15,25,7,1.80000000e+00,CharacterType.ARCHER,3.29800910e+02,1.22403274e-02,6.57154540e-01
12,68,35,19,9,19,1.70000000e+00,CharacterType.ARCHER,4.58957831e+02,1.70338952e-02,4.56762432e-01
13,8,15,60,8,59,1.30000000e+00,CharacterType.ARCHER,1.58761626e+02,5.89232543e-03,8.76184703e-01
14,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02,2.55052521e-02,1.50176963e-01
15,56,4,59,24,7,1.40000000e+00,CharacterType.ARCHER,8.75402227e+02,3.24899343e-02,6.85349097e-02
16,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02,2.25761685e-02,2.96647751e-01
17,48,46,28,21,7,1.30000000e+00,CharacterType.ARCHER,4.50118195e+02,1.67058183e-02,4.73468250e-01
18,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02,2.55052521e-02,1.50176963e-01
19,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02,2.48779977e-02,2.00382408e-01
20,26,28,49,26,21,1.90000000e+00,CharacterType.ARCHER,4.30362993e+02,1.59726180e-02,4.89440868e-01
21,45,3,41,43,18,1.70000000e+00,CharacterType.ARCHER,5.30852794e+02,1.97022259e-02,4.03553054e-01
22,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02,2.46990158e-02,2.25081424e-01
23,19,60,25,28,18,1.50000000e+00,CharacterType.ARCHER,2.04608900e+02,7.59391456e-03,8.09465636e-01
24,16,65,2,4,63,1.70000000e+00,CharacterType.ARCHER,5.88882837e+01,2.18559699e-03,9.82642137e-01
25,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02,2.46990158e-02,2.25081424e-01
26,34,3,29,2,82,1.70000000e+00,CharacterType.ARCHER,3.10724973e+02,1.15323375e-02,7.03790177e-01
27,25,12,46,36,31,1.70000000e+00,CharacterType.ARCHER,3.58766033e+02,1.33153475e-02,6.18910103e-01
28,27,31,11,8,73,1.30000000e+00,CharacterType.ARCHER,1.29988035e+02,4.82441395e-03,9.13101246e-01
29,55,39,16,9,31,1.40000000e+00,CharacterType.ARCHER,3.56848136e+02,1.32441661e-02,6.32154269e-01
30,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02,2.25761685e-02,2.96647751e-01
31,23,31,54,37,5,1.40000000e+00,CharacterType.ARCHER,3.94857150e+02,1.46548438e-02,5.51113892e-01
32,38,33,21,24,34,2.00000000e+00,CharacterType.ARCHER,3.10445209e+02,1.15219543e-02,7.15312131e-01
33,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02,2.46990158e-02,2.25081424e-01
34,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02,2.53274467e-02,1.75504410e-01

In [14]:
from genes import  encode_genes

cromosomas = encode_genes(selection_total)
#cromosomas

In [15]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas)
#cromosomas_decoded2

In [16]:
from crossover import normalize_chromosome

cromosomas_norm = normalize_chromosome(cromosomas)
cromosomas_norm

    strength   agility expertise resistance      life height
1   00111111  00000010  00111001   00010100  00001000    110
2   00111000  00000100  00111011   00011000  00000111    001
3   00110101  00001011  00110110   00001111  00010001    101
4   00011111  00011000  01001110   00001000  00001001    110
5   00111111  00001000  00100111   00001001  00011111    100
6   00110101  00110001  00100110   00000110  00000100    001
7   00101101  00010110  00110001   00001010  00011000    010
8   00101010  00010000  00110011   00010000  00011001    110
9   00011101  00001001  01011000   00010000  00001000    111
10  00100010  00110000  00111110   00000011  00000011    001
11  00101000  00100100  00110000   00010010  00001000    100
12  00110001  00011110  00100101   00010000  00010010    111
13  00110001  00100111  00100100   00000110  00010100    011
14  01000101  00000010  00011111   00010011  00011101    001
15  01100001  00000110  00010111   00001100  00001100    101
16  00000101  00010010  00101101   01010001  00000001    010
17  00100010  00110000  00111110   00000011  00000011    001
18  00101010  00010000  00110011   00010000  00011001    110
19  00001001  00000110  01011000   00010111  00011000    111
20  01000111  00011100  00010110   00010100  00001001    001
21  00110001  00011110  00100101   00010000  00010010    111
22  00100011  00000101  00011001   00000001  01010100    110
23  00011111  00011000  01001110   00001000  00001001    110
24  00110001  00011110  00100101   00010000  00010010    111
25  00101101  00010110  00110001   00001010  00011000    010
26  00001011  00000100  01100110   00010000  00010001    111
27  00101110  00111001  00001111   00011001  00000111    101
28  01000100  00100011  00010011   00001001  00010011    100
29  00001000  00001111  00111100   00001000  00111011    000
30  00111111  00001000  00100111   00001001  00011111    100
31  00111000  00000100  00111011   00011000  00000111    001
32  00101000  00100100  00110000   00010010  00001000    100
33  00110000  00101110  00011100   00010101  00000111    000
34  00111111  00001000  00100111   00001001  00011111    100
35  00101101  00010110  00110001   00001010  00011000    010
36  00011010  00011100  00110001   00011010  00010101    110
37  00101101  00000011  00101001   00101011  00010010    100
38  00101010  00010000  00110011   00010000  00011001    110
39  00010011  00111100  00011001   00011100  00010010    010
40  00010000  01000001  00000010   00000100  00111111    100
41  00101010  00010000  00110011   00010000  00011001    110
42  00100010  00000011  00011101   00000010  01010010    100
43  00011001  00001100  00101110   00100100  00011111    100
44  00011011  00011111  00001011   00001000  01001001    000
45  00110111  00100111  00010000   00001001  00011111    001
46  00101000  00100100  00110000   00010010  00001000    100
47  00010111  00011111  00110110   00100101  00000101    001
48  00100110  00100001  00010101   00011000  00100010    111
49  00101010  00010000  00110011   00010000  00011001    110
50  00110101  00110001  00100110   00000110  00000100    001

In [17]:
from crossover import single_point_crossover, normalize_chromosome

new_individuals = single_point_crossover(cromosomas)
cromosomas_ok1 = normalize_chromosome(new_individuals)

cromosomas_ok1

    strength   agility expertise resistance      life height
1   00111011  00000011  00111010   00010011  00001000    001
2   00111011  00000010  00111001   00011000  00000110    110
3   00110010  00010111  00110011   00000111  00010000    100
4   00100000  00001011  01010001   00001111  00001001    111
5   00111101  00010001  00100110   00000110  00011100    101
6   00110111  00101000  00100111   00001001  00000111    000
7   00101101  00010111  00110110   00000000  00011010    110
8   00101010  00001111  00101101   00011000  00010110    010
9   00000001  00101011  01010100   00010001  00000010    001
10  01000100  00001010  00111110   00000000  00001000    111
11  00100010  00110100  00101001   00001101  00001000    111
12  00111011  00000100  00101100   00010110  00010011    100
13  00100011  00100000  00101100   00010010  00010011    001
14  01010101  00000111  00010101   00000110  00011101    011
15  01011101  00010000  00011010   00001100  00000000    100
16  00000001  00000110  00101010   01010110  00001101    011
17  00110001  00010111  01001001   00000010  00000001    110
18  00100000  00100100  00101111   00001101  00010100    001
19  00000110  00011001  01001101   00010010  00010110    001
20  01010001  00000110  00011010   00011001  00001000    111
21  01000011  00000110  00110000   00000001  00011010    110
22  00011010  00011000  00010100   00001100  01000010    111
23  00101110  00011100  01000001   00000111  00000001    111
24  00100000  00011001  00110000   00010000  00011010    110
25  00101110  00010100  00100111   00010000  00011010    011
26  00001010  00000101  01101100   00001001  00001111    110
27  00100110  00111110  00010100   00001001  00010100    100
28  01001010  00011111  00001110   00010111  00000110    101
29  00101111  00000110  00101101   00000110  00101100    000
30  00001100  00010110  00111001   00001100  00101110    100
31  01000000  00000100  00110111   00010100  00000100    000
32  00100011  00011111  00110100   00010101  00001001    101
33  00110000  00100011  00010110   00010011  00010111    000
34  01000011  00001011  00110101   00000111  00001001    100
35  00011110  00010111  00111010   00001011  00011001    110
36  00100110  00011001  00101010   00010110  00010100    010
37  00110011  00000000  00101001   00100101  00010011    110
38  00100101  00010000  00110001   00010111  00010110    100
39  00001110  00110101  00010110   00000011  00110111    010
40  00010101  01001001  00000001   00100000  00010100    100
41  00111101  00000100  00101010   00000010  00100110    100
42  00011001  00001100  00100110   00001100  00111101    110
43  00011011  00001111  00101011   00101000  00011001    100
44  00011001  00011100  00001110   00000100  01001111    000
45  00111011  00101001  00010010   00010100  00001001    100
46  00100101  00100010  00101010   00000111  00011011    001
47  00100001  00101110  00011111   00100100  00000011    001
48  00011101  00011000  00101000   00011011  00011011    111
49  00100101  00110001  00110110   00000110  00000100    001
50  00111010  00010000  00100011   00010000  00011001    110

In [18]:
#from genes import decode_genes
#cromosomas_decoded = decode_genes(new_individuals)
#cromosomas_decoded

In [19]:
from crossover import two_point_crossover, normalize_chromosome

new_individuals2 = two_point_crossover(cromosomas)
cromosomas_ok2 = normalize_chromosome(new_individuals2)

cromosomas_ok2

    strength   agility expertise resistance      life height
1   01000001  00000000  00111011   00010100  00000100    000
2   00110101  00000101  00111000   00010111  00001010    111
3   00101001  00010101  00111101   00001011  00001101    111
4   00101010  00001010  01001001   00001010  00001100    100
5   01010000  00001010  00110001   00000001  00001000    100
6   00101011  00101000  00011111   00001011  00010111    001
7   00101011  00010001  00110001   00010001  00010111    010
8   00101011  00010100  00110011   00001000  00011010    110
9   00010100  00100010  01010100   00001011  00000000    101
10  00111011  00001101  00110100   00000101  00010011    011
11  00110011  00100110  00100010   00010001  00001000    100
12  00100110  00011100  00110001   00010000  00010000    111
13  01000000  00011011  00011110   00000100  00010110    001
14  00110001  00001000  00100110   00011001  00011100    011
15  00001010  00101100  00111110   00001000  00011000    101
16  01000000  00000001  00011000   00111011  00000000    010
17  00101010  00110000  00111010   00000001  00000001    001
18  00100010  00010000  00110111   00010010  00011011    110
19  00110101  00000100  01000101   00010000  00000101    101
20  00001010  00101011  00011001   00011111  00100111    011
21  00101001  00011000  00010001   00000000  01000010    111
22  00101010  00000110  00110101   00010101  00011001    110
23  00110001  00011110  00101110   00011000  00000001    110
24  00011111  00011000  01000101   00000000  00011010    111
25  00110100  00000100  00111101   00000010  00011101    110
26  00001011  00010010  01010101   00010100  00001110    011
27  01000101  00100010  00001110   00011000  00000110    101
28  00101100  00111001  00010011   00001001  00010011    100
29  00110000  00001100  00100011   00000110  00101111    000
30  00001110  00001010  01001000   00001011  00101000    100
31  00101110  00000100  00111011   00011110  00001000    001
32  00110000  00011111  00110000   00001101  00000110    100
33  00110001  00101111  00011100   00010001  00000111    000
34  00111101  00000111  00100101   00001100  00011110    100
35  00001101  00011110  00110100   00011011  00011001    110
36  00110110  00010100  00101101   00001001  00010011    010
37  00100010  00001110  00101011   00100101  00010011    100
38  00111100  00000000  00110010   00001110  00011000    110
39  00010100  00101111  00000011   00001100  01000010    000
40  00001111  01001011  00010110   00010010  00010001    110
41  00111001  00000000  01000101   00000000  00010111    100
42  00011010  00001111  00010110   00001110  01000111    110
43  00010011  00001001  00100011   00011100  00111001    100
44  00100101  00101011  00001111   00001011  00101011    000
45  00110100  00100101  00101101   00000000  00001110    101
46  00101010  00100110  00010000   00011011  00011001    000
47  00110001  00000000  00010011   00101111  00011111    011
48  00000110  01000110  00111011   00001000  00000100    101
49  00100111  00101101  00110000   00001111  00000000    110
50  00110111  00010001  00101000   00000110  00011101    001

In [20]:
from crossover import uniform_crossover
# Ejemplo de uso

individuals_df = pd.DataFrame(cromosomas)
offspring_df = uniform_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   00111111  00000010  00111001   00011000  00001000    110
1   00011111  00011000  01001110   00001111  00001001    101
2   00110101  00110001  00100111   00000110  00000100    100
3   00101101  00010000  00110001   00001010  00011001    010
4   00011101  00001001  01011000   00010000  00000011    111
5   00110001  00100100  00100101   00010010  00001000    111
6   00110001  00100111  00100100   00010011  00010100    001
7   00000101  00000110  00010111   00001100  00000001    101
8   00101010  00110000  00110011   00000011  00011001    110
9   01000111  00000110  01011000   00010111  00001001    001
10  00110001  00011110  00011001   00000001  01010100    111
11  00011111  00011000  01001110   00001000  00010010    111
12  00101101  00000100  01100110   00001010  00011000    010
13  00101110  00111001  00010011   00001001  00000111    100
14  00111111  00001111  00100111   00001001  00011111    000
15  00111000  00000100  00110000   00011000  00001000    001
16  00111111  00101110  00011100   00001001  00000111    100
17  00101101  00011100  00110001   00001010  00011000    110
18  00101101  00010000  00110011   00101011  00011001    100
19  00010000  00111100  00011001   00000100  00010010    100
20  00101010  00000011  00110011   00000010  00011001    100
21  00011001  00001100  00101110   00100100  00011111    100
22  00101000  00100111  00110000   00010010  00011111    001
23  00100110  00011111  00010101   00011000  00000101    111
24  00110101  00010000  00110011   00000110  00011001    110

In [21]:
from crossover import annular_crossover
individuals_df = pd.DataFrame(cromosomas)
offspring_df = annular_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   00111111  00000010  00111011   00011000  00000111    110
1   00111000  00000100  00111001   00010100  00001000    001
2   00110101  00001011  01001110   00001000  00001001    101
3   00011111  00011000  00110110   00001111  00010001    110
4   00110101  00001000  00100111   00001001  00011111    100
5   00111111  00110001  00100110   00000110  00000100    001
6   00101010  00010110  00110001   00001010  00011000    010
7   00101101  00010000  00110011   00010000  00011001    110
8   00011101  00001001  01011000   00010000  00001000    111
9   00100010  00110000  00111110   00000011  00000011    001
10  00101000  00100100  00100101   00010000  00001000    100
11  00110001  00011110  00110000   00010010  00010010    111
12  00110001  00100111  00011111   00010011  00011101    011
13  01000101  00000010  00100100   00000110  00010100    001
14  01100001  00000110  00101101   01010001  00000001    101
15  00000101  00010010  00010111   00001100  00001100    010
16  00100010  00010000  00111110   00000011  00000011    001
17  00101010  00110000  00110011   00010000  00011001    110
18  00001001  00011100  01011000   00010111  00011000    111
19  01000111  00000110  00010110   00010100  00001001    001
20  00110001  00000101  00100101   00010000  00010010    111
21  00100011  00011110  00011001   00000001  01010100    110
22  00110001  00011000  01001110   00001000  00001001    110
23  00011111  00011110  00100101   00010000  00010010    111
24  00001011  00010110  00110001   00001010  00011000    010
25  00101101  00000100  01100110   00010000  00010001    111
26  01000100  00111001  00001111   00011001  00000111    101
27  00101110  00100011  00010011   00001001  00010011    100
28  00001000  00001000  00100111   00001000  00111011    000
29  00111111  00001111  00111100   00001001  00011111    100
30  00111000  00000100  00111011   00011000  00000111    001
31  00101000  00100100  00110000   00010010  00001000    100
32  00111111  00101110  00011100   00010101  00000111    000
33  00110000  00001000  00100111   00001001  00011111    100
34  00101101  00010110  00110001   00011010  00010101    010
35  00011010  00011100  00110001   00001010  00011000    110
36  00101101  00000011  00110011   00010000  00011001    100
37  00101010  00010000  00101001   00101011  00010010    110
38  00010011  01000001  00011001   00011100  00010010    010
39  00010000  00111100  00000010   00000100  00111111    100
40  00100010  00010000  00110011   00010000  00011001    110
41  00101010  00000011  00011101   00000010  01010010    100
42  00011001  00011111  00101110   00100100  00011111    100
43  00011011  00001100  00001011   00001000  01001001    000
44  00110111  00100100  00010000   00001001  00011111    001
45  00101000  00100111  00110000   00010010  00001000    100
46  00010111  00100001  00110110   00100101  00000101    001
47  00100110  00011111  00010101   00011000  00100010    111
48  00101010  00110001  00100110   00010000  00011001    110
49  00110101  00010000  00110011   00000110  00000100    001

In [22]:
from genes import decode_genes
cromosomas_decoded2 = decode_genes(cromosomas_ok1)
cromosomas_decoded2

,strength,agility,expertise,resistance,life,height
1,5.90000000e+01,3.00000000e+00,5.80000000e+01,1.90000000e+01,8.00000000e+00,1.40000000e+00
2,5.90000000e+01,2.00000000e+00,5.70000000e+01,2.40000000e+01,6.00000000e+00,1.90000000e+00
3,5.00000000e+01,2.30000000e+01,5.10000000e+01,7.00000000e+00,1.60000000e+01,1.70000000e+00
4,3.20000000e+01,1.10000000e+01,8.10000000e+01,1.50000000e+01,9.00000000e+00,2.00000000e+00
5,6.10000000e+01,1.70000000e+01,3.80000000e+01,6.00000000e+00,2.80000000e+01,1.80000000e+00
6,5.50000000e+01,4.00000000e+01,3.90000000e+01,9.00000000e+00,7.00000000e+00,1.30000000e+00
7,4.50000000e+01,2.30000000e+01,5.40000000e+01,0.00000000e+00,2.60000000e+01,1.90000000e+00
8,4.20000000e+01,1.50000000e+01,4.50000000e+01,2.40000000e+01,2.20000000e+01,1.50000000e+00
9,1.00000000e+00,4.30000000e+01,8.40000000e+01,1.70000000e+01,2.00000000e+00,1.40000000e+00
10,6.80000000e+01,1.00000000e+01,6.20000000e+01,0.00000000e+00,8.00000000e+00,2.00000000e+00
11,3.40000000e+01,5.20000000e+01,4.10000000e+01,1.30000000e+01,8.00000000e+00,2.00000000e+00
12,5.90000000e+01,4.00000000e+00,4.40000000e+01,2.20000000e+01,1.90000000e+01,1.70000000e+00
13,3.50000000e+01,3.20000000e+01,4.40000000e+01,1.80000000e+01,1.90000000e+01,1.40000000e+00
14,8.50000000e+01,7.00000000e+00,2.10000000e+01,6.00000000e+00,2.90000000e+01,1.60000000e+00
15,9.30000000e+01,1.60000000e+01,2.60000000e+01,1.20000000e+01,0.00000000e+00,1.70000000e+00
16,1.00000000e+00,6.00000000e+00,4.20000000e+01,8.60000000e+01,1.30000000e+01,1.60000000e+00
17,4.90000000e+01,2.30000000e+01,7.30000000e+01,2.00000000e+00,1.00000000e+00,1.90000000e+00
18,3.20000000e+01,3.60000000e+01,4.70000000e+01,1.30000000e+01,2.00000000e+01,1.40000000e+00
19,6.00000000e+00,2.50000000e+01,7.70000000e+01,1.80000000e+01,2.20000000e+01,1.40000000e+00
20,8.10000000e+01,6.00000000e+00,2.60000000e+01,2.50000000e+01,8.00000000e+00,2.00000000e+00
21,6.70000000e+01,6.00000000e+00,4.80000000e+01,1.00000000e+00,2.60000000e+01,1.90000000e+00
22,2.60000000e+01,2.40000000e+01,2.00000000e+01,1.20000000e+01,6.60000000e+01,2.00000000e+00
23,4.60000000e+01,2.80000000e+01,6.50000000e+01,7.00000000e+00,1.00000000e+00,2.00000000e+00
24,3.20000000e+01,2.50000000e+01,4.80000000e+01,1.60000000e+01,2.60000000e+01,1.90000000e+00
25,4.60000000e+01,2.00000000e+01,3.90000000e+01,1.60000000e+01,2.60000000e+01,1.60000000e+00
26,1.00000000e+01,5.00000000e+00,1.08000000e+02,9.00000000e+00,1.50000000e+01,1.90000000e+00
27,3.80000000e+01,6.20000000e+01,2.00000000e+01,9.00000000e+00,2.00000000e+01,1.70000000e+00
28,7.40000000e+01,3.10000000e+01,1.40000000e+01,2.30000000e+01,6.00000000e+00,1.80000000e+00
29,4.70000000e+01,6.00000000e+00,4.50000000e+01,6.00000000e+00,4.40000000e+01,1.30000000e+00
30,1.20000000e+01,2.20000000e+01,5.70000000e+01,1.20000000e+01,4.60000000e+01,1.70000000e+00
31,6.40000000e+01,4.00000000e+00,5.50000000e+01,2.00000000e+01,4.00000000e+00,1.30000000e+00
32,3.50000000e+01,3.10000000e+01,5.20000000e+01,2.10000000e+01,9.00000000e+00,1.80000000e+00
33,4.80000000e+01,3.50000000e+01,2.20000000e+01,1.90000000e+01,2.30000000e+01,1.30000000e+00
34,6.70000000e+01,1.10000000e+01,5.30000000e+01,7.00000000e+00,9.00000000e+00,1.70000000e+00
35,3.00000000e+01,2.30000000e+01,5.80000000e+01,1.10000000e+01,2.50000000e+01,1.90000000e+00
36,3.80000000e+01,2.50000000e+01,4.20000000e+01,2.20000000e+01,2.00000000e+01,1.50000000e+00
37,5.10000000e+01,0.00000000e+00,4.10000000e+01,3.70000000e+01,1.90000000e+01,1.90000000e+00
38,3.70000000e+01,1.60000000e+01,4.90000000e+01,2.30000000e+01,2.20000000e+01,1.70000000e+00
39,1.40000000e+01,5.30000000e+01,2.20000000e+01,3.00000000e+00,5.50000000e+01,1.50000000e+00
40,2.10000000e+01,7.30000000e+01,1.00000000e+00,3.20000000e+01,2.00000000e+01,1.70000000e+00
41,6.10000000e+01,4.00000000e+00,4.20000000e+01,2.00000000e+00,3.80000000e+01,1.70000000e+00
42,2.50000000e+01,1.20000000e+01,3.80000000e+01,1.20000000e+01,6.10000000e+01,1.90000000e+00
43,2.70000000e+01,1.50000000e+01,4.30000000e+01,4.00000000e+01,2.50000000e+01,1.70000000e+00
44,2.50000000e+01,2.80000000e+01,1.40000000e+01,4.00000000e+00,7.90000000e+01,1.30000000e+00
45,5.90000000e+01,4.10000000e+01,1.80000000e+01,2.00000000e+01,9.00000000e+00,1.70000000e+00
46,3.70000000e+01,3.40000000e+01,4.20000000e+01,7.00000000e+00,2.70000000e+01,1.40000000e+00
47,3.30000000e+01,4.60000000e+01,3.10000000e+01,3.60000000e+01,3.00000000e+00,1.40000000e+00
48,2.90000000e+01,2.40000000e+01,4.00000000e+01,2.70000000e+01,2.70000000e+01,2.00000000e+00
49,3.70000000e+01,4.90000000e+01,5.40000000e+01,6.00000000e+00,4.00000000e+00,1.40000000e+00
50,5.80000000e+01,1.60000000e+01,3.50000000e+01,1.60000000e+01,2.50000000e+01,1.90000000e+00

In [23]:
#columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
#cromosomas_decoded2['sum'] = cromosomas_decoded2[columnas_a_sumar].sum(axis=1) 
#cromosomas_decoded2

In [24]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas_ok)
#cromosomas_decoded2

In [25]:
from mutation import one_gene_mutation
from crossover import normalize_chromosome

mutation_rate = 0.1
  
result = one_gene_mutation(cromosomas_ok2, mutation_rate)
cromosomas_okm = normalize_chromosome(result)

cromosomas_okm

    strength   agility expertise resistance      life height
1   00100011  00000000  00011111   01010000  00000010    000
2   00101100  00011110  00101111   00010011  00001000    111
3   00010110  00001011  01100111   00000110  00000111    111
4   00101001  00001001  01001100   00001001  00001011    100
5   00011100  00010001  01010111   00000001  00001110    100
6   00101011  00101000  00011111   00001011  00010111    001
7   00101011  00010001  00110001   00010001  00010111    010
8   00011110  00001110  01010001   00000101  00010010    110
9   00001110  00011001  00111101   00110000  00000000    101
10  00111011  00001101  00110101   00000101  00010011    011
11  00110101  00100010  00100011   00010001  00001000    100
12  00100110  00011100  00110010   00010000  00010000    111
13  01000001  00011011  00011110   00000100  00010110    001
14  00110001  00001000  00100110   00011001  00011100    011
15  00001010  00101100  00111110   00001000  00011000    101
16  01000000  00000001  00011000   00111011  00000000    010
17  01001010  00100001  00101000   00000000  00000000    001
18  00010111  00001011  00100110   00111001  00010010    110
19  00011100  00000010  00100100   01010000  00000010    101
20  00001010  00101110  00011010   00011000  00101001    011
21  00110101  00011111  00010101   00000000  00101011    111
22  00101010  00000110  00110110   00010101  00011001    110
23  00101000  00011000  00100101   00010011  00011011    110
24  00011100  00010101  00111110   00001110  00010111    111
25  00111011  00000100  00110011   00000010  00100000    110
26  00001011  00010010  01010110   00010100  00001110    011
27  01000110  00100010  00001110   00011000  00000110    101
28  00101101  00111010  00010011   00001001  00010001    100
29  00101011  00001010  00100000   00000101  00111001    000
30  00001111  00000010  01001101   00001011  00101011    100
31  00101110  00000100  00111011   00011111  00001000    001
32  00010111  01011101  00010111   00000110  00000010    100
33  00110001  00101111  00011100   00010001  00000111    000
34  00111111  00000111  00100110   00001100  00011011    100
35  00110110  00010101  00100100   00010011  00010001    110
36  00110111  00010100  00101101   00001001  00010011    010
37  00100010  00001110  00101011   00100101  00010011    100
38  00111101  00000000  00110001   00001110  00011000    110
39  00010000  00110000  00000011   00001100  01000100    000
40  00001111  01001100  00010110   00010010  00010001    110
41  00111001  00000000  01000101   00000000  00010111    100
42  00001110  00001000  00001011   01001101  00100110    110
43  00010011  00001001  00100011   00011100  00111001    100
44  00110000  00100111  00001101   00001010  00100111    000
45  00110100  00100101  00101101   00000001  00001110    101
46  00101101  00100101  00001111   00011010  00011000    000
47  00110011  00000000  00010011   00101110  00100000    011
48  00000011  00100101  00011111   00000100  01001010    101
49  00100111  00101101  00110000   00001111  00000000    110
50  00111001  00010001  00101001   00000110  00011010    001

In [26]:
from genes import decode_genes
cromosomas_decoded2m = decode_genes(cromosomas_okm)
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height
1,3.50000000e+01,0.00000000e+00,3.10000000e+01,8.00000000e+01,2.00000000e+00,1.30000000e+00
2,4.40000000e+01,3.00000000e+01,4.70000000e+01,1.90000000e+01,8.00000000e+00,2.00000000e+00
3,2.20000000e+01,1.10000000e+01,1.03000000e+02,6.00000000e+00,7.00000000e+00,2.00000000e+00
4,4.10000000e+01,9.00000000e+00,7.60000000e+01,9.00000000e+00,1.10000000e+01,1.70000000e+00
5,2.80000000e+01,1.70000000e+01,8.70000000e+01,1.00000000e+00,1.40000000e+01,1.70000000e+00
6,4.30000000e+01,4.00000000e+01,3.10000000e+01,1.10000000e+01,2.30000000e+01,1.40000000e+00
7,4.30000000e+01,1.70000000e+01,4.90000000e+01,1.70000000e+01,2.30000000e+01,1.50000000e+00
8,3.00000000e+01,1.40000000e+01,8.10000000e+01,5.00000000e+00,1.80000000e+01,1.90000000e+00
9,1.40000000e+01,2.50000000e+01,6.10000000e+01,4.80000000e+01,0.00000000e+00,1.80000000e+00
10,5.90000000e+01,1.30000000e+01,5.30000000e+01,5.00000000e+00,1.90000000e+01,1.60000000e+00
11,5.30000000e+01,3.40000000e+01,3.50000000e+01,1.70000000e+01,8.00000000e+00,1.70000000e+00
12,3.80000000e+01,2.80000000e+01,5.00000000e+01,1.60000000e+01,1.60000000e+01,2.00000000e+00
13,6.50000000e+01,2.70000000e+01,3.00000000e+01,4.00000000e+00,2.20000000e+01,1.40000000e+00
14,4.90000000e+01,8.00000000e+00,3.80000000e+01,2.50000000e+01,2.80000000e+01,1.60000000e+00
15,1.00000000e+01,4.40000000e+01,6.20000000e+01,8.00000000e+00,2.40000000e+01,1.80000000e+00
16,6.40000000e+01,1.00000000e+00,2.40000000e+01,5.90000000e+01,0.00000000e+00,1.50000000e+00
17,7.40000000e+01,3.30000000e+01,4.00000000e+01,0.00000000e+00,0.00000000e+00,1.40000000e+00
18,2.30000000e+01,1.10000000e+01,3.80000000e+01,5.70000000e+01,1.80000000e+01,1.90000000e+00
19,2.80000000e+01,2.00000000e+00,3.60000000e+01,8.00000000e+01,2.00000000e+00,1.80000000e+00
20,1.00000000e+01,4.60000000e+01,2.60000000e+01,2.40000000e+01,4.10000000e+01,1.60000000e+00
21,5.30000000e+01,3.10000000e+01,2.10000000e+01,0.00000000e+00,4.30000000e+01,2.00000000e+00
22,4.20000000e+01,6.00000000e+00,5.40000000e+01,2.10000000e+01,2.50000000e+01,1.90000000e+00
23,4.00000000e+01,2.40000000e+01,3.70000000e+01,1.90000000e+01,2.70000000e+01,1.90000000e+00
24,2.80000000e+01,2.10000000e+01,6.20000000e+01,1.40000000e+01,2.30000000e+01,2.00000000e+00
25,5.90000000e+01,4.00000000e+00,5.10000000e+01,2.00000000e+00,3.20000000e+01,1.90000000e+00
26,1.10000000e+01,1.80000000e+01,8.60000000e+01,2.00000000e+01,1.40000000e+01,1.60000000e+00
27,7.00000000e+01,3.40000000e+01,1.40000000e+01,2.40000000e+01,6.00000000e+00,1.80000000e+00
28,4.50000000e+01,5.80000000e+01,1.90000000e+01,9.00000000e+00,1.70000000e+01,1.70000000e+00
29,4.30000000e+01,1.00000000e+01,3.20000000e+01,5.00000000e+00,5.70000000e+01,1.30000000e+00
30,1.50000000e+01,2.00000000e+00,7.70000000e+01,1.10000000e+01,4.30000000e+01,1.70000000e+00
31,4.60000000e+01,4.00000000e+00,5.90000000e+01,3.10000000e+01,8.00000000e+00,1.40000000e+00
32,2.30000000e+01,9.30000000e+01,2.30000000e+01,6.00000000e+00,2.00000000e+00,1.70000000e+00
33,4.90000000e+01,4.70000000e+01,2.80000000e+01,1.70000000e+01,7.00000000e+00,1.30000000e+00
34,6.30000000e+01,7.00000000e+00,3.80000000e+01,1.20000000e+01,2.70000000e+01,1.70000000e+00
35,5.40000000e+01,2.10000000e+01,3.60000000e+01,1.90000000e+01,1.70000000e+01,1.90000000e+00
36,5.50000000e+01,2.00000000e+01,4.50000000e+01,9.00000000e+00,1.90000000e+01,1.50000000e+00
37,3.40000000e+01,1.40000000e+01,4.30000000e+01,3.70000000e+01,1.90000000e+01,1.70000000e+00
38,6.10000000e+01,0.00000000e+00,4.90000000e+01,1.40000000e+01,2.40000000e+01,1.90000000e+00
39,1.60000000e+01,4.80000000e+01,3.00000000e+00,1.20000000e+01,6.80000000e+01,1.30000000e+00
40,1.50000000e+01,7.60000000e+01,2.20000000e+01,1.80000000e+01,1.70000000e+01,1.90000000e+00
41,5.70000000e+01,0.00000000e+00,6.90000000e+01,0.00000000e+00,2.30000000e+01,1.70000000e+00
42,1.40000000e+01,8.00000000e+00,1.10000000e+01,7.70000000e+01,3.80000000e+01,1.90000000e+00
43,1.90000000e+01,9.00000000e+00,3.50000000e+01,2.80000000e+01,5.70000000e+01,1.70000000e+00
44,4.80000000e+01,3.90000000e+01,1.30000000e+01,1.00000000e+01,3.90000000e+01,1.30000000e+00
45,5.20000000e+01,3.70000000e+01,4.50000000e+01,1.00000000e+00,1.40000000e+01,1.80000000e+00
46,4.50000000e+01,3.70000000e+01,1.50000000e+01,2.60000000e+01,2.40000000e+01,1.30000000e+00
47,5.10000000e+01,0.00000000e+00,1.90000000e+01,4.60000000e+01,3.20000000e+01,1.60000000e+00
48,3.00000000e+00,3.70000000e+01,3.10000000e+01,4.00000000e+00,7.40000000e+01,1.80000000e+00
49,3.90000000e+01,4.50000000e+01,4.80000000e+01,1.50000000e+01,0.00000000e+00,1.90000000e+00
50,5.70000000e+01,1.70000000e+01,4.10000000e+01,6.00000000e+00,2.60000000e+01,1.40000000e+00

In [27]:
columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
cromosomas_decoded2m['sum'] = cromosomas_decoded2m[columnas_a_sumar].sum(axis=1) 
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height,sum
1,3.50000000e+01,0.00000000e+00,3.10000000e+01,8.00000000e+01,2.00000000e+00,1.30000000e+00,1.48000000e+02
2,4.40000000e+01,3.00000000e+01,4.70000000e+01,1.90000000e+01,8.00000000e+00,2.00000000e+00,1.48000000e+02
3,2.20000000e+01,1.10000000e+01,1.03000000e+02,6.00000000e+00,7.00000000e+00,2.00000000e+00,1.49000000e+02
4,4.10000000e+01,9.00000000e+00,7.60000000e+01,9.00000000e+00,1.10000000e+01,1.70000000e+00,1.46000000e+02
5,2.80000000e+01,1.70000000e+01,8.70000000e+01,1.00000000e+00,1.40000000e+01,1.70000000e+00,1.47000000e+02
6,4.30000000e+01,4.00000000e+01,3.10000000e+01,1.10000000e+01,2.30000000e+01,1.40000000e+00,1.48000000e+02
7,4.30000000e+01,1.70000000e+01,4.90000000e+01,1.70000000e+01,2.30000000e+01,1.50000000e+00,1.49000000e+02
8,3.00000000e+01,1.40000000e+01,8.10000000e+01,5.00000000e+00,1.80000000e+01,1.90000000e+00,1.48000000e+02
9,1.40000000e+01,2.50000000e+01,6.10000000e+01,4.80000000e+01,0.00000000e+00,1.80000000e+00,1.48000000e+02
10,5.90000000e+01,1.30000000e+01,5.30000000e+01,5.00000000e+00,1.90000000e+01,1.60000000e+00,1.49000000e+02
11,5.30000000e+01,3.40000000e+01,3.50000000e+01,1.70000000e+01,8.00000000e+00,1.70000000e+00,1.47000000e+02
12,3.80000000e+01,2.80000000e+01,5.00000000e+01,1.60000000e+01,1.60000000e+01,2.00000000e+00,1.48000000e+02
13,6.50000000e+01,2.70000000e+01,3.00000000e+01,4.00000000e+00,2.20000000e+01,1.40000000e+00,1.48000000e+02
14,4.90000000e+01,8.00000000e+00,3.80000000e+01,2.50000000e+01,2.80000000e+01,1.60000000e+00,1.48000000e+02
15,1.00000000e+01,4.40000000e+01,6.20000000e+01,8.00000000e+00,2.40000000e+01,1.80000000e+00,1.48000000e+02
16,6.40000000e+01,1.00000000e+00,2.40000000e+01,5.90000000e+01,0.00000000e+00,1.50000000e+00,1.48000000e+02
17,7.40000000e+01,3.30000000e+01,4.00000000e+01,0.00000000e+00,0.00000000e+00,1.40000000e+00,1.47000000e+02
18,2.30000000e+01,1.10000000e+01,3.80000000e+01,5.70000000e+01,1.80000000e+01,1.90000000e+00,1.47000000e+02
19,2.80000000e+01,2.00000000e+00,3.60000000e+01,8.00000000e+01,2.00000000e+00,1.80000000e+00,1.48000000e+02
20,1.00000000e+01,4.60000000e+01,2.60000000e+01,2.40000000e+01,4.10000000e+01,1.60000000e+00,1.47000000e+02
21,5.30000000e+01,3.10000000e+01,2.10000000e+01,0.00000000e+00,4.30000000e+01,2.00000000e+00,1.48000000e+02
22,4.20000000e+01,6.00000000e+00,5.40000000e+01,2.10000000e+01,2.50000000e+01,1.90000000e+00,1.48000000e+02
23,4.00000000e+01,2.40000000e+01,3.70000000e+01,1.90000000e+01,2.70000000e+01,1.90000000e+00,1.47000000e+02
24,2.80000000e+01,2.10000000e+01,6.20000000e+01,1.40000000e+01,2.30000000e+01,2.00000000e+00,1.48000000e+02
25,5.90000000e+01,4.00000000e+00,5.10000000e+01,2.00000000e+00,3.20000000e+01,1.90000000e+00,1.48000000e+02
26,1.10000000e+01,1.80000000e+01,8.60000000e+01,2.00000000e+01,1.40000000e+01,1.60000000e+00,1.49000000e+02
27,7.00000000e+01,3.40000000e+01,1.40000000e+01,2.40000000e+01,6.00000000e+00,1.80000000e+00,1.48000000e+02
28,4.50000000e+01,5.80000000e+01,1.90000000e+01,9.00000000e+00,1.70000000e+01,1.70000000e+00,1.48000000e+02
29,4.30000000e+01,1.00000000e+01,3.20000000e+01,5.00000000e+00,5.70000000e+01,1.30000000e+00,1.47000000e+02
30,1.50000000e+01,2.00000000e+00,7.70000000e+01,1.10000000e+01,4.30000000e+01,1.70000000e+00,1.48000000e+02
31,4.60000000e+01,4.00000000e+00,5.90000000e+01,3.10000000e+01,8.00000000e+00,1.40000000e+00,1.48000000e+02
32,2.30000000e+01,9.30000000e+01,2.30000000e+01,6.00000000e+00,2.00000000e+00,1.70000000e+00,1.47000000e+02
33,4.90000000e+01,4.70000000e+01,2.80000000e+01,1.70000000e+01,7.00000000e+00,1.30000000e+00,1.48000000e+02
34,6.30000000e+01,7.00000000e+00,3.80000000e+01,1.20000000e+01,2.70000000e+01,1.70000000e+00,1.47000000e+02
35,5.40000000e+01,2.10000000e+01,3.60000000e+01,1.90000000e+01,1.70000000e+01,1.90000000e+00,1.47000000e+02
36,5.50000000e+01,2.00000000e+01,4.50000000e+01,9.00000000e+00,1.90000000e+01,1.50000000e+00,1.48000000e+02
37,3.40000000e+01,1.40000000e+01,4.30000000e+01,3.70000000e+01,1.90000000e+01,1.70000000e+00,1.47000000e+02
38,6.10000000e+01,0.00000000e+00,4.90000000e+01,1.40000000e+01,2.40000000e+01,1.90000000e+00,1.48000000e+02
39,1.60000000e+01,4.80000000e+01,3.00000000e+00,1.20000000e+01,6.80000000e+01,1.30000000e+00,1.47000000e+02
40,1.50000000e+01,7.60000000e+01,2.20000000e+01,1.80000000e+01,1.70000000e+01,1.90000000e+00,1.48000000e+02
41,5.70000000e+01,0.00000000e+00,6.90000000e+01,0.00000000e+00,2.30000000e+01,1.70000000e+00,1.49000000e+02
42,1.40000000e+01,8.00000000e+00,1.10000000e+01,7.70000000e+01,3.80000000e+01,1.90000000e+00,1.48000000e+02
43,1.90000000e+01,9.00000000e+00,3.50000000e+01,2.80000000e+01,5.70000000e+01,1.70000000e+00,1.48000000e+02
44,4.80000000e+01,3.90000000e+01,1.30000000e+01,1.00000000e+01,3.90000000e+01,1.30000000e+00,1.49000000e+02
45,5.20000000e+01,3.70000000e+01,4.50000000e+01,1.00000000e+00,1.40000000e+01,1.80000000e+00,1.49000000e+02
46,4.50000000e+01,3.70000000e+01,1.50000000e+01,2.60000000e+01,2.40000000e+01,1.30000000e+00,1.47000000e+02
47,5.10000000e+01,0.00000000e+00,1.90000000e+01,4.60000000e+01,3.20000000e+01,1.60000000e+00,1.48000000e+02
48,3.00000000e+00,3.70000000e+01,3.10000000e+01,4.00000000e+00,7.40000000e+01,1.80000000e+00,1.49000000e+02
49,3.90000000e+01,4.50000000e+01,4.80000000e+01,1.50000000e+01,0.00000000e+00,1.90000000e+00,1.47000000e+02
50,5.70000000e+01,1.70000000e+01,4.10000000e+01,6.00000000e+00,2.60000000e+01,1.40000000e+00,1.47000000e+02

In [28]:
from mutation import multi_gene_mutation

# Ejemplo de uso:
mutation_rate = 0.8
resultmp = multi_gene_mutation(cromosomas_ok1, mutation_rate)
resultmp

    strength   agility expertise resistance      life height
0   00111011  00000011  00111010   00010011  00001000    001
1   00111011  00000010  00111001   00011000  00000110    110
2   00110010  00010111  00110011   00000111  00010000    100
3   00100000  00001011  01010001   00001111  00001001    111
4   00111101  00010001  00100110   00000110  00011100    101
5   00110111  00101000  00100111   00001001  00000111    000
6   00101101  00010111  00110110   00000000  00011010    110
7   00101010  00001111  00101101   00011000  00010110    010
8   00000001  00101011  01010100   00010001  00000010    001
9   01000100  00001010  00111110   00000000  00001000    111
10  00100010  00110100  00101001   00001101  00001000    111
11  00111011  00000100  00101100   00010110  00010011    100
12  00100011  00100000  00101100   00010010  00010011    001
13  01010101  00000111  00010101   00000110  00011101    011
14  01011101  00010000  00011010   00001100  00000000    100
15  00000001  00000110  00101010   01010110  00001101    011
16  00110001  00010111  01001001   00000010  00000001    110
17  00100000  00100100  00101111   00001101  00010100    001
18  00000110  00011001  01001101   00010010  00010110    001
19  01010001  00000110  00011010   00011001  00001000    111
20  01000011  00000110  00110000   00000001  00011010    110
21  00011010  00011000  00010100   00001100  01000010    111
22  00101110  00011100  01000001   00000111  00000001    111
23  00100000  00011001  00110000   00010000  00011010    110
24  00101110  00010100  00100111   00010000  00011010    011
25  00001010  00000101  01101100   00001001  00001111    110
26  00100110  00111110  00010100   00001001  00010100    100
27  01001010  00011111  00001110   00010111  00000110    101
28  00101111  00000110  00101101   00000110  00101100    000
29  00001100  00010110  00111001   00001100  00101110    100
30  01000000  00000100  00110111   00010100  00000100    000
31  00100011  00011111  00110100   00010101  00001001    101
32  00110000  00100011  00010110   00010011  00010111    000
33  01000011  00001011  00110101   00000111  00001001    100
34  00011110  00010111  00111010   00001011  00011001    110
35  00100110  00011001  00101010   00010110  00010100    010
36  00110011  00000000  00101001   00100101  00010011    110
37  00100101  00010000  00110001   00010111  00010110    100
38  00001110  00110101  00010110   00000011  00110111    010
39  00010101  01001001  00000001   00100000  00010100    100
40  00111101  00000100  00101010   00000010  00100110    100
41  00011001  00001100  00100110   00001100  00111101    110
42  00011011  00001111  00101011   00101000  00011001    100
43  00011001  00011100  00001110   00000100  01001111    000
44  00111011  00101001  00010010   00010100  00001001    100
45  00100101  00100010  00101010   00000111  00011011    001
46  00100001  00101110  00011111   00100100  00000011    001
47  00011101  00011000  00101000   00011011  00011011    111
48  00100101  00110001  00110110   00000110  00000100    001
49  00111010  00010000  00100011   00010000  00011001    110

    strength   agility expertise resistance      life height
0   00111011  00000011  00111010   11100100  11110111    110
1   00111011  11111111  11000110   00011000  00000110    101
2   01001101  11111000  11001101   11111001  11001111    010
3   11010111  11110100  10101010   10110100  11111110    111
4   00111101  10101110  11000000   01111001  11110011    101
5   11001100  00101000  01001000   01010100  00000111    101
6   00101101  10011100  00110110   11011011  11001001    000
7   00101010  10110010  00101101   11100110  00010110    101
8   11111110  11111100  10001000   11101110  01111101    111
9   10111011  00001010  11010001   11110111  11110100    000
10  11011101  10011011  11011110   11010000  11111111    000
11  11000100  11111011  01010011   01101001  00010011    011
12  10111000  11011110  11011111   11101100  11001100    001
13  01010101  11111010  11101000   10111001  00011101    100
14  01011101  01101110  00011010   00001100  11101100    011
15  11110111  00000110  01010001   10000000  11000110    100
16  00110001  01101000  00010010   01111111  11111110    000
17  11011110  00100100  11010010   01010011  00010100    111
18  11111001  11000110  01001101   11101001  10100011    010
19  11101000  00000110  11100101   00011001  11110111    000
20  11110101  11011101  11001011   10011111  10100001    011
21  11100101  11100110  11111000   00001100  01000010    000
22  10010011  11000011  00011110   00000111  01110100    100
23  11011111  10100110  00110000   00010000  00011010    100
24  00101110  11101011  11011000   00010000  11100101    011
25  11111100  00000101  00010111   11110110  01101001    001
26  11011101  11000101  10011011   00001001  11101011    010
27  11110111  11000100  11111111   00010111  11111101    010
28  11010100  11111001  11010010   10111001  00110001    010
29  00001100  00010110  11100110   00001100  10010011    100
30  00111010  00000100  00110111   11101011  11111001    010
31  10011100  01100000  11001010   11101001  00001001    101
32  11101010  11001100  10101001   01010100  10101010    111
33  10101110  11110100  01001010   00000111  11111110    011
34  11110000  00010111  11000100   00001011  11101110    001
35  11111011  10100110  00101010   00010110  10101011    100
36  11111110  00111011  11001011   01011110  11101000    100
37  00100101  00010000  10010110   00010111  11101010    011
38  10010011  11011010  11111111   01110100  11001111    100
39  10101000  10110000  11111100   11011111  01111011    011
40  10000010  00101011  11010001   11110100  11011000    100
41  10000010  01110000  01101001   11110111  00111101    011
42  10100010  11010100  11000010   11110111  11100100    011
43  00011001  11100011  11110001   00000100  11110011    010
44  11000101  10100110  11111101   11101011  00001001    001
45  11011110  10001100  11110000   00000111  11100111    110
46  11011110  10010001  11101000   00100100  10110100    110
47  00011101  11100010  11000111   00011011  00011011    000
48  11011000  00110001  01000000   00111001  01101011    010
49  11000101  11101011  11011100   11101111  01000110    001

In [29]:
from mutation import multi_gene_mutation_uniform

# Ejemplo de uso:
mutation_rate = 0.7
resultmu = multi_gene_mutation_uniform(cromosomas_ok1, mutation_rate)
resultmu

    strength   agility expertise resistance      life height
0   00111011  00000011  00111010   00010011  00001000    001
1   00111011  00000010  00111001   00011000  00000110    110
2   00110010  00010111  00110011   00000111  00010000    100
3   00100000  00001011  01010001   00001111  00001001    111
4   00111101  00010001  00100110   00000110  00011100    101
5   00110111  00101000  00100111   00001001  00000111    000
6   00101101  00010111  00110110   00000000  00011010    110
7   00101010  00001111  00101101   00011000  00010110    010
8   00000001  00101011  01010100   00010001  00000010    001
9   01000100  00001010  00111110   00000000  00001000    111
10  00100010  00110100  00101001   00001101  00001000    111
11  00111011  00000100  00101100   00010110  00010011    100
12  00100011  00100000  00101100   00010010  00010011    001
13  01010101  00000111  00010101   00000110  00011101    011
14  01011101  00010000  00011010   00001100  00000000    100
15  00000001  00000110  00101010   01010110  00001101    011
16  00110001  00010111  01001001   00000010  00000001    110
17  00100000  00100100  00101111   00001101  00010100    001
18  00000110  00011001  01001101   00010010  00010110    001
19  01010001  00000110  00011010   00011001  00001000    111
20  01000011  00000110  00110000   00000001  00011010    110
21  00011010  00011000  00010100   00001100  01000010    111
22  00101110  00011100  01000001   00000111  00000001    111
23  00100000  00011001  00110000   00010000  00011010    110
24  00101110  00010100  00100111   00010000  00011010    011
25  00001010  00000101  01101100   00001001  00001111    110
26  00100110  00111110  00010100   00001001  00010100    100
27  01001010  00011111  00001110   00010111  00000110    101
28  00101111  00000110  00101101   00000110  00101100    000
29  00001100  00010110  00111001   00001100  00101110    100
30  01000000  00000100  00110111   00010100  00000100    000
31  00100011  00011111  00110100   00010101  00001001    101
32  00110000  00100011  00010110   00010011  00010111    000
33  01000011  00001011  00110101   00000111  00001001    100
34  00011110  00010111  00111010   00001011  00011001    110
35  00100110  00011001  00101010   00010110  00010100    010
36  00110011  00000000  00101001   00100101  00010011    110
37  00100101  00010000  00110001   00010111  00010110    100
38  00001110  00110101  00010110   00000011  00110111    010
39  00010101  01001001  00000001   00100000  00010100    100
40  00111101  00000100  00101010   00000010  00100110    100
41  00011001  00001100  00100110   00001100  00111101    110
42  00011011  00001111  00101011   00101000  00011001    100
43  00011001  00011100  00001110   00000100  01001111    000
44  00111011  00101001  00010010   00010100  00001001    100
45  00100101  00100010  00101010   00000111  00011011    001
46  00100001  00101110  00011111   00100100  00000011    001
47  00011101  00011000  00101000   00011011  00011011    111
48  00100101  00110001  00110110   00000110  00000100    001
49  00111010  00010000  00100011   00010000  00011001    110

    strength   agility expertise resistance      life height
0   11000100  11111100  11000101   00010011  11110111    110
1   11000100  11111101  00111001   11100111  11111001    001
2   11001101  00010111  00110011   11111000  00010000    100
3   11011111  00001011  10101110   11110000  11110110    000
4   00111101  00010001  11011001   00000110  11100011    101
5   11001000  11010111  11011000   11110110  11111000    111
6   00101101  11101000  11001001   11111111  11100101    110
7   00101010  11110000  11010010   11100111  11101001    101
8   00000001  00101011  10101011   11101110  11111101    110
9   10111011  11110101  00111110   11111111  11110111    111
10  00100010  11001011  11010110   11110010  11110111    111
11  11000100  11111011  11010011   11101001  11101100    011
12  00100011  00100000  11010011   00010010  11101100    110
13  01010101  11111000  11101010   11111001  11100010    100
14  10100010  11101111  00011010   11110011  00000000    011
15  00000001  11111001  11010101   10101001  11110010    011
16  11001110  11101000  10110110   11111101  00000001    110
17  11011111  11011011  11010000   11110010  11101011    110
18  11111001  00011001  01001101   11101101  00010110    001
19  10101110  11111001  11100101   11100110  11110111    000
20  10111100  11111001  11001111   00000001  11100101    001
21  11100101  11100111  00010100   11110011  10111101    000
22  00101110  11100011  10111110   11111000  11111110    111
23  11011111  11100110  11001111   11101111  00011010    001
24  00101110  11101011  00100111   11101111  11100101    100
25  11110101  11111010  10010011   11110110  11110000    001
26  11011001  00111110  11101011   11110110  11101011    100
27  01001010  11100000  11110001   11101000  11111001    101
28  11010000  11111001  11010010   00000110  11010011    111
29  11110011  11101001  00111001   11110011  00101110    011
30  10111111  11111011  11001000   11101011  11111011    000
31  11011100  11100000  00110100   11101010  11110110    010
32  11001111  11011100  11101001   11101100  11101000    111
33  10111100  11110100  11001010   11111000  11110110    011
34  11100001  11101000  00111010   11110100  00011001    001
35  11011001  11100110  00101010   11101001  11101011    101
36  00110011  11111111  00101001   00100101  00010011    001
37  11011010  11101111  11001110   11101000  11101001    100
38  11110001  11001010  11101001   00000011  11001000    010
39  11101010  10110110  00000001   11011111  11101011    011
40  11000010  00000100  11010101   00000010  11011001    100
41  11100110  11110011  11011001   11110011  00111101    001
42  00011011  00001111  00101011   00101000  11100110    011
43  00011001  00011100  00001110   00000100  01001111    111
44  11000100  00101001  11101101   00010100  11110110    011
45  11011010  00100010  11010101   11111000  11100100    110
46  11011110  11010001  11100000   11011011  00000011    110
47  11100010  00011000  11010111   00011011  11100100    111
48  11011010  00110001  11001001   11111001  11111011    001
49  11000101  00010000  11011100   00010000  00011001    001

In [30]:
from population import eval_performace

new_generation = eval_performace(cromosomas_decoded2,type)
new_generation

,strength,agility,expertise,resistance,life,height,characterType,performance
10,6.80000000e+01,1.00000000e+01,6.20000000e+01,0.00000000e+00,8.00000000e+00,2.00000000e+00,CharacterType.ARCHER,1.09072524e+03
17,4.90000000e+01,2.30000000e+01,7.30000000e+01,2.00000000e+00,1.00000000e+00,1.90000000e+00,CharacterType.ARCHER,1.00507783e+03
34,6.70000000e+01,1.10000000e+01,5.30000000e+01,7.00000000e+00,9.00000000e+00,1.70000000e+00,CharacterType.ARCHER,9.35330592e+02
2,5.90000000e+01,2.00000000e+00,5.70000000e+01,2.40000000e+01,6.00000000e+00,1.90000000e+00,CharacterType.ARCHER,9.21787559e+02
21,6.70000000e+01,6.00000000e+00,4.80000000e+01,1.00000000e+00,2.60000000e+01,1.90000000e+00,CharacterType.ARCHER,8.98988960e+02
1,5.90000000e+01,3.00000000e+00,5.80000000e+01,1.90000000e+01,8.00000000e+00,1.40000000e+00,CharacterType.ARCHER,8.98255291e+02
23,4.60000000e+01,2.80000000e+01,6.50000000e+01,7.00000000e+00,1.00000000e+00,2.00000000e+00,CharacterType.ARCHER,8.60337523e+02
31,6.40000000e+01,4.00000000e+00,5.50000000e+01,2.00000000e+01,4.00000000e+00,1.30000000e+00,CharacterType.ARCHER,8.36874403e+02
7,4.50000000e+01,2.30000000e+01,5.40000000e+01,0.00000000e+00,2.60000000e+01,1.90000000e+00,CharacterType.ARCHER,7.55571992e+02
3,5.00000000e+01,2.30000000e+01,5.10000000e+01,7.00000000e+00,1.60000000e+01,1.70000000e+00,CharacterType.ARCHER,7.47513510e+02
12,5.90000000e+01,4.00000000e+00,4.40000000e+01,2.20000000e+01,1.90000000e+01,1.70000000e+00,CharacterType.ARCHER,7.10536258e+02
41,6.10000000e+01,4.00000000e+00,4.20000000e+01,2.00000000e+00,3.80000000e+01,1.70000000e+00,CharacterType.ARCHER,7.04841033e+02
5,6.10000000e+01,1.70000000e+01,3.80000000e+01,6.00000000e+00,2.80000000e+01,1.80000000e+00,CharacterType.ARCHER,6.98760706e+02
4,3.20000000e+01,1.10000000e+01,8.10000000e+01,1.50000000e+01,9.00000000e+00,2.00000000e+00,CharacterType.ARCHER,6.93517345e+02
15,9.30000000e+01,1.60000000e+01,2.60000000e+01,1.20000000e+01,0.00000000e+00,1.70000000e+00,CharacterType.ARCHER,6.49022244e+02
49,3.70000000e+01,4.90000000e+01,5.40000000e+01,6.00000000e+00,4.00000000e+00,1.40000000e+00,CharacterType.ARCHER,6.45974590e+02
50,5.80000000e+01,1.60000000e+01,3.50000000e+01,1.60000000e+01,2.50000000e+01,1.90000000e+00,CharacterType.ARCHER,6.39143149e+02
6,5.50000000e+01,4.00000000e+01,3.90000000e+01,9.00000000e+00,7.00000000e+00,1.30000000e+00,CharacterType.ARCHER,6.36546981e+02
37,5.10000000e+01,0.00000000e+00,4.10000000e+01,3.70000000e+01,1.90000000e+01,1.90000000e+00,CharacterType.ARCHER,6.15236972e+02
32,3.50000000e+01,3.10000000e+01,5.20000000e+01,2.10000000e+01,9.00000000e+00,1.80000000e+00,CharacterType.ARCHER,5.81158135e+02
8,4.20000000e+01,1.50000000e+01,4.50000000e+01,2.40000000e+01,2.20000000e+01,1.50000000e+00,CharacterType.ARCHER,5.74878429e+02
20,8.10000000e+01,6.00000000e+00,2.60000000e+01,2.50000000e+01,8.00000000e+00,2.00000000e+00,CharacterType.ARCHER,5.74769417e+02
29,4.70000000e+01,6.00000000e+00,4.50000000e+01,6.00000000e+00,4.40000000e+01,1.30000000e+00,CharacterType.ARCHER,5.68635692e+02
25,4.60000000e+01,2.00000000e+01,3.90000000e+01,1.60000000e+01,2.60000000e+01,1.60000000e+00,CharacterType.ARCHER,5.55198225e+02
35,3.00000000e+01,2.30000000e+01,5.80000000e+01,1.10000000e+01,2.50000000e+01,1.90000000e+00,CharacterType.ARCHER,5.52855846e+02
38,3.70000000e+01,1.60000000e+01,4.90000000e+01,2.30000000e+01,2.20000000e+01,1.70000000e+00,CharacterType.ARCHER,5.45695393e+02
46,3.70000000e+01,3.40000000e+01,4.20000000e+01,7.00000000e+00,2.70000000e+01,1.40000000e+00,CharacterType.ARCHER,5.18757185e+02
36,3.80000000e+01,2.50000000e+01,4.20000000e+01,2.20000000e+01,2.00000000e+01,1.50000000e+00,CharacterType.ARCHER,5.14521719e+02
24,3.20000000e+01,2.50000000e+01,4.80000000e+01,1.60000000e+01,2.60000000e+01,1.90000000e+00,CharacterType.ARCHER,5.10471553e+02
13,3.50000000e+01,3.20000000e+01,4.40000000e+01,1.80000000e+01,1.90000000e+01,1.40000000e+00,CharacterType.ARCHER,5.06492843e+02
11,3.40000000e+01,5.20000000e+01,4.10000000e+01,1.30000000e+01,8.00000000e+00,2.00000000e+00,CharacterType.ARCHER,4.98619224e+02
18,3.20000000e+01,3.60000000e+01,4.70000000e+01,1.30000000e+01,2.00000000e+01,1.40000000e+00,CharacterType.ARCHER,4.97181082e+02
14,8.50000000e+01,7.00000000e+00,2.10000000e+01,6.00000000e+00,2.90000000e+01,1.60000000e+00,CharacterType.ARCHER,4.80573795e+02
45,5.90000000e+01,4.10000000e+01,1.80000000e+01,2.00000000e+01,9.00000000e+00,1.70000000e+00,CharacterType.ARCHER,4.08460011e+02
48,2.90000000e+01,2.40000000e+01,4.00000000e+01,2.70000000e+01,2.70000000e+01,2.00000000e+00,CharacterType.ARCHER,3.89900983e+02
28,7.40000000e+01,3.10000000e+01,1.40000000e+01,2.30000000e+01,6.00000000e+00,1.80000000e+00,CharacterType.ARCHER,3.88424776e+02
47,3.30000000e+01,4.60000000e+01,3.10000000e+01,3.60000000e+01,3.00000000e+00,1.40000000e+00,CharacterType.ARCHER,3.80262554e+02
43,2.70000000e+01,1.50000000e+01,4.30000000e+01,4.00000000e+01,2.50000000e+01,1.70000000e+00,CharacterType.ARCHER,3.66670755e+02
33,4.80000000e+01,3.50000000e+01,2.20000000e+01,1.90000000e+01,2.30000000e+01,1.30000000e+00,CharacterType.ARCHER,3.59816198e+02
27,3.80000000e+01,6.20000000e+01,2.00000000e+01,9.00000000e+00,2.00000000e+01,1.70000000e+00,CharacterType.ARCHER,3.34825368e+02
42,2.50000000e+01,1.20000000e+01,3.80000000e+01,1.20000000e+01,6.10000000e+01,1.90000000e+00,CharacterType.ARCHER,3.23726429e+02
26,1.00000000e+01,5.00000000e+00,1.08000000e+02,9.00000000e+00,1.50000000e+01,1.90000000e+00,CharacterType.ARCHER,2.73231696e+02
30,1.20000000e+01,2.20000000e+01,5.70000000e+01,1.20000000e+01,4.60000000e+01,1.70000000e+00,CharacterType.ARCHER,2.24144070e+02
22,2.60000000e+01,2.40000000e+01,2.00000000e+01,1.20000000e+01,6.60000000e+01,2.00000000e+00,CharacterType.ARCHER,2.02499168e+02
19,6.00000000e+00,2.50000000e+01,7.70000000e+01,1.80000000e+01,2.20000000e+01,1.40000000e+00,CharacterType.ARCHER,1.41390867e+02
44,2.50000000e+01,2.80000000e+01,1.40000000e+01,4.00000000e+00,7.90000000e+01,1.30000000e+00,CharacterType.ARCHER,1.40957789e+02
39,1.40000000e+01,5.30000000e+01,2.20000000e+01,3.00000000e+00,5.50000000e+01,1.50000000e+00,CharacterType.ARCHER,1.39704875e+02
40,2.10000000e+01,7.30000000e+01,1.00000000e+00,3.20000000e+01,2.00000000e+01,1.70000000e+00,CharacterType.ARCHER,7.53894027e+01
9,1.00000000e+00,4.30000000e+01,8.40000000e+01,1.70000000e+01,2.00000000e+00,1.40000000e+00,CharacterType.ARCHER,2.50411483e+01
16,1.00000000e+00,6.00000000e+00,4.20000000e+01,8.60000000e+01,1.30000000e+01,1.60000000e+00,CharacterType.ARCHER,1.74504151e+01

In [31]:
import numpy as np
from selection import boltzmann_selection

# Example usage:

max_generation = 500
generation = 1
k = K                                  # Number of desired selected individuals.
T_0 = 20                                # Initial temperature.
T_offset = 5                          # Offset value for temperature exponential function.
reference_generation = max_generation   # Reference generation where 0 < (T_0 - T_offset) = 0.015 = deltaT is desired.
deltaT = 0.015                          # 0 < (T_0 - T_offset) = deltaT at reference generation.
m = - (np.log(deltaT) - np.log(T_0 - T_offset)) / reference_generation

new_boltzmann_selection = boltzmann_selection(poblacion_inicial,k,generation,T_0,T_offset,m)

new_boltzmann_selection

sum: 100.0
    strength  agility  expertise  resistance  life         height  \
14        63        2         57          20     8 1.90000000e+00
29        56        4         59          24     7 1.40000000e+00
72        53       11         54          15    17 1.80000000e+00
5         31       24         78           8     9 1.90000000e+00
51        63        8         39           9    31 1.70000000e+00
..       ...      ...        ...         ...   ...            ...
42         4       11         13          65    57 1.40000000e+00
67         3       22         12          87    26 1.30000000e+00
12         1       45         26          40    38 2.00000000e+00
64         1       88         12          25    24 1.60000000e+00
79         1       80          6          53    10 1.50000000e+00

           characterType    performance  performance_relative  \
14  CharacterType.ARCHER 9.91800955e+01        9.91800955e-01
29  CharacterType.ARCHER 7.84919247e-01        7.84919247e-03
72  CharacterType.ARCHER 3.46992732e-02        3.46992732e-04
5   CharacterType.ARCHER 1.05113502e-04        1.05113502e-06
51  CharacterType.ARCHER 5.83119316e-05        5.83119316e-07
..                   ...            ...                   ...
42  CharacterType.ARCHER 1.84258510e-19        1.84258510e-21
67  CharacterType.ARCHER 1.29758422e-19        1.29758422e-21
12  CharacterType.ARCHER 1.17616754e-19        1.17616754e-21
64  CharacterType.ARCHER 8.12486172e-20        8.12486172e-22
79  CharacterType.ARCHER 6.72515339e-20        6.72515339e-22

    performance_accumulated
14           9.91800955e-01
29           9.99650147e-01
72           9.99997140e-01
5            9.99998191e-01
51           9.99998774e-01
..                      ...
42           1.00000000e+00
67           1.00000000e+00
12           1.00000000e+00
64           1.00000000e+00
79           1.00000000e+00

[100 rows x 10 columns]

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
1,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
2,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
3,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
4,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
5,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
6,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
7,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
8,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
9,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
10,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
11,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
12,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
13,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
14,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
15,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
16,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
17,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
18,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
19,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
20,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
21,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
22,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
23,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
24,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
25,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
26,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
27,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
28,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
29,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
30,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
31,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
32,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
33,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
34,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
35,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
36,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
37,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
38,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
39,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
40,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
41,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
42,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
43,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
44,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
45,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
46,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
47,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
48,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01
49,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.91800955e+01,9.91800955e-01,9.91800955e-01

In [32]:
from selection import deterministic_tournament_selection 

individualsT = deterministic_tournament_selection(poblacion_inicial, 10, k)
individualsT

c:\Users\dpenaloza\Downloads\SIA\sia-tp2\src\selection.py:196: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  individuals = pd.concat([individuals, winner])

,strength,agility,expertise,resistance,life,height,characterType,performance
0,23,31,54,37,5,1.40000000e+00,CharacterType.ARCHER,3.94857150e+02
1,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02
2,29,9,88,16,8,2.00000000e+00,CharacterType.ARCHER,6.62934860e+02
3,29,9,88,16,8,2.00000000e+00,CharacterType.ARCHER,6.62934860e+02
4,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02
5,56,4,59,24,7,1.40000000e+00,CharacterType.ARCHER,8.75402227e+02
6,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02
7,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02
8,26,28,49,26,21,1.90000000e+00,CharacterType.ARCHER,4.30362993e+02
9,43,29,28,23,27,1.60000000e+00,CharacterType.ARCHER,4.14532570e+02
10,49,39,36,6,20,1.60000000e+00,CharacterType.ARCHER,5.87874034e+02
11,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
12,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02
13,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
14,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02
15,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02
16,42,16,51,16,25,1.90000000e+00,CharacterType.ARCHER,6.65485293e+02
17,68,35,19,9,19,1.70000000e+00,CharacterType.ARCHER,4.58957831e+02
18,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02
19,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02
20,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
21,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02
22,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02
23,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
24,25,23,60,13,29,1.40000000e+00,CharacterType.ARCHER,4.60885799e+02
25,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
26,18,2,97,21,12,1.70000000e+00,CharacterType.ARCHER,4.30178456e+02
27,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02
28,49,39,36,6,20,1.60000000e+00,CharacterType.ARCHER,5.87874034e+02
29,24,35,46,21,24,2.00000000e+00,CharacterType.ARCHER,3.77497416e+02
30,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02
31,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
32,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02
33,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02
34,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02
35,18,2,97,21,12,1.70000000e+00,CharacterType.ARCHER,4.30178456e+02
36,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
37,56,4,59,24,7,1.40000000e+00,CharacterType.ARCHER,8.75402227e+02
38,34,48,62,3,3,1.40000000e+00,CharacterType.ARCHER,6.57046077e+02
39,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02
40,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02
41,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02
42,46,57,15,25,7,1.80000000e+00,CharacterType.ARCHER,3.29800910e+02
43,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02
44,63,2,57,20,8,1.90000000e+00,CharacterType.ARCHER,9.71188536e+02
45,26,28,49,26,21,1.90000000e+00,CharacterType.ARCHER,4.30362993e+02
46,69,2,31,19,29,1.40000000e+00,CharacterType.ARCHER,5.87721976e+02
47,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
48,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
49,29,9,88,16,8,2.00000000e+00,CharacterType.ARCHER,6.62934860e+02
50,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02
51,35,5,25,1,84,1.90000000e+00,CharacterType.ARCHER,2.93314582e+02
52,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02

In [33]:
from selection import stochastic_tournament_selection
#ejemplo
individualsTd = stochastic_tournament_selection(poblacion_inicial, k, 0.6)
individualsTd

,strength,agility,expertise,resistance,life,height,characterType,performance
13,24,46,44,30,6,1.70000000e+00,CharacterType.ARCHER,3.63554208e+02
59,74,25,14,26,11,1.70000000e+00,CharacterType.ARCHER,3.59535247e+02
67,3,22,12,87,26,1.30000000e+00,CharacterType.ARCHER,1.93739155e+01
38,45,3,41,43,18,1.70000000e+00,CharacterType.ARCHER,5.30852794e+02
87,22,10,7,70,41,1.80000000e+00,CharacterType.ARCHER,6.48672286e+01
75,27,31,11,8,73,1.30000000e+00,CharacterType.ARCHER,1.29988035e+02
35,33,6,8,52,51,1.90000000e+00,CharacterType.ARCHER,9.93779634e+01
73,15,42,27,40,26,1.90000000e+00,CharacterType.ARCHER,1.68373087e+02
24,22,43,13,50,22,1.50000000e+00,CharacterType.ARCHER,1.39486330e+02
44,4,2,24,75,45,1.40000000e+00,CharacterType.ARCHER,3.98192671e+01
50,18,2,97,21,12,1.70000000e+00,CharacterType.ARCHER,4.30178456e+02
27,40,68,2,31,9,1.90000000e+00,CharacterType.ARCHER,1.51146411e+02
22,8,37,24,44,37,1.30000000e+00,CharacterType.ARCHER,7.88736497e+01
75,27,31,11,8,73,1.30000000e+00,CharacterType.ARCHER,1.29988035e+02
47,49,39,36,6,20,1.60000000e+00,CharacterType.ARCHER,5.87874034e+02
72,53,11,54,15,17,1.80000000e+00,CharacterType.ARCHER,8.13666871e+02
9,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
53,16,65,2,4,63,1.70000000e+00,CharacterType.ARCHER,5.88882837e+01
9,40,36,48,18,8,1.70000000e+00,CharacterType.ARCHER,6.08287724e+02
66,23,14,6,97,10,1.30000000e+00,CharacterType.ARCHER,5.65080960e+01
73,15,42,27,40,26,1.90000000e+00,CharacterType.ARCHER,1.68373087e+02
97,5,18,45,81,1,1.50000000e+00,CharacterType.ARCHER,7.26736078e+01
48,63,55,9,6,17,1.50000000e+00,CharacterType.ARCHER,3.10929966e+02
33,25,12,46,36,31,1.70000000e+00,CharacterType.ARCHER,3.58766033e+02
11,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02
57,45,22,49,10,24,1.50000000e+00,CharacterType.ARCHER,6.70307744e+02
11,49,30,37,16,18,2.00000000e+00,CharacterType.ARCHER,5.96473002e+02
65,9,105,24,10,2,1.60000000e+00,CharacterType.ARCHER,1.03865502e+02
5,31,24,78,8,9,1.90000000e+00,CharacterType.ARCHER,6.98871773e+02
95,26,28,49,26,21,1.90000000e+00,CharacterType.ARCHER,4.30362993e+02
62,9,6,88,23,24,2.00000000e+00,CharacterType.ARCHER,2.18855971e+02
36,10,6,29,90,15,1.60000000e+00,CharacterType.ARCHER,9.59592700e+01
22,8,37,24,44,37,1.30000000e+00,CharacterType.ARCHER,7.88736497e+01
51,63,8,39,9,31,1.70000000e+00,CharacterType.ARCHER,6.87208362e+02
16,46,57,15,25,7,1.80000000e+00,CharacterType.ARCHER,3.29800910e+02
85,10,7,24,99,10,1.40000000e+00,CharacterType.ARCHER,8.11965147e+01
49,12,82,2,28,26,1.90000000e+00,CharacterType.ARCHER,5.37812592e+01
18,19,60,25,28,18,1.50000000e+00,CharacterType.ARCHER,2.04608900e+02
87,22,10,7,70,41,1.80000000e+00,CharacterType.ARCHER,6.48672286e+01
23,87,9,2,33,19,1.60000000e+00,CharacterType.ARCHER,7.82548170e+01
56,15,11,17,5,102,1.90000000e+00,CharacterType.ARCHER,9.95635831e+01
92,55,5,7,55,28,1.50000000e+00,CharacterType.ARCHER,1.28181694e+02
2,3,12,63,36,36,1.70000000e+00,CharacterType.ARCHER,6.93861318e+01
18,19,60,25,28,18,1.50000000e+00,CharacterType.ARCHER,2.04608900e+02
1,18,11,63,4,54,1.70000000e+00,CharacterType.ARCHER,3.43801339e+02
69,14,102,20,7,7,1.80000000e+00,CharacterType.ARCHER,1.48461502e+02
63,121,5,6,6,12,1.90000000e+00,CharacterType.ARCHER,1.91592465e+02
96,14,32,70,33,1,1.30000000e+00,CharacterType.ARCHER,2.66480777e+02
39,53,49,38,6,4,1.40000000e+00,CharacterType.ARCHER,6.82417607e+02
25,35,5,25,1,84,1.90000000e+00,CharacterType.ARCHER,2.93314582e+02

In [34]:
from selection import rank_based_selection
#ejemplo
individualsR = rank_based_selection(poblacion_inicial,k)
individualsR

sum: 49.5

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,35,18,7,53,37,2.00000000e+00,CharacterType.ARCHER,6.70000000e-01,1.35353535e-02,5.53333333e-01
1,28,25,11,67,19,2.00000000e+00,CharacterType.ARCHER,6.30000000e-01,1.27272727e-02,6.05454545e-01
2,12,82,2,28,26,1.90000000e+00,CharacterType.ARCHER,9.00000000e-01,1.81818182e-02,1.90909091e-01
3,38,33,21,24,34,2.00000000e+00,CharacterType.ARCHER,3.70000000e-01,7.47474747e-03,8.65454545e-01
4,15,38,29,31,37,1.30000000e+00,CharacterType.ARCHER,5.60000000e-01,1.13131313e-02,6.88888889e-01
5,3,12,63,36,36,1.70000000e+00,CharacterType.ARCHER,8.10000000e-01,1.63636364e-02,3.45454545e-01
6,23,14,6,97,10,1.30000000e+00,CharacterType.ARCHER,8.80000000e-01,1.77777778e-02,2.26666667e-01
7,27,52,15,17,39,2.00000000e+00,CharacterType.ARCHER,4.90000000e-01,9.89898990e-03,7.62424242e-01
8,7,32,69,35,7,2.00000000e+00,CharacterType.ARCHER,5.90000000e-01,1.19191919e-02,6.54343434e-01
9,3,22,12,87,26,1.30000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
10,2,73,38,26,11,1.40000000e+00,CharacterType.ARCHER,9.40000000e-01,1.89898990e-02,1.16969697e-01
11,24,46,44,30,6,1.70000000e+00,CharacterType.ARCHER,2.70000000e-01,5.45454545e-03,9.29090909e-01
12,16,65,2,4,63,1.70000000e+00,CharacterType.ARCHER,8.60000000e-01,1.73737374e-02,2.61616162e-01
13,16,65,2,4,63,1.70000000e+00,CharacterType.ARCHER,8.60000000e-01,1.73737374e-02,2.61616162e-01
14,55,39,16,9,31,1.40000000e+00,CharacterType.ARCHER,3.00000000e-01,6.06060606e-03,9.12121212e-01
15,3,40,51,29,27,1.30000000e+00,CharacterType.ARCHER,8.50000000e-01,1.71717172e-02,2.78787879e-01
16,10,6,29,90,15,1.60000000e+00,CharacterType.ARCHER,7.20000000e-01,1.45454545e-02,4.83636364e-01
17,23,31,54,37,5,1.40000000e+00,CharacterType.ARCHER,2.40000000e-01,4.84848485e-03,9.44242424e-01
18,5,18,45,81,1,1.50000000e+00,CharacterType.ARCHER,8.00000000e-01,1.61616162e-02,3.61616162e-01
19,12,82,2,28,26,1.90000000e+00,CharacterType.ARCHER,9.00000000e-01,1.81818182e-02,1.90909091e-01
20,27,36,48,29,10,1.60000000e+00,CharacterType.ARCHER,2.20000000e-01,4.44444444e-03,9.53333333e-01
21,121,5,6,6,12,1.90000000e+00,CharacterType.ARCHER,5.20000000e-01,1.05050505e-02,7.32121212e-01
22,6,50,33,57,4,1.40000000e+00,CharacterType.ARCHER,7.70000000e-01,1.55555556e-02,4.08888889e-01
23,38,21,3,83,5,1.70000000e+00,CharacterType.ARCHER,7.90000000e-01,1.59595960e-02,3.77575758e-01
24,1,45,26,40,38,2.00000000e+00,CharacterType.ARCHER,9.70000000e-01,1.95959596e-02,5.93939394e-02
25,10,7,24,99,10,1.40000000e+00,CharacterType.ARCHER,7.30000000e-01,1.47474747e-02,4.69090909e-01
26,19,60,25,28,18,1.50000000e+00,CharacterType.ARCHER,4.70000000e-01,9.49494949e-03,7.81616162e-01
27,40,68,2,31,9,1.90000000e+00,CharacterType.ARCHER,5.80000000e-01,1.17171717e-02,6.66060606e-01
28,114,16,5,5,10,2.00000000e+00,CharacterType.ARCHER,4.80000000e-01,9.69696970e-03,7.72121212e-01
29,3,12,63,36,36,1.70000000e+00,CharacterType.ARCHER,8.10000000e-01,1.63636364e-02,3.45454545e-01
30,40,68,2,31,9,1.90000000e+00,CharacterType.ARCHER,5.80000000e-01,1.17171717e-02,6.66060606e-01
31,4,2,24,75,45,1.40000000e+00,CharacterType.ARCHER,9.30000000e-01,1.87878788e-02,1.35757576e-01
32,10,7,24,99,10,1.40000000e+00,CharacterType.ARCHER,7.30000000e-01,1.47474747e-02,4.69090909e-01
33,38,21,3,83,5,1.70000000e+00,CharacterType.ARCHER,7.90000000e-01,1.59595960e-02,3.77575758e-01
34,22,10,7,70,41,1.80000000e+00,CharacterType.ARCHER,8.40000000e-01,1.69696970e-02,2.95757576e-01
35,19,27,32,63,9,1.80000000e+00,CharacterType.ARCHER,4.60000000e-01,9.29292929e-03,7.90909091e-01
36,6,50,33,57,4,1.40000000e+00,CharacterType.ARCHER,7.70000000e-01,1.55555556e-02,4.08888889e-01
37,10,68,29,34,9,1.70000000e+00,CharacterType.ARCHER,6.60000000e-01,1.33333333e-02,5.66666667e-01
38,103,5,7,1,34,1.70000000e+00,CharacterType.ARCHER,5.10000000e-01,1.03030303e-02,7.42424242e-01
39,1,88,12,25,24,1.60000000e+00,CharacterType.ARCHER,9.80000000e-01,1.97979798e-02,3.97979798e-02
40,3,22,12,87,26,1.30000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
41,5,18,25,3,99,1.70000000e+00,CharacterType.ARCHER,8.90000000e-01,1.79797980e-02,2.08888889e-01
42,68,35,19,9,19,1.70000000e+00,CharacterType.ARCHER,1.80000000e-01,3.63636364e-03,9.69090909e-01
43,71,28,22,20,9,1.40000000e+00,CharacterType.ARCHER,1.60000000e-01,3.23232323e-03,9.75757576e-01
44,3,22,12,87,26,1.30000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
45,74,25,14,26,11,1.70000000e+00,CharacterType.ARCHER,2.80000000e-01,5.65656566e-03,9.23636364e-01
46,5,18,45,81,1,1.50000000e+00,CharacterType.ARCHER,8.00000000e-01,1.61616162e-02,3.61616162e-01
47,3,12,63,36,36,1.70000000e+00,CharacterType.ARCHER,8.10000000e-01,1.63636364e-02,3.45454545e-01
48,10,68,29,34,9,1.70000000e+00,CharacterType.ARCHER,6.60000000e-01,1.33333333e-02,5.66666667e-01
49,7,32,69,35,7,2.00000000e+00,CharacterType.ARCHER,5.90000000e-01,1.19191919e-02,6.54343434e-01