In [1]:
from population import generate_init_population

In [2]:
import pandas as pd
pd.options.display.float_format = '{:.8e}'.format

from population import generate_init_population
from character import CharacterType
#from src.stats import random_stats

N = 100
K = 50
maxStatsValue = 150
type = CharacterType.ARCHER

#equipment_data = random_stats(N, maxStatsValue)
poblacion_inicial = generate_init_population(N,maxStatsValue,type)

poblacion_inicial

,strength,agility,expertise,resistance,life,height,characterType,performance
10,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
95,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
19,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02
43,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02
87,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02
...,...,...,...,...,...,...,...,...
33,2,99,15,19,15,1.80000000e+00,CharacterType.ARCHER,1.94812460e+01
91,3,53,8,6,80,1.70000000e+00,CharacterType.ARCHER,1.93331552e+01
5,16,13,1,89,31,1.60000000e+00,CharacterType.ARCHER,1.84701899e+01
30,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,1.00986591e+01
4,7,2,3,3,135,1.80000000e+00,CharacterType.ARCHER,9.36063826e+00

In [3]:
#AÃ±ado las columnas de desempeÃ±o relativo y acumulado
from selection import add_relative_accumulate
poblacion_rel_acu = add_relative_accumulate(poblacion_inicial)
poblacion_rel_acu

sum: 28103.961572076325

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
10,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02,3.44548687e-02,3.44548687e-02
95,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
19,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02,2.63527783e-02,8.89174845e-02
43,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02,2.56676324e-02,1.14585117e-01
87,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02,2.55908648e-02,1.40175982e-01
...,...,...,...,...,...,...,...,...,...,...
33,2,99,15,19,15,1.80000000e+00,CharacterType.ARCHER,1.94812460e+01,6.93185051e-04,9.97962471e-01
91,3,53,8,6,80,1.70000000e+00,CharacterType.ARCHER,1.93331552e+01,6.87915658e-04,9.98650386e-01
5,16,13,1,89,31,1.60000000e+00,CharacterType.ARCHER,1.84701899e+01,6.57209478e-04,9.99307596e-01
30,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,1.00986591e+01,3.59332227e-04,9.99666928e-01
4,7,2,3,3,135,1.80000000e+00,CharacterType.ARCHER,9.36063826e+00,3.33071842e-04,1.00000000e+00

#### Seleccion de k indiduos
A*(mÃ©todo1) + (1-A)*(mÃ©todo2)

In [4]:
import numpy as np
#Dado un K
#Si quiero un m1_perc de la selecciÃ³n con metodo1
#K = 120
m1_perc = 0.3
N1 = int(np.round(K * m1_perc))
N2 = K - N1
#N1

In [5]:
from selection import elitist_selection
nueva_poblacion_e = elitist_selection(poblacion_rel_acu,N1)
#nueva_poblacion_e

In [6]:
from selection import roulette_wheel_selection
nueva_poblacion_rul = roulette_wheel_selection(poblacion_rel_acu, N2)
#nueva_poblacion_rul

In [7]:
from selection import universal_selection
    
nueva_poblacion_uni = universal_selection(poblacion_rel_acu, N2)
#nueva_poblacion_uni

In [8]:
from selection import rank_based_selection

nueva_poblacion_rank = rank_based_selection(poblacion_inicial, N2)
#nueva_poblacion_rank

sum: 49.5

In [9]:
import pandas as pd
selection_total = pd.concat([nueva_poblacion_e,nueva_poblacion_rul])
selection_total

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02,3.44548687e-02,3.44548687e-02
1,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
2,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02,2.63527783e-02,8.89174845e-02
3,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02,2.56676324e-02,1.14585117e-01
4,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02,2.55908648e-02,1.40175982e-01
5,31,10,82,12,15,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02,2.39424078e-02,1.64118389e-01
6,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02,2.27208707e-02,1.86839260e-01
7,66,33,29,7,15,1.60000000e+00,CharacterType.ARCHER,6.14300674e+02,2.18581524e-02,2.08697413e-01
8,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02,2.15024732e-02,2.30199886e-01
9,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02,2.08728144e-02,2.51072700e-01
10,50,8,39,39,14,1.80000000e+00,CharacterType.ARCHER,5.82737077e+02,2.07350510e-02,2.71807751e-01
11,48,28,38,30,6,1.70000000e+00,CharacterType.ARCHER,5.78080781e+02,2.05693699e-02,2.92377121e-01
12,30,2,77,17,24,1.30000000e+00,CharacterType.ARCHER,5.67256446e+02,2.01842166e-02,3.12561338e-01
13,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02,1.99723851e-02,3.32533723e-01
14,70,42,22,12,4,1.80000000e+00,CharacterType.ARCHER,5.57237948e+02,1.98277366e-02,3.52361459e-01
0,32,15,38,11,54,1.50000000e+00,CharacterType.ARCHER,3.96532675e+02,1.41094939e-02,5.60380281e-01
1,21,74,26,15,14,1.80000000e+00,CharacterType.ARCHER,2.44467789e+02,8.69869496e-03,7.61282713e-01
2,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02,3.44548687e-02,3.44548687e-02
3,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02,2.15024732e-02,2.30199886e-01
4,50,8,39,39,14,1.80000000e+00,CharacterType.ARCHER,5.82737077e+02,2.07350510e-02,2.71807751e-01
5,32,15,38,11,54,1.50000000e+00,CharacterType.ARCHER,3.96532675e+02,1.41094939e-02,5.60380281e-01
6,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
7,80,21,12,36,1,2.00000000e+00,CharacterType.ARCHER,3.31265533e+02,1.17871472e-02,6.71912562e-01
8,30,2,77,17,24,1.30000000e+00,CharacterType.ARCHER,5.67256446e+02,2.01842166e-02,3.12561338e-01
9,51,69,4,16,10,1.90000000e+00,CharacterType.ARCHER,2.20024245e+02,7.82894057e-03,8.19642230e-01
10,61,3,22,14,50,2.00000000e+00,CharacterType.ARCHER,3.97173625e+02,1.41323003e-02,5.46270787e-01
11,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
12,18,44,56,21,11,1.90000000e+00,CharacterType.ARCHER,3.46814686e+02,1.23404199e-02,6.24193875e-01
13,80,21,12,36,1,2.00000000e+00,CharacterType.ARCHER,3.31265533e+02,1.17871472e-02,6.71912562e-01
14,23,11,31,49,36,1.80000000e+00,CharacterType.ARCHER,2.42252882e+02,8.61988377e-03,7.69902597e-01
15,44,42,4,31,29,1.60000000e+00,CharacterType.ARCHER,1.40181014e+02,4.98794498e-03,8.94017930e-01
16,60,6,14,32,38,1.60000000e+00,CharacterType.ARCHER,2.57239563e+02,9.15314244e-03,7.52584018e-01
17,32,63,33,14,8,1.90000000e+00,CharacterType.ARCHER,4.27741484e+02,1.52199712e-02,5.03224290e-01
18,45,42,30,21,12,1.30000000e+00,CharacterType.ARCHER,4.43188351e+02,1.57696042e-02,4.88004319e-01
19,61,3,22,14,50,2.00000000e+00,CharacterType.ARCHER,3.97173625e+02,1.41323003e-02,5.46270787e-01
20,45,42,30,21,12,1.30000000e+00,CharacterType.ARCHER,4.43188351e+02,1.57696042e-02,4.88004319e-01
21,31,10,82,12,15,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02,2.39424078e-02,1.64118389e-01
22,8,16,64,53,9,1.60000000e+00,CharacterType.ARCHER,1.52869935e+02,5.43944435e-03,8.78327093e-01
23,70,42,22,12,4,1.80000000e+00,CharacterType.ARCHER,5.57237948e+02,1.98277366e-02,3.52361459e-01
24,55,22,27,29,17,1.50000000e+00,CharacterType.ARCHER,4.84308959e+02,1.72327648e-02,4.06585946e-01
25,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02,2.56676324e-02,1.14585117e-01
26,17,39,40,2,52,1.30000000e+00,CharacterType.ARCHER,2.34401525e+02,8.34051542e-03,8.03895513e-01
27,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
28,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02,2.81098375e-02,6.25647062e-02
29,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02,2.63527783e-02,8.89174845e-02
30,19,1,33,9,88,1.60000000e+00,CharacterType.ARCHER,2.05942244e+02,7.32787237e-03,8.26970102e-01
31,33,15,57,21,24,1.70000000e+00,CharacterType.ARCHER,5.53303964e+02,1.96877569e-02,3.72049216e-01
32,32,47,35,5,31,1.70000000e+00,CharacterType.ARCHER,4.08053827e+02,1.45194415e-02,5.17743732e-01
33,6,47,9,14,74,1.70000000e+00,CharacterType.ARCHER,3.57312150e+01,1.27139424e-03,9.94820585e-01
34,45,42,30,21,12,1.30000000e+00,CharacterType.ARCHER,4.43188351e+02,1.57696042e-02,4.88004319e-01

In [10]:
from genes import  encode_genes

cromosomas = encode_genes(selection_total)
#cromosomas

In [11]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas)
#cromosomas_decoded2

In [12]:
from crossover import normalize_chromosome

cromosomas_norm = normalize_chromosome(cromosomas)
cromosomas_norm

    strength   agility expertise resistance      life height
1   01000110  00000010  00110110   00000011  00010101    010
2   00100011  00000001  01011011   00010010  00000101    111
3   00100111  00001011  01000001   00001001  00011010    110
4   01001101  00010011  00100000   00000110  00010000    101
5   00110101  00100010  00101100   00001010  00001001    011
6   00011111  00001010  01010010   00001100  00001111    010
7   00101011  00000111  00110011   00101001  00001000    101
8   01000010  00100001  00011101   00000111  00001111    011
9   00100100  00001000  00111001   00000101  00101100    111
10  00100111  00111101  00101000   00000010  00001000    110
11  00110010  00001000  00100111   00100111  00001110    101
12  00110000  00011100  00100110   00011110  00000110    100
13  00011110  00000010  01001101   00010001  00011000    000
14  01001001  00010010  00011010   00011010  00000111    100
15  01000110  00101010  00010110   00001100  00000100    101
16  00100000  00001111  00100110   00001011  00110110    010
17  00010101  01001010  00011010   00001111  00001110    101
18  01000110  00000010  00110110   00000011  00010101    010
19  00100100  00001000  00111001   00000101  00101100    111
20  00110010  00001000  00100111   00100111  00001110    101
21  00100000  00001111  00100110   00001011  00110110    010
22  00100011  00000001  01011011   00010010  00000101    111
23  01010000  00010101  00001100   00100100  00000001    111
24  00011110  00000010  01001101   00010001  00011000    000
25  00110011  01000101  00000100   00010000  00001010    110
26  00111101  00000011  00010110   00001110  00110010    111
27  00100011  00000001  01011011   00010010  00000101    111
28  00010010  00101100  00111000   00010101  00001011    110
29  01010000  00010101  00001100   00100100  00000001    111
30  00010111  00001011  00011111   00110001  00100100    101
31  00101100  00101010  00000100   00011111  00011101    011
32  00111100  00000110  00001110   00100000  00100110    011
33  00100000  00111111  00100001   00001110  00001000    110
34  00101101  00101010  00011110   00010101  00001100    000
35  00111101  00000011  00010110   00001110  00110010    111
36  00101101  00101010  00011110   00010101  00001100    000
37  00011111  00001010  01010010   00001100  00001111    010
38  00001000  00010000  01000000   00110101  00001001    011
39  01000110  00101010  00010110   00001100  00000100    101
40  00110111  00010110  00011011   00011101  00010001    010
41  01001101  00010011  00100000   00000110  00010000    101
42  00010001  00100111  00101000   00000010  00110100    000
43  00100011  00000001  01011011   00010010  00000101    111
44  00100011  00000001  01011011   00010010  00000101    111
45  00100111  00001011  01000001   00001001  00011010    110
46  00010011  00000001  00100001   00001001  01011000    011
47  00100001  00001111  00111001   00010101  00011000    100
48  00100000  00101111  00100011   00000101  00011111    100
49  00000110  00101111  00001001   00001110  01001010    100
50  00101101  00101010  00011110   00010101  00001100    000

In [13]:
from crossover import single_point_crossover, normalize_chromosome

new_individuals = single_point_crossover(cromosomas)
cromosomas_ok1 = normalize_chromosome(new_individuals)

cromosomas_ok1

    strength   agility expertise resistance      life height
1   01001100  00000011  00111110   00000010  00000101    011
2   00100001  00000000  01010000   00010000  00010010    110
3   00101010  00010010  00111100   00000101  00010110    101
4   01001011  00001011  00100010   00001001  00010011    110
5   00110101  00100011  00101010   00000110  00001100    010
6   00011001  00000010  01011101   00010001  00001011    011
7   00100001  00011010  00110000   00011110  00001011    101
8   01011011  00001001  00011001   00001100  00001010    011
9   00101011  00001110  00101100   00000010  00101100    110
10  00100000  00110010  00110011   00000100  00001010    111
11  00101011  00011001  00100010   00100010  00001100    100
12  00110111  00001000  00101011   00100010  00000110    101
13  00011001  00000010  01010000   00010010  00010111    000
14  01001011  00010001  00011000   00011000  00000111    100
15  01000000  00101111  00010110   00001011  00000110    110
16  00100110  00001010  00100110   00001100  00110100    001
17  00001110  00000100  00110101   00011010  00110010    110
18  00110101  00101110  00100100   00000100  00001000    001
19  00101101  00001010  01000100   00001000  00010001    111
20  00101001  00000110  00100010   00011110  00100100    101
21  00011010  00000000  01000100   00001101  00101000    011
22  00101111  00010110  00110111   00010000  00001000    110
23  00111101  00000001  00110010   00010101  00001111    110
24  00100010  00101101  00011001   00101010  00000010    001
25  00100100  00101111  00001111   00001111  00100011    111
26  01100111  00001000  00000110   00001101  00010001    110
27  00010011  00000000  01100001   00010100  00001100    110
28  00100000  00101001  00110101   00010010  00000100    111
29  00100001  00010000  00101101   00110000  00000101    101
30  00111100  00001111  00001001   00100111  00011001    111
31  00111110  00001000  00000101   00101010  00011111    011
32  00101110  00100000  00001010   00011001  00100010    011
33  00101000  00100101  00101001   00010010  00001010    110
34  00100011  01000110  00010011   00001111  00001000    000
35  01000111  00001111  00100011   00000111  00010011    000
36  00101100  00011001  00010101   00010101  00100100    111
37  00001000  00010000  01000000   00110101  00001001    011
38  00011111  00001010  01010010   00001100  00001111    010
39  00111000  00100100  00010101   00010110  00001101    100
40  01001001  00011000  00011101   00010000  00000101    011
41  00110011  00011110  00011001   00000001  00101001    100
42  00100111  00011001  00110110   00001000  00010101    001
43  00100011  00000001  01011011   00010010  00000101    111
44  00100011  00000001  01011011   00010010  00000101    111
45  00100100  00001001  01000100   00001001  00011001    011
46  00010101  00000010  00011111   00001000  01010101    110
47  00100000  00001111  00110011   00010101  00011111    100
48  00100001  00101111  00101001   00000101  00011000    100
49  00010100  01000001  00001100   00100000  00010010    100
50  00011011  00100010  00010110   00001010  00110110    000

In [14]:
#from genes import decode_genes
#cromosomas_decoded = decode_genes(new_individuals)
#cromosomas_decoded

In [15]:
from crossover import two_point_crossover, normalize_chromosome

new_individuals2 = two_point_crossover(cromosomas)
cromosomas_ok2 = normalize_chromosome(new_individuals2)

cromosomas_ok2

    strength   agility expertise resistance      life height
1   01000011  00000010  00110111   00010011  00000101    010
2   00100101  00000000  01011000   00000001  00010100    111
3   01010010  00001111  00011010   00000101  00010100    100
4   00010001  00001110  01010101   00001010  00010101    111
5   00010111  00100010  01001011   00001000  00000111    011
6   01000101  00000010  00101011   00001111  00010011    010
7   01000111  00011001  00010001   00011011  00000111    101
8   00000100  00000010  01101011   00001110  00010110    011
9   00110100  00010001  00111100   00000111  00001011    111
10  00011101  00101011  00101010   00000001  00100001    110
11  00110100  00001000  00101001   00100000  00001110    101
12  00101101  00011010  00100100   00100100  00000101    100
13  00001111  00000010  01100001   00011010  00001000    100
14  01010011  00010000  00001011   00010000  00010101    000
15  00100001  00101011  00000110   00001100  00110110    001
16  01000011  00001110  00110011   00001010  00000101    110
17  00010100  00111010  00101100   00001101  00001100    001
18  01001101  00001011  00100010   00000011  00010111    110
19  00101000  00001001  00101100   00101010  00001101    111
20  00101100  00000111  00110010   00000110  00101001    101
21  00011001  00001011  01000011   00001111  00011110    010
22  00101111  00000001  00111010   00001101  00011100    111
23  00110011  00001011  00101100   00011100  00001110    101
24  01001011  00001101  00101100   00010001  00000000    010
25  00111001  00000101  00000100   00011010  00110111    110
26  00110111  00111100  00010011   00000101  00001001    111
27  00100011  00011110  00111110   00001100  00001000    111
28  00000011  00000000  01100110   00100110  00000101    110
29  00010001  00000101  00100000   00110111  00100111    111
30  01010001  00011001  00001100   00011110  00000000    101
31  00101111  00000110  00000100   00011001  01000010    011
32  00110111  00100110  00001100   00100101  00000101    011
33  00011100  00110100  00100100   00011010  00000111    000
34  00110011  00110101  00011001   00000101  00001101    110
35  00101100  00101010  00011101   00010011  00001101    101
36  00111101  00000010  00010110   00001111  00110000    010
37  00011010  00001111  00110111   00101011  00001001    010
38  00001001  00001001  01100010   00001111  00001111    011
39  01101000  00001010  00010110   00001100  00000000    101
40  00010110  00110100  00011010   00011100  00010100    010
41  01010110  00010001  00011101   00000001  00001110    001
42  00000001  00101010  00101011   00000110  00111000    100
43  00100011  00000001  01011011   00010010  00000101    111
44  00100011  00000001  01011011   00010010  00000101    111
45  00010100  00001001  00011101   00001000  01010001    010
46  00100111  00000001  01001000   00001010  00011010    111
47  00011100  00101000  00101010   00010010  00010100    100
48  00100110  00010001  00110011   00000101  00100100    100
49  00000011  00101001  00001100   00010101  01000111    100
50  00110000  00101111  00011011   00001101  00001100    000

In [16]:
from crossover import uniform_crossover
# Ejemplo de uso

individuals_df = pd.DataFrame(cromosomas)
offspring_df = uniform_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   00100011  00000001  00110110   00010010  00010101    010
1   00100111  00010011  01000001   00001001  00010000    110
2   00110101  00001010  01010010   00001010  00001111    011
3   01000010  00000111  00110011   00000111  00001111    011
4   00100111  00001000  00111001   00000010  00101100    111
5   00110010  00011100  00100111   00011110  00000110    100
6   00011110  00010010  01001101   00011010  00011000    000
7   00100000  00101010  00100110   00001011  00000100    010
8   01000110  01001010  00110110   00001111  00001110    010
9   00110010  00001000  00111001   00100111  00001110    101
10  00100000  00000001  01011011   00010010  00000101    111
11  01010000  00010101  00001100   00100100  00011000    000
12  00110011  01000101  00010110   00001110  00001010    110
13  00010010  00000001  01011011   00010101  00000101    111
14  01010000  00010101  00001100   00100100  00000001    111
15  00101100  00000110  00001110   00011111  00100110    011
16  00101101  00111111  00011110   00001110  00001100    000
17  00111101  00101010  00010110   00010101  00001100    111
18  00001000  00010000  01010010   00001100  00001111    010
19  00110111  00101010  00010110   00001100  00000100    010
20  00010001  00100111  00100000   00000010  00110100    101
21  00100011  00000001  01011011   00010010  00000101    111
22  00100111  00001011  00100001   00001001  00011010    110
23  00100001  00101111  00111001   00010101  00011000    100
24  00101101  00101111  00001001   00010101  01001010    000

In [17]:
from crossover import annular_crossover
individuals_df = pd.DataFrame(cromosomas)
offspring_df = annular_crossover(individuals_df)
print("Descendientes:")
print(offspring_df)

Descendientes:
    strength   agility expertise resistance      life height
0   01000110  00000010  01011011   00010010  00000101    010
1   00100011  00000001  00110110   00000011  00010101    111
2   00100111  00001011  01000001   00001001  00011010    110
3   01001101  00010011  00100000   00000110  00010000    101
4   00011111  00100010  00101100   00001010  00001001    011
5   00110101  00001010  01010010   00001100  00001111    010
6   00101011  00000111  00011101   00000111  00001111    101
7   01000010  00100001  00110011   00101001  00001000    011
8   00100100  00001000  00101000   00000010  00101100    111
9   00100111  00111101  00111001   00000101  00001000    110
10  00110010  00001000  00100110   00011110  00000110    101
11  00110000  00011100  00100111   00100111  00001110    100
12  00011110  00000010  00011010   00011010  00011000    000
13  01001001  00010010  01001101   00010001  00000111    100
14  01000110  00101010  00100110   00001011  00110110    101
15  00100000  00001111  00010110   00001100  00000100    010
16  01000110  01001010  00011010   00001111  00001110    101
17  00010101  00000010  00110110   00000011  00010101    010
18  00100100  00001000  00100111   00000101  00101100    111
19  00110010  00001000  00111001   00100111  00001110    101
20  00100011  00001111  00100110   00001011  00110110    010
21  00100000  00000001  01011011   00010010  00000101    111
22  00011110  00010101  00001100   00100100  00000001    111
23  01010000  00000010  01001101   00010001  00011000    000
24  00110011  01000101  00010110   00001110  00001010    110
25  00111101  00000011  00000100   00010000  00110010    111
26  00100011  00000001  00111000   00010101  00000101    111
27  00010010  00101100  01011011   00010010  00001011    110
28  00010111  00010101  00001100   00100100  00000001    111
29  01010000  00001011  00011111   00110001  00100100    101
30  00101100  00101010  00001110   00100000  00011101    011
31  00111100  00000110  00000100   00011111  00100110    011
32  00100000  00101010  00100001   00001110  00001000    110
33  00101101  00111111  00011110   00010101  00001100    000
34  00111101  00000011  00011110   00010101  00110010    111
35  00101101  00101010  00010110   00001110  00001100    000
36  00011111  00001010  01010010   00001100  00001111    010
37  00001000  00010000  01000000   00110101  00001001    011
38  01000110  00101010  00010110   00001100  00000100    101
39  00110111  00010110  00011011   00011101  00010001    010
40  01001101  00010011  00100000   00000110  00010000    101
41  00010001  00100111  00101000   00000010  00110100    000
42  00100011  00000001  01011011   00010010  00000101    111
43  00100011  00000001  01011011   00010010  00000101    111
44  00100111  00000001  00100001   00001001  00011010    110
45  00010011  00001011  01000001   00001001  01011000    011
46  00100000  00001111  00111001   00010101  00011000    100
47  00100001  00101111  00100011   00000101  00011111    100
48  00000110  00101010  00011110   00001110  01001010    100
49  00101101  00101111  00001001   00010101  00001100    000

In [18]:
from genes import decode_genes
cromosomas_decoded2 = decode_genes(cromosomas_ok1)
cromosomas_decoded2

,strength,agility,expertise,resistance,life,height
1,7.60000000e+01,3.00000000e+00,6.20000000e+01,2.00000000e+00,5.00000000e+00,1.60000000e+00
2,3.30000000e+01,0.00000000e+00,8.00000000e+01,1.60000000e+01,1.80000000e+01,1.90000000e+00
3,4.20000000e+01,1.80000000e+01,6.00000000e+01,5.00000000e+00,2.20000000e+01,1.80000000e+00
4,7.50000000e+01,1.10000000e+01,3.40000000e+01,9.00000000e+00,1.90000000e+01,1.90000000e+00
5,5.30000000e+01,3.50000000e+01,4.20000000e+01,6.00000000e+00,1.20000000e+01,1.50000000e+00
6,2.50000000e+01,2.00000000e+00,9.30000000e+01,1.70000000e+01,1.10000000e+01,1.60000000e+00
7,3.30000000e+01,2.60000000e+01,4.80000000e+01,3.00000000e+01,1.10000000e+01,1.80000000e+00
8,9.10000000e+01,9.00000000e+00,2.50000000e+01,1.20000000e+01,1.00000000e+01,1.60000000e+00
9,4.30000000e+01,1.40000000e+01,4.40000000e+01,2.00000000e+00,4.40000000e+01,1.90000000e+00
10,3.20000000e+01,5.00000000e+01,5.10000000e+01,4.00000000e+00,1.00000000e+01,2.00000000e+00
11,4.30000000e+01,2.50000000e+01,3.40000000e+01,3.40000000e+01,1.20000000e+01,1.70000000e+00
12,5.50000000e+01,8.00000000e+00,4.30000000e+01,3.40000000e+01,6.00000000e+00,1.80000000e+00
13,2.50000000e+01,2.00000000e+00,8.00000000e+01,1.80000000e+01,2.30000000e+01,1.30000000e+00
14,7.50000000e+01,1.70000000e+01,2.40000000e+01,2.40000000e+01,7.00000000e+00,1.70000000e+00
15,6.40000000e+01,4.70000000e+01,2.20000000e+01,1.10000000e+01,6.00000000e+00,1.90000000e+00
16,3.80000000e+01,1.00000000e+01,3.80000000e+01,1.20000000e+01,5.20000000e+01,1.40000000e+00
17,1.40000000e+01,4.00000000e+00,5.30000000e+01,2.60000000e+01,5.00000000e+01,1.90000000e+00
18,5.30000000e+01,4.60000000e+01,3.60000000e+01,4.00000000e+00,8.00000000e+00,1.40000000e+00
19,4.50000000e+01,1.00000000e+01,6.80000000e+01,8.00000000e+00,1.70000000e+01,2.00000000e+00
20,4.10000000e+01,6.00000000e+00,3.40000000e+01,3.00000000e+01,3.60000000e+01,1.80000000e+00
21,2.60000000e+01,0.00000000e+00,6.80000000e+01,1.30000000e+01,4.00000000e+01,1.60000000e+00
22,4.70000000e+01,2.20000000e+01,5.50000000e+01,1.60000000e+01,8.00000000e+00,1.90000000e+00
23,6.10000000e+01,1.00000000e+00,5.00000000e+01,2.10000000e+01,1.50000000e+01,1.90000000e+00
24,3.40000000e+01,4.50000000e+01,2.50000000e+01,4.20000000e+01,2.00000000e+00,1.40000000e+00
25,3.60000000e+01,4.70000000e+01,1.50000000e+01,1.50000000e+01,3.50000000e+01,2.00000000e+00
26,1.03000000e+02,8.00000000e+00,6.00000000e+00,1.30000000e+01,1.70000000e+01,1.90000000e+00
27,1.90000000e+01,0.00000000e+00,9.70000000e+01,2.00000000e+01,1.20000000e+01,1.90000000e+00
28,3.20000000e+01,4.10000000e+01,5.30000000e+01,1.80000000e+01,4.00000000e+00,2.00000000e+00
29,3.30000000e+01,1.60000000e+01,4.50000000e+01,4.80000000e+01,5.00000000e+00,1.80000000e+00
30,6.00000000e+01,1.50000000e+01,9.00000000e+00,3.90000000e+01,2.50000000e+01,2.00000000e+00
31,6.20000000e+01,8.00000000e+00,5.00000000e+00,4.20000000e+01,3.10000000e+01,1.60000000e+00
32,4.60000000e+01,3.20000000e+01,1.00000000e+01,2.50000000e+01,3.40000000e+01,1.60000000e+00
33,4.00000000e+01,3.70000000e+01,4.10000000e+01,1.80000000e+01,1.00000000e+01,1.90000000e+00
34,3.50000000e+01,7.00000000e+01,1.90000000e+01,1.50000000e+01,8.00000000e+00,1.30000000e+00
35,7.10000000e+01,1.50000000e+01,3.50000000e+01,7.00000000e+00,1.90000000e+01,1.30000000e+00
36,4.40000000e+01,2.50000000e+01,2.10000000e+01,2.10000000e+01,3.60000000e+01,2.00000000e+00
37,8.00000000e+00,1.60000000e+01,6.40000000e+01,5.30000000e+01,9.00000000e+00,1.60000000e+00
38,3.10000000e+01,1.00000000e+01,8.20000000e+01,1.20000000e+01,1.50000000e+01,1.50000000e+00
39,5.60000000e+01,3.60000000e+01,2.10000000e+01,2.20000000e+01,1.30000000e+01,1.70000000e+00
40,7.30000000e+01,2.40000000e+01,2.90000000e+01,1.60000000e+01,5.00000000e+00,1.60000000e+00
41,5.10000000e+01,3.00000000e+01,2.50000000e+01,1.00000000e+00,4.10000000e+01,1.70000000e+00
42,3.90000000e+01,2.50000000e+01,5.40000000e+01,8.00000000e+00,2.10000000e+01,1.40000000e+00
43,3.50000000e+01,1.00000000e+00,9.10000000e+01,1.80000000e+01,5.00000000e+00,2.00000000e+00
44,3.50000000e+01,1.00000000e+00,9.10000000e+01,1.80000000e+01,5.00000000e+00,2.00000000e+00
45,3.60000000e+01,9.00000000e+00,6.80000000e+01,9.00000000e+00,2.50000000e+01,1.60000000e+00
46,2.10000000e+01,2.00000000e+00,3.10000000e+01,8.00000000e+00,8.50000000e+01,1.90000000e+00
47,3.20000000e+01,1.50000000e+01,5.10000000e+01,2.10000000e+01,3.10000000e+01,1.70000000e+00
48,3.30000000e+01,4.70000000e+01,4.10000000e+01,5.00000000e+00,2.40000000e+01,1.70000000e+00
49,2.00000000e+01,6.50000000e+01,1.20000000e+01,3.20000000e+01,1.80000000e+01,1.70000000e+00
50,2.70000000e+01,3.40000000e+01,2.20000000e+01,1.00000000e+01,5.40000000e+01,1.30000000e+00

In [19]:
#columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
#cromosomas_decoded2['sum'] = cromosomas_decoded2[columnas_a_sumar].sum(axis=1) 
#cromosomas_decoded2

In [20]:
#from genes import decode_genes
#cromosomas_decoded2 = decode_genes(cromosomas_ok)
#cromosomas_decoded2

In [21]:
from mutation import one_gene_mutation
from crossover import normalize_chromosome

mutation_rate = 0.1
  
result = one_gene_mutation(cromosomas_ok2, mutation_rate)
cromosomas_okm = normalize_chromosome(result)

cromosomas_okm

    strength   agility expertise resistance      life height
1   01000011  00000010  00110111   00010011  00000101    010
2   00100110  00000000  01011010   00000001  00010100    111
3   01010011  00001111  00011010   00000101  00010100    100
4   00010001  00001110  01010110   00001010  00010101    111
5   00010111  00100010  01001011   00001010  00000111    011
6   01000101  00000010  00101011   00001111  00010011    010
7   01001000  00011001  00010001   00011011  00000111    111
8   00000011  00000001  01100110   00001101  00011100    011
9   00110010  00011000  00111010   00000110  00001010    111
10  00011101  00101011  00101010   00000001  00100001    110
11  00110101  00001000  00101001   00100000  00001110    101
12  00101101  00011010  00100100   00100100  00000101    100
13  00001111  00000010  01100010   00011010  00001000    100
14  01011111  00010010  00001100   00010010  00000101    000
15  00100010  00101100  00000010   00001100  00111000    001
16  01000101  00001100  00110100   00001010  00000101    110
17  00010100  00111011  00101100   00001101  00001100    001
18  01001110  00001011  00100010   00000011  00010111    110
19  00110011  00001011  00001111   00110110  00010000    111
20  00101100  00000111  00110010   00000110  00101001    101
21  00001001  00001100  01001100   00010001  00100010    010
22  00100100  00000000  00101100   00101110  00010101    111
23  00110011  00001011  00101100   00011100  00001110    101
24  00101000  00000110  00010111   00001001  01000110    010
25  00111010  00000101  00000100   00011010  00111000    110
26  00110111  00111100  00010011   00000101  00001001    111
27  00011000  00010101  01011001   00001000  00000101    111
28  01001111  00000000  00110001   00010010  00000010    110
29  00010001  00000101  00100001   00110101  00101000    111
30  01110001  00001101  00000110   00010000  00000000    101
31  01011111  00000011  00000010   00001101  00100011    011
32  00111001  00100111  00001100   00100010  00000101    011
33  00011100  00110100  00100100   00011010  00000111    000
34  00110100  00110110  00011001   00000101  00001101    110
35  00101100  00101010  00011101   00010011  00001101    101
36  00111101  00000010  00010110   00001111  00110000    010
37  00011010  00001111  00110111   00101011  00001001    010
38  00001001  00001001  01100100   00001111  00001111    011
39  01001001  00000111  00001111   00001000  00101101    101
40  00010110  00110100  00011010   00011100  00010100    011
41  00101110  00001001  00001111   01000110  00000111    001
42  01001010  00010101  00010110   00000011  00011100    100
43  00011111  00000000  01010010   00010000  00010010    111
44  00100001  00000000  01010110   00011000  00000100    111
45  00010101  00001001  00011101   00001000  01010010    010
46  00100111  00000001  01001000   00001010  00011010    111
47  00011100  00101000  00101010   00010010  00010100    100
48  00100110  00010001  00110011   00000101  00100101    100
49  00000011  00101001  00001100   00010101  01000111    100
50  00110000  00101111  00011011   00001101  00001100    000

In [22]:
from genes import decode_genes
cromosomas_decoded2m = decode_genes(cromosomas_okm)
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height
1,6.70000000e+01,2.00000000e+00,5.50000000e+01,1.90000000e+01,5.00000000e+00,1.50000000e+00
2,3.80000000e+01,0.00000000e+00,9.00000000e+01,1.00000000e+00,2.00000000e+01,2.00000000e+00
3,8.30000000e+01,1.50000000e+01,2.60000000e+01,5.00000000e+00,2.00000000e+01,1.70000000e+00
4,1.70000000e+01,1.40000000e+01,8.60000000e+01,1.00000000e+01,2.10000000e+01,2.00000000e+00
5,2.30000000e+01,3.40000000e+01,7.50000000e+01,1.00000000e+01,7.00000000e+00,1.60000000e+00
6,6.90000000e+01,2.00000000e+00,4.30000000e+01,1.50000000e+01,1.90000000e+01,1.50000000e+00
7,7.20000000e+01,2.50000000e+01,1.70000000e+01,2.70000000e+01,7.00000000e+00,2.00000000e+00
8,3.00000000e+00,1.00000000e+00,1.02000000e+02,1.30000000e+01,2.80000000e+01,1.60000000e+00
9,5.00000000e+01,2.40000000e+01,5.80000000e+01,6.00000000e+00,1.00000000e+01,2.00000000e+00
10,2.90000000e+01,4.30000000e+01,4.20000000e+01,1.00000000e+00,3.30000000e+01,1.90000000e+00
11,5.30000000e+01,8.00000000e+00,4.10000000e+01,3.20000000e+01,1.40000000e+01,1.80000000e+00
12,4.50000000e+01,2.60000000e+01,3.60000000e+01,3.60000000e+01,5.00000000e+00,1.70000000e+00
13,1.50000000e+01,2.00000000e+00,9.80000000e+01,2.60000000e+01,8.00000000e+00,1.70000000e+00
14,9.50000000e+01,1.80000000e+01,1.20000000e+01,1.80000000e+01,5.00000000e+00,1.30000000e+00
15,3.40000000e+01,4.40000000e+01,2.00000000e+00,1.20000000e+01,5.60000000e+01,1.40000000e+00
16,6.90000000e+01,1.20000000e+01,5.20000000e+01,1.00000000e+01,5.00000000e+00,1.90000000e+00
17,2.00000000e+01,5.90000000e+01,4.40000000e+01,1.30000000e+01,1.20000000e+01,1.40000000e+00
18,7.80000000e+01,1.10000000e+01,3.40000000e+01,3.00000000e+00,2.30000000e+01,1.90000000e+00
19,5.10000000e+01,1.10000000e+01,1.50000000e+01,5.40000000e+01,1.60000000e+01,2.00000000e+00
20,4.40000000e+01,7.00000000e+00,5.00000000e+01,6.00000000e+00,4.10000000e+01,1.80000000e+00
21,9.00000000e+00,1.20000000e+01,7.60000000e+01,1.70000000e+01,3.40000000e+01,1.50000000e+00
22,3.60000000e+01,0.00000000e+00,4.40000000e+01,4.60000000e+01,2.10000000e+01,2.00000000e+00
23,5.10000000e+01,1.10000000e+01,4.40000000e+01,2.80000000e+01,1.40000000e+01,1.80000000e+00
24,4.00000000e+01,6.00000000e+00,2.30000000e+01,9.00000000e+00,7.00000000e+01,1.50000000e+00
25,5.80000000e+01,5.00000000e+00,4.00000000e+00,2.60000000e+01,5.60000000e+01,1.90000000e+00
26,5.50000000e+01,6.00000000e+01,1.90000000e+01,5.00000000e+00,9.00000000e+00,2.00000000e+00
27,2.40000000e+01,2.10000000e+01,8.90000000e+01,8.00000000e+00,5.00000000e+00,2.00000000e+00
28,7.90000000e+01,0.00000000e+00,4.90000000e+01,1.80000000e+01,2.00000000e+00,1.90000000e+00
29,1.70000000e+01,5.00000000e+00,3.30000000e+01,5.30000000e+01,4.00000000e+01,2.00000000e+00
30,1.13000000e+02,1.30000000e+01,6.00000000e+00,1.60000000e+01,0.00000000e+00,1.80000000e+00
31,9.50000000e+01,3.00000000e+00,2.00000000e+00,1.30000000e+01,3.50000000e+01,1.60000000e+00
32,5.70000000e+01,3.90000000e+01,1.20000000e+01,3.40000000e+01,5.00000000e+00,1.60000000e+00
33,2.80000000e+01,5.20000000e+01,3.60000000e+01,2.60000000e+01,7.00000000e+00,1.30000000e+00
34,5.20000000e+01,5.40000000e+01,2.50000000e+01,5.00000000e+00,1.30000000e+01,1.90000000e+00
35,4.40000000e+01,4.20000000e+01,2.90000000e+01,1.90000000e+01,1.30000000e+01,1.80000000e+00
36,6.10000000e+01,2.00000000e+00,2.20000000e+01,1.50000000e+01,4.80000000e+01,1.50000000e+00
37,2.60000000e+01,1.50000000e+01,5.50000000e+01,4.30000000e+01,9.00000000e+00,1.50000000e+00
38,9.00000000e+00,9.00000000e+00,1.00000000e+02,1.50000000e+01,1.50000000e+01,1.60000000e+00
39,7.30000000e+01,7.00000000e+00,1.50000000e+01,8.00000000e+00,4.50000000e+01,1.80000000e+00
40,2.20000000e+01,5.20000000e+01,2.60000000e+01,2.80000000e+01,2.00000000e+01,1.60000000e+00
41,4.60000000e+01,9.00000000e+00,1.50000000e+01,7.00000000e+01,7.00000000e+00,1.40000000e+00
42,7.40000000e+01,2.10000000e+01,2.20000000e+01,3.00000000e+00,2.80000000e+01,1.70000000e+00
43,3.10000000e+01,0.00000000e+00,8.20000000e+01,1.60000000e+01,1.80000000e+01,2.00000000e+00
44,3.30000000e+01,0.00000000e+00,8.60000000e+01,2.40000000e+01,4.00000000e+00,2.00000000e+00
45,2.10000000e+01,9.00000000e+00,2.90000000e+01,8.00000000e+00,8.20000000e+01,1.50000000e+00
46,3.90000000e+01,1.00000000e+00,7.20000000e+01,1.00000000e+01,2.60000000e+01,2.00000000e+00
47,2.80000000e+01,4.00000000e+01,4.20000000e+01,1.80000000e+01,2.00000000e+01,1.70000000e+00
48,3.80000000e+01,1.70000000e+01,5.10000000e+01,5.00000000e+00,3.70000000e+01,1.70000000e+00
49,3.00000000e+00,4.10000000e+01,1.20000000e+01,2.10000000e+01,7.10000000e+01,1.70000000e+00
50,4.80000000e+01,4.70000000e+01,2.70000000e+01,1.30000000e+01,1.20000000e+01,1.30000000e+00

In [23]:
columnas_a_sumar = ['strength', 'agility', 'expertise', 'resistance', 'life']
cromosomas_decoded2m['sum'] = cromosomas_decoded2m[columnas_a_sumar].sum(axis=1) 
cromosomas_decoded2m

,strength,agility,expertise,resistance,life,height,sum
1,6.70000000e+01,2.00000000e+00,5.50000000e+01,1.90000000e+01,5.00000000e+00,1.50000000e+00,1.48000000e+02
2,3.80000000e+01,0.00000000e+00,9.00000000e+01,1.00000000e+00,2.00000000e+01,2.00000000e+00,1.49000000e+02
3,8.30000000e+01,1.50000000e+01,2.60000000e+01,5.00000000e+00,2.00000000e+01,1.70000000e+00,1.49000000e+02
4,1.70000000e+01,1.40000000e+01,8.60000000e+01,1.00000000e+01,2.10000000e+01,2.00000000e+00,1.48000000e+02
5,2.30000000e+01,3.40000000e+01,7.50000000e+01,1.00000000e+01,7.00000000e+00,1.60000000e+00,1.49000000e+02
6,6.90000000e+01,2.00000000e+00,4.30000000e+01,1.50000000e+01,1.90000000e+01,1.50000000e+00,1.48000000e+02
7,7.20000000e+01,2.50000000e+01,1.70000000e+01,2.70000000e+01,7.00000000e+00,2.00000000e+00,1.48000000e+02
8,3.00000000e+00,1.00000000e+00,1.02000000e+02,1.30000000e+01,2.80000000e+01,1.60000000e+00,1.47000000e+02
9,5.00000000e+01,2.40000000e+01,5.80000000e+01,6.00000000e+00,1.00000000e+01,2.00000000e+00,1.48000000e+02
10,2.90000000e+01,4.30000000e+01,4.20000000e+01,1.00000000e+00,3.30000000e+01,1.90000000e+00,1.48000000e+02
11,5.30000000e+01,8.00000000e+00,4.10000000e+01,3.20000000e+01,1.40000000e+01,1.80000000e+00,1.48000000e+02
12,4.50000000e+01,2.60000000e+01,3.60000000e+01,3.60000000e+01,5.00000000e+00,1.70000000e+00,1.48000000e+02
13,1.50000000e+01,2.00000000e+00,9.80000000e+01,2.60000000e+01,8.00000000e+00,1.70000000e+00,1.49000000e+02
14,9.50000000e+01,1.80000000e+01,1.20000000e+01,1.80000000e+01,5.00000000e+00,1.30000000e+00,1.48000000e+02
15,3.40000000e+01,4.40000000e+01,2.00000000e+00,1.20000000e+01,5.60000000e+01,1.40000000e+00,1.48000000e+02
16,6.90000000e+01,1.20000000e+01,5.20000000e+01,1.00000000e+01,5.00000000e+00,1.90000000e+00,1.48000000e+02
17,2.00000000e+01,5.90000000e+01,4.40000000e+01,1.30000000e+01,1.20000000e+01,1.40000000e+00,1.48000000e+02
18,7.80000000e+01,1.10000000e+01,3.40000000e+01,3.00000000e+00,2.30000000e+01,1.90000000e+00,1.49000000e+02
19,5.10000000e+01,1.10000000e+01,1.50000000e+01,5.40000000e+01,1.60000000e+01,2.00000000e+00,1.47000000e+02
20,4.40000000e+01,7.00000000e+00,5.00000000e+01,6.00000000e+00,4.10000000e+01,1.80000000e+00,1.48000000e+02
21,9.00000000e+00,1.20000000e+01,7.60000000e+01,1.70000000e+01,3.40000000e+01,1.50000000e+00,1.48000000e+02
22,3.60000000e+01,0.00000000e+00,4.40000000e+01,4.60000000e+01,2.10000000e+01,2.00000000e+00,1.47000000e+02
23,5.10000000e+01,1.10000000e+01,4.40000000e+01,2.80000000e+01,1.40000000e+01,1.80000000e+00,1.48000000e+02
24,4.00000000e+01,6.00000000e+00,2.30000000e+01,9.00000000e+00,7.00000000e+01,1.50000000e+00,1.48000000e+02
25,5.80000000e+01,5.00000000e+00,4.00000000e+00,2.60000000e+01,5.60000000e+01,1.90000000e+00,1.49000000e+02
26,5.50000000e+01,6.00000000e+01,1.90000000e+01,5.00000000e+00,9.00000000e+00,2.00000000e+00,1.48000000e+02
27,2.40000000e+01,2.10000000e+01,8.90000000e+01,8.00000000e+00,5.00000000e+00,2.00000000e+00,1.47000000e+02
28,7.90000000e+01,0.00000000e+00,4.90000000e+01,1.80000000e+01,2.00000000e+00,1.90000000e+00,1.48000000e+02
29,1.70000000e+01,5.00000000e+00,3.30000000e+01,5.30000000e+01,4.00000000e+01,2.00000000e+00,1.48000000e+02
30,1.13000000e+02,1.30000000e+01,6.00000000e+00,1.60000000e+01,0.00000000e+00,1.80000000e+00,1.48000000e+02
31,9.50000000e+01,3.00000000e+00,2.00000000e+00,1.30000000e+01,3.50000000e+01,1.60000000e+00,1.48000000e+02
32,5.70000000e+01,3.90000000e+01,1.20000000e+01,3.40000000e+01,5.00000000e+00,1.60000000e+00,1.47000000e+02
33,2.80000000e+01,5.20000000e+01,3.60000000e+01,2.60000000e+01,7.00000000e+00,1.30000000e+00,1.49000000e+02
34,5.20000000e+01,5.40000000e+01,2.50000000e+01,5.00000000e+00,1.30000000e+01,1.90000000e+00,1.49000000e+02
35,4.40000000e+01,4.20000000e+01,2.90000000e+01,1.90000000e+01,1.30000000e+01,1.80000000e+00,1.47000000e+02
36,6.10000000e+01,2.00000000e+00,2.20000000e+01,1.50000000e+01,4.80000000e+01,1.50000000e+00,1.48000000e+02
37,2.60000000e+01,1.50000000e+01,5.50000000e+01,4.30000000e+01,9.00000000e+00,1.50000000e+00,1.48000000e+02
38,9.00000000e+00,9.00000000e+00,1.00000000e+02,1.50000000e+01,1.50000000e+01,1.60000000e+00,1.48000000e+02
39,7.30000000e+01,7.00000000e+00,1.50000000e+01,8.00000000e+00,4.50000000e+01,1.80000000e+00,1.48000000e+02
40,2.20000000e+01,5.20000000e+01,2.60000000e+01,2.80000000e+01,2.00000000e+01,1.60000000e+00,1.48000000e+02
41,4.60000000e+01,9.00000000e+00,1.50000000e+01,7.00000000e+01,7.00000000e+00,1.40000000e+00,1.47000000e+02
42,7.40000000e+01,2.10000000e+01,2.20000000e+01,3.00000000e+00,2.80000000e+01,1.70000000e+00,1.48000000e+02
43,3.10000000e+01,0.00000000e+00,8.20000000e+01,1.60000000e+01,1.80000000e+01,2.00000000e+00,1.47000000e+02
44,3.30000000e+01,0.00000000e+00,8.60000000e+01,2.40000000e+01,4.00000000e+00,2.00000000e+00,1.47000000e+02
45,2.10000000e+01,9.00000000e+00,2.90000000e+01,8.00000000e+00,8.20000000e+01,1.50000000e+00,1.49000000e+02
46,3.90000000e+01,1.00000000e+00,7.20000000e+01,1.00000000e+01,2.60000000e+01,2.00000000e+00,1.48000000e+02
47,2.80000000e+01,4.00000000e+01,4.20000000e+01,1.80000000e+01,2.00000000e+01,1.70000000e+00,1.48000000e+02
48,3.80000000e+01,1.70000000e+01,5.10000000e+01,5.00000000e+00,3.70000000e+01,1.70000000e+00,1.48000000e+02
49,3.00000000e+00,4.10000000e+01,1.20000000e+01,2.10000000e+01,7.10000000e+01,1.70000000e+00,1.48000000e+02
50,4.80000000e+01,4.70000000e+01,2.70000000e+01,1.30000000e+01,1.20000000e+01,1.30000000e+00,1.47000000e+02

In [24]:
from mutation import multi_gene_mutation

# Ejemplo de uso:
mutation_rate = 0.8
resultmp = multi_gene_mutation(cromosomas_ok1, mutation_rate)
resultmp

    strength   agility expertise resistance      life height
0   01001100  00000011  00111110   00000010  00000101    011
1   00100001  00000000  01010000   00010000  00010010    110
2   00101010  00010010  00111100   00000101  00010110    101
3   01001011  00001011  00100010   00001001  00010011    110
4   00110101  00100011  00101010   00000110  00001100    010
5   00011001  00000010  01011101   00010001  00001011    011
6   00100001  00011010  00110000   00011110  00001011    101
7   01011011  00001001  00011001   00001100  00001010    011
8   00101011  00001110  00101100   00000010  00101100    110
9   00100000  00110010  00110011   00000100  00001010    111
10  00101011  00011001  00100010   00100010  00001100    100
11  00110111  00001000  00101011   00100010  00000110    101
12  00011001  00000010  01010000   00010010  00010111    000
13  01001011  00010001  00011000   00011000  00000111    100
14  01000000  00101111  00010110   00001011  00000110    110
15  00100110  00001010  00100110   00001100  00110100    001
16  00001110  00000100  00110101   00011010  00110010    110
17  00110101  00101110  00100100   00000100  00001000    001
18  00101101  00001010  01000100   00001000  00010001    111
19  00101001  00000110  00100010   00011110  00100100    101
20  00011010  00000000  01000100   00001101  00101000    011
21  00101111  00010110  00110111   00010000  00001000    110
22  00111101  00000001  00110010   00010101  00001111    110
23  00100010  00101101  00011001   00101010  00000010    001
24  00100100  00101111  00001111   00001111  00100011    111
25  01100111  00001000  00000110   00001101  00010001    110
26  00010011  00000000  01100001   00010100  00001100    110
27  00100000  00101001  00110101   00010010  00000100    111
28  00100001  00010000  00101101   00110000  00000101    101
29  00111100  00001111  00001001   00100111  00011001    111
30  00111110  00001000  00000101   00101010  00011111    011
31  00101110  00100000  00001010   00011001  00100010    011
32  00101000  00100101  00101001   00010010  00001010    110
33  00100011  01000110  00010011   00001111  00001000    000
34  01000111  00001111  00100011   00000111  00010011    000
35  00101100  00011001  00010101   00010101  00100100    111
36  00001000  00010000  01000000   00110101  00001001    011
37  00011111  00001010  01010010   00001100  00001111    010
38  00111000  00100100  00010101   00010110  00001101    100
39  01001001  00011000  00011101   00010000  00000101    011
40  00110011  00011110  00011001   00000001  00101001    100
41  00100111  00011001  00110110   00001000  00010101    001
42  00100011  00000001  01011011   00010010  00000101    111
43  00100011  00000001  01011011   00010010  00000101    111
44  00100100  00001001  01000100   00001001  00011001    011
45  00010101  00000010  00011111   00001000  01010101    110
46  00100000  00001111  00110011   00010101  00011111    100
47  00100001  00101111  00101001   00000101  00011000    100
48  00010100  01000001  00001100   00100000  00010010    100
49  00011011  00100010  00010110   00001010  00110110    000

    strength   agility expertise resistance      life height
0   10110011  00000011  11000001   11111100  00000101    011
1   01011110  00000000  10001110   11101101  01111101    111
2   00101010  11101000  00111100   11011110  10011000    110
3   10111111  10110101  11010111   11110010  10001110    000
4   00110101  00100011  11110001   11110001  11110001    010
5   00011001  01011101  10110010   11100110  01110100    011
6   10010100  11100011  01001011   11100001  11110100    110
7   10100110  10110110  01100110   11100011  11101111    100
8   11001010  00001110  10110001   11011000  01110001    110
9   11111111  01100101  11010111   00000100  00001010    000
10  11011111  00011001  10011100   10011001  11111010    100
11  10011101  00001000  01010001   11111100  00000110    101
12  11100010  00000010  00100111   01110101  11111001    110
13  01001011  10111110  00011000   01100111  11111001    011
14  11111111  11010000  01001001   00001011  11111101    001
15  00100110  00110100  11010100   00001100  01011011    111
16  11110001  00101010  10001110   11100101  11011101    110
17  00110101  11000000  00100100   11111011  00001000    110
18  00010011  10110111  00011011   11111111  01101110    111
19  10010110  01110001  11010101   10000011  00100100    010
20  10101101  01011111  10011111   01100010  11110011    100
21  01010000  10100011  10101000   01001001  00100011    101
22  11000100  11100110  11001101   10101010  11010000    110
23  11011101  11110010  11110110   00101010  00000010    010
24  01011011  10010000  00001111   11110000  00100011    111
25  01100111  00001000  00110001   10001000  10101110    101
26  11111100  10111111  10111110   01101011  00001100    001
27  10011111  10010110  11001010   01111100  11111011    000
28  10011110  01101111  01010010   10001111  11110010    000
29  11100110  10010000  00110110   00100111  10111010    000
30  01001001  11011111  11111001   11000101  10110000    100
31  00101110  01010101  11000101   11100110  11001100    101
32  00101000  11101010  01010110   00010010  11110101    101
33  10001101  01000110  11101000   11001001  01110011    000
34  10111100  11111010  10011101   00000111  01101110    000
35  11011111  00011001  11110010   11101000  11110010    000
36  11100111  01100011  01000000   11101110  10101101    011
37  11101000  01100101  01010010   10111010  01110100    101
38  11001011  00100100  10011011   10101001  01111001    100
39  00110111  11110011  11000110   00010000  10111010    000
40  11001100  11100101  11110110   11010100  11010010    001
41  11111011  00011001  10011101   11111111  11101001    111
42  11010100  00000001  11100100   11100101  11111011    000
43  00100011  10111010  10010101   01101101  11111010    000
44  00100100  01110010  10111011   00001001  11111110    100
45  01001111  00111011  11100101   00001000  10001010    000
46  10101110  11010000  01100010   11101001  10100100    101
47  10011110  01010000  11010111   11111010  01100100    011
48  00010100  01000001  11110011   01011111  11101100    010
49  00011011  11011101  00010110   00001010  11000000    000

In [25]:
from mutation import multi_gene_mutation_uniform

# Ejemplo de uso:
mutation_rate = 0.7
resultmu = multi_gene_mutation_uniform(cromosomas_ok1, mutation_rate)
resultmu

    strength   agility expertise resistance      life height
0   01001100  00000011  00111110   00000010  00000101    011
1   00100001  00000000  01010000   00010000  00010010    110
2   00101010  00010010  00111100   00000101  00010110    101
3   01001011  00001011  00100010   00001001  00010011    110
4   00110101  00100011  00101010   00000110  00001100    010
5   00011001  00000010  01011101   00010001  00001011    011
6   00100001  00011010  00110000   00011110  00001011    101
7   01011011  00001001  00011001   00001100  00001010    011
8   00101011  00001110  00101100   00000010  00101100    110
9   00100000  00110010  00110011   00000100  00001010    111
10  00101011  00011001  00100010   00100010  00001100    100
11  00110111  00001000  00101011   00100010  00000110    101
12  00011001  00000010  01010000   00010010  00010111    000
13  01001011  00010001  00011000   00011000  00000111    100
14  01000000  00101111  00010110   00001011  00000110    110
15  00100110  00001010  00100110   00001100  00110100    001
16  00001110  00000100  00110101   00011010  00110010    110
17  00110101  00101110  00100100   00000100  00001000    001
18  00101101  00001010  01000100   00001000  00010001    111
19  00101001  00000110  00100010   00011110  00100100    101
20  00011010  00000000  01000100   00001101  00101000    011
21  00101111  00010110  00110111   00010000  00001000    110
22  00111101  00000001  00110010   00010101  00001111    110
23  00100010  00101101  00011001   00101010  00000010    001
24  00100100  00101111  00001111   00001111  00100011    111
25  01100111  00001000  00000110   00001101  00010001    110
26  00010011  00000000  01100001   00010100  00001100    110
27  00100000  00101001  00110101   00010010  00000100    111
28  00100001  00010000  00101101   00110000  00000101    101
29  00111100  00001111  00001001   00100111  00011001    111
30  00111110  00001000  00000101   00101010  00011111    011
31  00101110  00100000  00001010   00011001  00100010    011
32  00101000  00100101  00101001   00010010  00001010    110
33  00100011  01000110  00010011   00001111  00001000    000
34  01000111  00001111  00100011   00000111  00010011    000
35  00101100  00011001  00010101   00010101  00100100    111
36  00001000  00010000  01000000   00110101  00001001    011
37  00011111  00001010  01010010   00001100  00001111    010
38  00111000  00100100  00010101   00010110  00001101    100
39  01001001  00011000  00011101   00010000  00000101    011
40  00110011  00011110  00011001   00000001  00101001    100
41  00100111  00011001  00110110   00001000  00010101    001
42  00100011  00000001  01011011   00010010  00000101    111
43  00100011  00000001  01011011   00010010  00000101    111
44  00100100  00001001  01000100   00001001  00011001    011
45  00010101  00000010  00011111   00001000  01010101    110
46  00100000  00001111  00110011   00010101  00011111    100
47  00100001  00101111  00101001   00000101  00011000    100
48  00010100  01000001  00001100   00100000  00010010    100
49  00011011  00100010  00010110   00001010  00110110    000

    strength   agility expertise resistance      life height
0   10110011  11111100  11000001   11111101  00000101    100
1   11011110  11111111  01010000   00010000  00010010    001
2   00101010  00010010  11000011   11111010  11101001    010
3   01001011  11110100  11011101   11110110  11101100    110
4   11001010  11011100  11010101   11111001  11110011    010
5   11100110  00000010  10100010   11101110  11110100    011
6   00100001  00011010  00110000   00011110  11110100    010
7   10100100  11110110  11100110   00001100  11110101    100
8   11010100  11110001  11010011   11111101  11010011    110
9   11011111  11001101  11001100   11111011  11110101    000
10  11010100  11100110  11011101   00100010  00001100    011
11  11001000  11110111  11010100   11011101  00000110    010
12  11100110  11111101  10101111   11101101  00010111    000
13  10110100  11101110  11100111   11100111  00000111    011
14  10111111  00101111  00010110   11110100  00000110    110
15  11011001  00001010  00100110   00001100  00110100    001
16  11110001  00000100  11001010   00011010  11001101    001
17  11001010  00101110  11011011   11111011  11110111    001
18  11010010  11110101  01000100   11110111  11101110    000
19  00101001  11111001  11011101   11100001  11011011    010
20  11100101  11111111  01000100   11110010  11010111    100
21  00101111  11101001  11001000   11101111  11110111    110
22  11000010  11111110  00110010   11101010  11110000    001
23  11011101  00101101  11100110   11010101  11111101    001
24  11011011  11010000  11110000   00001111  00100011    111
25  10011000  11110111  11111001   11110010  11101110    001
26  11101100  11111111  10011110   11101011  11110011    001
27  11011111  11010110  00110101   11101101  00000100    000
28  11011110  00010000  11010010   00110000  11111010    010
29  11000011  00001111  00001001   11011000  11100110    000
30  11000001  00001000  00000101   11010101  11100000    100
31  11010001  11011111  11110101   00011001  00100010    100
32  11010111  00100101  00101001   00010010  00001010    110
33  11011100  10111001  00010011   11110000  11110111    111
34  01000111  11110000  00100011   11111000  11101100    111
35  11010011  00011001  11101010   00010101  11011011    000
36  11110111  00010000  10111111   00110101  00001001    100
37  11100000  00001010  10101101   11110011  00001111    101
38  11000111  11011011  11101010   11101001  11110010    011
39  10110110  11100111  11100010   00010000  00000101    100
40  11001100  00011110  00011001   11111110  11010110    011
41  11011000  00011001  11001001   11110111  11101010    001
42  11011100  11111110  10100100   11101101  11111010    000
43  11011100  00000001  01011011   11101101  11111010    000
44  00100100  11110110  10111011   11110110  00011001    100
45  00010101  00000010  00011111   11110111  10101010    001
46  00100000  11110000  11001100   11101010  11100000    100
47  00100001  11010000  11010110   11111010  11100111    011
48  11101011  10111110  11110011   11011111  11101101    100
49  11100100  11011101  11101001   11110101  00110110    111

In [26]:
from population import eval_performace

new_generation = eval_performace(cromosomas_decoded2,type)
new_generation

,strength,agility,expertise,resistance,life,height,characterType,performance
1,7.60000000e+01,3.00000000e+00,6.20000000e+01,2.00000000e+00,5.00000000e+00,1.60000000e+00,CharacterType.ARCHER,1.12594372e+03
23,6.10000000e+01,1.00000000e+00,5.00000000e+01,2.10000000e+01,1.50000000e+01,1.90000000e+00,CharacterType.ARCHER,8.48428137e+02
19,4.50000000e+01,1.00000000e+01,6.80000000e+01,8.00000000e+00,1.70000000e+01,2.00000000e+00,CharacterType.ARCHER,8.37396445e+02
44,3.50000000e+01,1.00000000e+00,9.10000000e+01,1.80000000e+01,5.00000000e+00,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
43,3.50000000e+01,1.00000000e+00,9.10000000e+01,1.80000000e+01,5.00000000e+00,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
22,4.70000000e+01,2.20000000e+01,5.50000000e+01,1.60000000e+01,8.00000000e+00,1.90000000e+00,CharacterType.ARCHER,7.89257593e+02
3,4.20000000e+01,1.80000000e+01,6.00000000e+01,5.00000000e+00,2.20000000e+01,1.80000000e+00,CharacterType.ARCHER,7.39865366e+02
4,7.50000000e+01,1.10000000e+01,3.40000000e+01,9.00000000e+00,1.90000000e+01,1.90000000e+00,CharacterType.ARCHER,7.38277169e+02
2,3.30000000e+01,0.00000000e+00,8.00000000e+01,1.60000000e+01,1.80000000e+01,1.90000000e+00,CharacterType.ARCHER,7.14025275e+02
5,5.30000000e+01,3.50000000e+01,4.20000000e+01,6.00000000e+00,1.20000000e+01,1.50000000e+00,CharacterType.ARCHER,7.08069875e+02
12,5.50000000e+01,8.00000000e+00,4.30000000e+01,3.40000000e+01,6.00000000e+00,1.80000000e+00,CharacterType.ARCHER,6.84369165e+02
38,3.10000000e+01,1.00000000e+01,8.20000000e+01,1.20000000e+01,1.50000000e+01,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02
45,3.60000000e+01,9.00000000e+00,6.80000000e+01,9.00000000e+00,2.50000000e+01,1.60000000e+00,CharacterType.ARCHER,6.70425304e+02
18,5.30000000e+01,4.60000000e+01,3.60000000e+01,4.00000000e+00,8.00000000e+00,1.40000000e+00,CharacterType.ARCHER,6.49820635e+02
35,7.10000000e+01,1.50000000e+01,3.50000000e+01,7.00000000e+00,1.90000000e+01,1.30000000e+00,CharacterType.ARCHER,6.48983055e+02
42,3.90000000e+01,2.50000000e+01,5.40000000e+01,8.00000000e+00,2.10000000e+01,1.40000000e+00,CharacterType.ARCHER,6.41555550e+02
40,7.30000000e+01,2.40000000e+01,2.90000000e+01,1.60000000e+01,5.00000000e+00,1.60000000e+00,CharacterType.ARCHER,6.32388690e+02
9,4.30000000e+01,1.40000000e+01,4.40000000e+01,2.00000000e+00,4.40000000e+01,1.90000000e+00,CharacterType.ARCHER,6.01050991e+02
8,9.10000000e+01,9.00000000e+00,2.50000000e+01,1.20000000e+01,1.00000000e+01,1.60000000e+00,CharacterType.ARCHER,5.92683179e+02
6,2.50000000e+01,2.00000000e+00,9.30000000e+01,1.70000000e+01,1.10000000e+01,1.60000000e+00,CharacterType.ARCHER,5.72504703e+02
33,4.00000000e+01,3.70000000e+01,4.10000000e+01,1.80000000e+01,1.00000000e+01,1.90000000e+00,CharacterType.ARCHER,5.71205963e+02
28,3.20000000e+01,4.10000000e+01,5.30000000e+01,1.80000000e+01,4.00000000e+00,2.00000000e+00,CharacterType.ARCHER,5.52903714e+02
10,3.20000000e+01,5.00000000e+01,5.10000000e+01,4.00000000e+00,1.00000000e+01,2.00000000e+00,CharacterType.ARCHER,5.51347708e+02
15,6.40000000e+01,4.70000000e+01,2.20000000e+01,1.10000000e+01,6.00000000e+00,1.90000000e+00,CharacterType.ARCHER,5.48290220e+02
14,7.50000000e+01,1.70000000e+01,2.40000000e+01,2.40000000e+01,7.00000000e+00,1.70000000e+00,CharacterType.ARCHER,5.31023028e+02
7,3.30000000e+01,2.60000000e+01,4.80000000e+01,3.00000000e+01,1.10000000e+01,1.80000000e+00,CharacterType.ARCHER,5.10297593e+02
47,3.20000000e+01,1.50000000e+01,5.10000000e+01,2.10000000e+01,3.10000000e+01,1.70000000e+00,CharacterType.ARCHER,4.94927982e+02
13,2.50000000e+01,2.00000000e+00,8.00000000e+01,1.80000000e+01,2.30000000e+01,1.30000000e+00,CharacterType.ARCHER,4.91353407e+02
21,2.60000000e+01,0.00000000e+00,6.80000000e+01,1.30000000e+01,4.00000000e+01,1.60000000e+00,CharacterType.ARCHER,4.90471404e+02
11,4.30000000e+01,2.50000000e+01,3.40000000e+01,3.40000000e+01,1.20000000e+01,1.70000000e+00,CharacterType.ARCHER,4.75490662e+02
27,1.90000000e+01,0.00000000e+00,9.70000000e+01,2.00000000e+01,1.20000000e+01,1.90000000e+00,CharacterType.ARCHER,4.75089772e+02
48,3.30000000e+01,4.70000000e+01,4.10000000e+01,5.00000000e+00,2.40000000e+01,1.70000000e+00,CharacterType.ARCHER,4.71548550e+02
29,3.30000000e+01,1.60000000e+01,4.50000000e+01,4.80000000e+01,5.00000000e+00,1.80000000e+00,CharacterType.ARCHER,4.66779763e+02
16,3.80000000e+01,1.00000000e+01,3.80000000e+01,1.20000000e+01,5.20000000e+01,1.40000000e+00,CharacterType.ARCHER,4.52323723e+02
41,5.10000000e+01,3.00000000e+01,2.50000000e+01,1.00000000e+00,4.10000000e+01,1.70000000e+00,CharacterType.ARCHER,4.42964061e+02
20,4.10000000e+01,6.00000000e+00,3.40000000e+01,3.00000000e+01,3.60000000e+01,1.80000000e+00,CharacterType.ARCHER,4.34707293e+02
39,5.60000000e+01,3.60000000e+01,2.10000000e+01,2.20000000e+01,1.30000000e+01,1.70000000e+00,CharacterType.ARCHER,4.27314439e+02
36,4.40000000e+01,2.50000000e+01,2.10000000e+01,2.10000000e+01,3.60000000e+01,2.00000000e+00,CharacterType.ARCHER,3.37086490e+02
24,3.40000000e+01,4.50000000e+01,2.50000000e+01,4.20000000e+01,2.00000000e+00,1.40000000e+00,CharacterType.ARCHER,3.30992274e+02
34,3.50000000e+01,7.00000000e+01,1.90000000e+01,1.50000000e+01,8.00000000e+00,1.30000000e+00,CharacterType.ARCHER,2.84374299e+02
25,3.60000000e+01,4.70000000e+01,1.50000000e+01,1.50000000e+01,3.50000000e+01,2.00000000e+00,CharacterType.ARCHER,2.51719807e+02
17,1.40000000e+01,4.00000000e+00,5.30000000e+01,2.60000000e+01,5.00000000e+01,1.90000000e+00,CharacterType.ARCHER,2.40840313e+02
46,2.10000000e+01,2.00000000e+00,3.10000000e+01,8.00000000e+00,8.50000000e+01,1.90000000e+00,CharacterType.ARCHER,2.20894614e+02
50,2.70000000e+01,3.40000000e+01,2.20000000e+01,1.00000000e+01,5.40000000e+01,1.30000000e+00,CharacterType.ARCHER,2.19304206e+02
32,4.60000000e+01,3.20000000e+01,1.00000000e+01,2.50000000e+01,3.40000000e+01,1.60000000e+00,CharacterType.ARCHER,2.08296063e+02
30,6.00000000e+01,1.50000000e+01,9.00000000e+00,3.90000000e+01,2.50000000e+01,2.00000000e+00,CharacterType.ARCHER,2.01588388e+02
26,1.03000000e+02,8.00000000e+00,6.00000000e+00,1.30000000e+01,1.70000000e+01,1.90000000e+00,CharacterType.ARCHER,1.90405691e+02
37,8.00000000e+00,1.60000000e+01,6.40000000e+01,5.30000000e+01,9.00000000e+00,1.60000000e+00,CharacterType.ARCHER,1.52869935e+02
49,2.00000000e+01,6.50000000e+01,1.20000000e+01,3.20000000e+01,1.80000000e+01,1.70000000e+00,CharacterType.ARCHER,1.36180594e+02
31,6.20000000e+01,8.00000000e+00,5.00000000e+00,4.20000000e+01,3.10000000e+01,1.60000000e+00,CharacterType.ARCHER,1.12355247e+02

In [27]:
import numpy as np
from selection import boltzmann_selection

# Example usage:

max_generation = 500
generation = 1
k = K                                  # Number of desired selected individuals.
T_0 = 20                                # Initial temperature.
T_offset = 5                          # Offset value for temperature exponential function.
reference_generation = max_generation   # Reference generation where 0 < (T_0 - T_offset) = 0.015 = deltaT is desired.
deltaT = 0.015                          # 0 < (T_0 - T_offset) = deltaT at reference generation.
m = - (np.log(deltaT) - np.log(T_0 - T_offset)) / reference_generation

new_boltzmann_selection = boltzmann_selection(poblacion_inicial,k,generation,T_0,T_offset,m)

new_boltzmann_selection

sum: 100.0
    strength  agility  expertise  resistance  life         height  \
10        70        2         54           3    21 1.50000000e+00
95        35        1         91          18     5 2.00000000e+00
19        39       11         65           9    26 1.90000000e+00
43        77       19         32           6    16 1.80000000e+00
87        53       34         44          10     9 1.60000000e+00
..       ...      ...        ...         ...   ...            ...
33         2       99         15          19    15 1.80000000e+00
91         3       53          8           6    80 1.70000000e+00
5         16       13          1          89    31 1.60000000e+00
30         2       99          2           2    45 1.80000000e+00
4          7        2          3           3   135 1.80000000e+00

           characterType    performance  performance_relative  \
10  CharacterType.ARCHER 9.99859918e+01        9.99859918e-01
95  CharacterType.ARCHER 1.22320125e-02        1.22320125e-04
19  CharacterType.ARCHER 1.00941296e-03        1.00941296e-05
43  CharacterType.ARCHER 3.81590602e-04        3.81590602e-06
87  CharacterType.ARCHER 3.42185478e-04        3.42185478e-06
..                   ...            ...                   ...
33  CharacterType.ARCHER 1.52047527e-19        1.52047527e-21
91  CharacterType.ARCHER 1.50914223e-19        1.50914223e-21
5   CharacterType.ARCHER 1.44476191e-19        1.44476191e-21
30  CharacterType.ARCHER 9.46500196e-20        9.46500196e-22
4   CharacterType.ARCHER 9.11859992e-20        9.11859992e-22

    performance_accumulated
10           9.99859918e-01
95           9.99982238e-01
19           9.99992332e-01
43           9.99996148e-01
87           9.99999570e-01
..                      ...
33           1.00000000e+00
91           1.00000000e+00
5            1.00000000e+00
30           1.00000000e+00
4            1.00000000e+00

[100 rows x 10 columns]

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
1,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
2,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
3,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
4,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
5,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
6,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
7,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
8,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
9,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
10,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
11,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
12,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
13,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
14,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
15,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
16,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
17,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
18,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
19,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
20,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
21,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
22,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
23,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
24,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
25,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
26,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
27,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
28,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
29,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
30,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
31,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
32,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
33,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
34,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
35,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
36,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
37,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
38,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
39,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
40,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
41,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
42,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
43,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
44,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
45,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
46,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
47,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
48,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01
49,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.99859918e+01,9.99859918e-01,9.99859918e-01

In [28]:
from selection import deterministic_tournament_selection 

individualsT = deterministic_tournament_selection(poblacion_inicial, 10, k)
individualsT

c:\Users\dpenaloza\Downloads\SIA\sia-tp2\src\selection.py:196: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  individuals = pd.concat([individuals, winner])

,strength,agility,expertise,resistance,life,height,characterType,performance
0,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
1,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
2,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
3,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
4,16,14,84,14,22,1.40000000e+00,CharacterType.ARCHER,3.70060598e+02
5,16,14,84,14,22,1.40000000e+00,CharacterType.ARCHER,3.70060598e+02
6,45,42,30,21,12,1.30000000e+00,CharacterType.ARCHER,4.43188351e+02
7,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02
8,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
9,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02
10,59,15,25,3,48,1.60000000e+00,CharacterType.ARCHER,4.58394099e+02
11,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
12,55,22,27,29,17,1.50000000e+00,CharacterType.ARCHER,4.84308959e+02
13,59,15,25,3,48,1.60000000e+00,CharacterType.ARCHER,4.58394099e+02
14,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
15,48,28,38,30,6,1.70000000e+00,CharacterType.ARCHER,5.78080781e+02
16,31,10,82,12,15,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02
17,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
18,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
19,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
20,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02
21,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02
22,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02
23,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
24,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02
25,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02
26,66,33,29,7,15,1.60000000e+00,CharacterType.ARCHER,6.14300674e+02
27,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
28,31,10,82,12,15,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02
29,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
30,77,19,32,6,16,1.80000000e+00,CharacterType.ARCHER,7.21362156e+02
31,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
32,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
33,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02
34,45,42,30,21,12,1.30000000e+00,CharacterType.ARCHER,4.43188351e+02
35,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
36,70,4,20,30,26,1.30000000e+00,CharacterType.ARCHER,3.65330404e+02
37,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02
38,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
39,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
40,39,11,65,9,26,1.90000000e+00,CharacterType.ARCHER,7.40617469e+02
41,32,43,34,9,32,1.80000000e+00,CharacterType.ARCHER,4.04549623e+02
42,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
43,32,47,35,5,31,1.70000000e+00,CharacterType.ARCHER,4.08053827e+02
44,70,2,54,3,21,1.50000000e+00,CharacterType.ARCHER,9.68318306e+02
45,39,6,42,30,33,1.60000000e+00,CharacterType.ARCHER,4.86309974e+02
46,31,10,82,12,15,1.50000000e+00,CharacterType.ARCHER,6.72876508e+02
47,70,42,22,12,4,1.80000000e+00,CharacterType.ARCHER,5.57237948e+02
48,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02
49,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02
50,53,34,44,10,9,1.60000000e+00,CharacterType.ARCHER,7.19204680e+02

In [29]:
from selection import stochastic_tournament_selection
#ejemplo
individualsTd = stochastic_tournament_selection(poblacion_inicial, k, 0.6)
individualsTd

,strength,agility,expertise,resistance,life,height,characterType,performance
33,2,99,15,19,15,1.80000000e+00,CharacterType.ARCHER,1.94812460e+01
98,59,15,25,3,48,1.60000000e+00,CharacterType.ARCHER,4.58394099e+02
80,43,7,51,41,8,1.80000000e+00,CharacterType.ARCHER,6.38546478e+02
12,6,28,66,5,45,1.80000000e+00,CharacterType.ARCHER,1.36165674e+02
32,26,66,27,13,18,1.60000000e+00,CharacterType.ARCHER,2.92176025e+02
3,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02
27,41,59,2,16,32,1.40000000e+00,CharacterType.ARCHER,1.35669653e+02
15,22,50,31,24,23,1.60000000e+00,CharacterType.ARCHER,2.63012231e+02
82,32,15,38,11,54,1.50000000e+00,CharacterType.ARCHER,3.96532675e+02
95,35,1,91,18,5,2.00000000e+00,CharacterType.ARCHER,7.89997794e+02
54,48,43,5,34,20,1.70000000e+00,CharacterType.ARCHER,1.67346405e+02
18,32,63,33,14,8,1.90000000e+00,CharacterType.ARCHER,4.27741484e+02
94,6,12,33,90,9,1.80000000e+00,CharacterType.ARCHER,6.83649827e+01
71,18,44,56,21,11,1.90000000e+00,CharacterType.ARCHER,3.46814686e+02
58,44,65,7,12,22,2.00000000e+00,CharacterType.ARCHER,2.22520880e+02
88,7,10,66,24,43,1.50000000e+00,CharacterType.ARCHER,1.49275603e+02
40,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
32,26,66,27,13,18,1.60000000e+00,CharacterType.ARCHER,2.92176025e+02
77,73,18,26,26,7,1.70000000e+00,CharacterType.ARCHER,5.61303144e+02
39,79,2,16,50,3,1.90000000e+00,CharacterType.ARCHER,3.57397787e+02
42,11,57,44,35,3,1.90000000e+00,CharacterType.ARCHER,1.83904595e+02
72,16,7,20,95,12,1.50000000e+00,CharacterType.ARCHER,1.08764475e+02
44,61,3,22,14,50,2.00000000e+00,CharacterType.ARCHER,3.97173625e+02
93,39,6,42,30,33,1.60000000e+00,CharacterType.ARCHER,4.86309974e+02
24,44,42,4,31,29,1.60000000e+00,CharacterType.ARCHER,1.40181014e+02
60,57,56,6,15,16,1.40000000e+00,CharacterType.ARCHER,2.39495046e+02
20,6,47,9,14,74,1.70000000e+00,CharacterType.ARCHER,3.57312150e+01
20,6,47,9,14,74,1.70000000e+00,CharacterType.ARCHER,3.57312150e+01
50,40,11,8,46,45,1.80000000e+00,CharacterType.ARCHER,1.25147290e+02
75,1,56,39,7,47,1.40000000e+00,CharacterType.ARCHER,2.53741723e+01
42,11,57,44,35,3,1.90000000e+00,CharacterType.ARCHER,1.83904595e+02
73,41,20,19,17,53,1.40000000e+00,CharacterType.ARCHER,2.81212477e+02
40,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
23,11,27,46,40,26,1.40000000e+00,CharacterType.ARCHER,1.74363633e+02
30,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,1.00986591e+01
79,55,22,27,29,17,1.50000000e+00,CharacterType.ARCHER,4.84308959e+02
97,17,83,10,17,23,1.30000000e+00,CharacterType.ARCHER,1.07321697e+02
5,16,13,1,89,31,1.60000000e+00,CharacterType.ARCHER,1.84701899e+01
15,22,50,31,24,23,1.60000000e+00,CharacterType.ARCHER,2.63012231e+02
55,48,20,11,20,51,1.30000000e+00,CharacterType.ARCHER,1.91670732e+02
40,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
6,20,32,83,6,9,1.60000000e+00,CharacterType.ARCHER,4.59860327e+02
62,28,5,28,88,1,1.60000000e+00,CharacterType.ARCHER,2.42243160e+02
68,48,28,38,30,6,1.70000000e+00,CharacterType.ARCHER,5.78080781e+02
28,39,4,13,48,46,1.80000000e+00,CharacterType.ARCHER,1.69570871e+02
15,22,50,31,24,23,1.60000000e+00,CharacterType.ARCHER,2.63012231e+02
59,5,34,5,66,40,1.40000000e+00,CharacterType.ARCHER,2.02933598e+01
56,16,14,84,14,22,1.40000000e+00,CharacterType.ARCHER,3.70060598e+02
40,39,61,40,2,8,1.90000000e+00,CharacterType.ARCHER,5.86608774e+02
3,36,8,57,5,44,2.00000000e+00,CharacterType.ARCHER,6.04304680e+02

In [30]:
from selection import rank_based_selection
#ejemplo
individualsR = rank_based_selection(poblacion_inicial,k)
individualsR

sum: 49.5

,strength,agility,expertise,resistance,life,height,characterType,performance,performance_relative,performance_accumulated
0,41,59,2,16,32,1.40000000e+00,CharacterType.ARCHER,6.80000000e-01,1.37373737e-02,5.39797980e-01
1,35,10,25,72,8,1.70000000e+00,CharacterType.ARCHER,4.20000000e-01,8.48484848e-03,8.26060606e-01
2,41,59,2,16,32,1.40000000e+00,CharacterType.ARCHER,6.80000000e-01,1.37373737e-02,5.39797980e-01
3,59,15,25,3,48,1.60000000e+00,CharacterType.ARCHER,2.00000000e-01,4.04040404e-03,9.61616162e-01
4,66,33,29,7,15,1.60000000e+00,CharacterType.ARCHER,7.00000000e-02,1.41414141e-03,9.95757576e-01
5,2,99,15,19,15,1.80000000e+00,CharacterType.ARCHER,9.50000000e-01,1.91919192e-02,9.79797980e-02
6,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,9.80000000e-01,1.97979798e-02,3.97979798e-02
7,20,92,8,18,12,1.90000000e+00,CharacterType.ARCHER,7.10000000e-01,1.43434343e-02,4.97979798e-01
8,16,7,20,95,12,1.50000000e+00,CharacterType.ARCHER,7.80000000e-01,1.57575758e-02,3.93333333e-01
9,26,66,27,13,18,1.60000000e+00,CharacterType.ARCHER,3.90000000e-01,7.87878788e-03,8.50303030e-01
10,5,31,80,19,15,1.90000000e+00,CharacterType.ARCHER,7.30000000e-01,1.47474747e-02,4.69090909e-01
11,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,9.80000000e-01,1.97979798e-02,3.97979798e-02
12,32,43,34,9,32,1.80000000e+00,CharacterType.ARCHER,2.50000000e-01,5.05050505e-03,9.39393939e-01
13,11,57,44,35,3,1.90000000e+00,CharacterType.ARCHER,5.70000000e-01,1.15151515e-02,6.77575758e-01
14,5,56,56,13,20,1.30000000e+00,CharacterType.ARCHER,8.30000000e-01,1.67676768e-02,3.12525253e-01
15,26,66,7,35,16,2.00000000e+00,CharacterType.ARCHER,6.50000000e-01,1.31313131e-02,5.79797980e-01
16,2,99,2,2,45,1.80000000e+00,CharacterType.ARCHER,9.80000000e-01,1.97979798e-02,3.97979798e-02
17,25,4,17,49,55,1.30000000e+00,CharacterType.ARCHER,6.60000000e-01,1.33333333e-02,5.66666667e-01
18,44,65,7,12,22,2.00000000e+00,CharacterType.ARCHER,5.10000000e-01,1.03030303e-02,7.42424242e-01
19,51,31,3,11,54,2.00000000e+00,CharacterType.ARCHER,7.40000000e-01,1.49494949e-02,4.54343434e-01
20,1,56,39,7,47,1.40000000e+00,CharacterType.ARCHER,9.20000000e-01,1.85858586e-02,1.54343434e-01
21,1,56,39,7,47,1.40000000e+00,CharacterType.ARCHER,9.20000000e-01,1.85858586e-02,1.54343434e-01
22,13,64,18,34,21,1.60000000e+00,CharacterType.ARCHER,7.50000000e-01,1.51515152e-02,4.39393939e-01
23,3,53,8,6,80,1.70000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
24,40,10,7,18,75,1.60000000e+00,CharacterType.ARCHER,8.00000000e-01,1.61616162e-02,3.61616162e-01
25,13,64,18,34,21,1.60000000e+00,CharacterType.ARCHER,7.50000000e-01,1.51515152e-02,4.39393939e-01
26,79,2,16,50,3,1.90000000e+00,CharacterType.ARCHER,3.00000000e-01,6.06060606e-03,9.12121212e-01
27,55,22,27,29,17,1.50000000e+00,CharacterType.ARCHER,1.70000000e-01,3.43434343e-03,9.72525253e-01
28,3,53,8,6,80,1.70000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
29,3,53,8,6,80,1.70000000e+00,CharacterType.ARCHER,9.60000000e-01,1.93939394e-02,7.87878788e-02
30,32,12,7,18,81,1.70000000e+00,CharacterType.ARCHER,8.40000000e-01,1.69696970e-02,2.95757576e-01
31,10,12,91,25,12,1.60000000e+00,CharacterType.ARCHER,4.90000000e-01,9.89898990e-03,7.62424242e-01
32,11,27,46,40,26,1.40000000e+00,CharacterType.ARCHER,5.80000000e-01,1.17171717e-02,6.66060606e-01
33,51,69,4,16,10,1.90000000e+00,CharacterType.ARCHER,5.20000000e-01,1.05050505e-02,7.32121212e-01
34,44,65,7,12,22,2.00000000e+00,CharacterType.ARCHER,5.10000000e-01,1.03030303e-02,7.42424242e-01
35,15,6,11,53,65,2.00000000e+00,CharacterType.ARCHER,8.90000000e-01,1.79797980e-02,2.08888889e-01
36,10,12,91,25,12,1.60000000e+00,CharacterType.ARCHER,4.90000000e-01,9.89898990e-03,7.62424242e-01
37,26,66,7,35,16,2.00000000e+00,CharacterType.ARCHER,6.50000000e-01,1.31313131e-02,5.79797980e-01
38,23,32,42,23,30,1.50000000e+00,CharacterType.ARCHER,3.50000000e-01,7.07070707e-03,8.79797980e-01
39,32,12,7,18,81,1.70000000e+00,CharacterType.ARCHER,8.40000000e-01,1.69696970e-02,2.95757576e-01
40,32,12,7,18,81,1.70000000e+00,CharacterType.ARCHER,8.40000000e-01,1.69696970e-02,2.95757576e-01
41,39,4,13,48,46,1.80000000e+00,CharacterType.ARCHER,5.90000000e-01,1.19191919e-02,6.54343434e-01
42,40,10,7,18,75,1.60000000e+00,CharacterType.ARCHER,8.00000000e-01,1.61616162e-02,3.61616162e-01
43,16,7,20,95,12,1.50000000e+00,CharacterType.ARCHER,7.80000000e-01,1.57575758e-02,3.93333333e-01
44,6,12,33,90,9,1.80000000e+00,CharacterType.ARCHER,8.70000000e-01,1.75757576e-02,2.44242424e-01
45,5,34,5,66,40,1.40000000e+00,CharacterType.ARCHER,9.40000000e-01,1.89898990e-02,1.16969697e-01
46,26,66,7,35,16,2.00000000e+00,CharacterType.ARCHER,6.50000000e-01,1.31313131e-02,5.79797980e-01
47,28,57,4,46,15,1.80000000e+00,CharacterType.ARCHER,7.60000000e-01,1.53535354e-02,4.24242424e-01
48,1,56,39,7,47,1.40000000e+00,CharacterType.ARCHER,9.20000000e-01,1.85858586e-02,1.54343434e-01
49,26,66,7,35,16,2.00000000e+00,CharacterType.ARCHER,6.50000000e-01,1.31313131e-02,5.79797980e-01